//! The clock capability: monotonic and wall time as a handed-in trait, so
//! time-dependent behavior is replayable ([`FakeClock`]) and the certified
//! path never consults an ambient clock (see the crate-level doctrine).

use std::sync::Mutex;
use std::time::{Duration, Instant, SystemTime};

/// The clock capability.
pub trait Clock: Send + Sync {
    /// Monotonic time since this clock's own epoch (its construction, for
    /// the std clock). Only differences are meaningful; the epoch is not
    /// comparable across clock instances.
    fn monotonic(&self) -> Duration;

    /// Wall-clock time. Never used on any certified path (wall time is
    /// outside the input closure); provenance timestamps and the Studio use
    /// it.
    fn wall(&self) -> SystemTime;
}

/// The host clock. Monotonic time is measured from construction.
#[derive(Debug)]
pub struct StdClock {
    origin: Instant,
}

impl StdClock {
    /// A clock whose monotonic epoch is now.
    #[must_use]
    pub fn new() -> Self {
        Self {
            origin: Instant::now(),
        }
    }
}

impl Default for StdClock {
    fn default() -> Self {
        Self::new()
    }
}

impl Clock for StdClock {
    fn monotonic(&self) -> Duration {
        self.origin.elapsed()
    }

    fn wall(&self) -> SystemTime {
        SystemTime::now()
    }
}

/// The test double: time advances only when told to, so timeout logic and
/// journaled timing are exactly reproducible.
#[derive(Debug)]
pub struct FakeClock {
    state: Mutex<(Duration, SystemTime)>,
}

impl FakeClock {
    /// A fake clock at monotonic zero and `SystemTime::UNIX_EPOCH`.
    #[must_use]
    pub fn new() -> Self {
        Self {
            state: Mutex::new((Duration::ZERO, SystemTime::UNIX_EPOCH)),
        }
    }

    /// Advance both monotonic and wall time by `by`.
    pub fn advance(&self, by: Duration) {
        let mut s = self
            .state
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner);
        s.0 += by;
        s.1 += by;
    }
}

impl Default for FakeClock {
    fn default() -> Self {
        Self::new()
    }
}

/// Convert a host millisecond reading (`performance.now`, `Date.now`) into
/// a [`Duration`]. The web specifications guarantee non-negative finite
/// values; anything else (a hostile or broken host) saturates to zero rather
/// than panicking — the capability never gets to crash the engine.
///
/// Compiled for tests on every target so the saturation contract is
/// host-provable without a wasm runner.
#[cfg(any(target_arch = "wasm32", test))]
fn duration_from_host_millis(ms: f64) -> Duration {
    if ms.is_finite() && ms > 0.0 {
        Duration::from_secs_f64(ms / 1000.0)
    } else {
        Duration::ZERO
    }
}

/// The browser clock imports. These are extern imports the wasm-bindgen
/// glue (generated by the fmn-wasm surface crate) satisfies at
/// instantiation; they are never linked on native targets.
#[cfg(target_arch = "wasm32")]
#[wasm_bindgen::prelude::wasm_bindgen]
extern "C" {
    /// `performance.now()` — monotonic milliseconds since time origin.
    #[wasm_bindgen::prelude::wasm_bindgen(js_namespace = performance, js_name = now)]
    fn performance_now() -> f64;

    /// `Date.now()` — wall-clock milliseconds since the Unix epoch.
    #[wasm_bindgen::prelude::wasm_bindgen(js_namespace = Date, js_name = now)]
    fn date_now() -> f64;
}

/// The wasm32 host clock (W5 tier 1, fm-l97): monotonic time from
/// `performance.now()` (monotonic per the High Resolution Time spec),
/// wall time from `Date.now()`.
///
/// `std::time::Instant` panics on `wasm32-unknown-unknown`, so
/// [`StdClock`] is not usable there; a wasm host hands this implementation
/// wherever the engine asks for a [`Clock`]. Like every clock reading, the
/// values stay off the certified path — provenance timestamps only (the
/// input closure never contains a clock).
#[cfg(target_arch = "wasm32")]
#[derive(Clone, Copy, Debug, Default)]
pub struct WasmClock;

#[cfg(target_arch = "wasm32")]
impl WasmClock {
    /// The browser clock.
    #[must_use]
    pub const fn new() -> Self {
        Self
    }
}

#[cfg(target_arch = "wasm32")]
impl Clock for WasmClock {
    fn monotonic(&self) -> Duration {
        duration_from_host_millis(performance_now())
    }

    fn wall(&self) -> SystemTime {
        SystemTime::UNIX_EPOCH + duration_from_host_millis(date_now())
    }
}

impl Clock for FakeClock {
    fn monotonic(&self) -> Duration {
        self.state
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner)
            .0
    }

    fn wall(&self) -> SystemTime {
        self.state
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner)
            .1
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fake_clock_advances_only_on_command() {
        let c = FakeClock::new();
        assert_eq!(c.monotonic(), Duration::ZERO);
        assert_eq!(c.wall(), SystemTime::UNIX_EPOCH);
        c.advance(Duration::from_millis(1500));
        assert_eq!(c.monotonic(), Duration::from_millis(1500));
        assert_eq!(
            c.wall(),
            SystemTime::UNIX_EPOCH + Duration::from_millis(1500)
        );
    }

    #[test]
    fn std_clock_is_monotonic() {
        let c = StdClock::new();
        let a = c.monotonic();
        let b = c.monotonic();
        assert!(b >= a);
    }

    // The wasm clock's conversion is host-testable pure logic; the extern
    // imports themselves only link under the wasm-bindgen pipeline.
    #[test]
    fn host_millis_conversion_saturates_hostile_values() {
        assert_eq!(duration_from_host_millis(f64::NAN), Duration::ZERO);
        assert_eq!(duration_from_host_millis(-5.0), Duration::ZERO);
        assert_eq!(duration_from_host_millis(0.0), Duration::ZERO);
        assert_eq!(
            duration_from_host_millis(1500.0),
            Duration::from_millis(1500)
        );
    }
}
