//! The governed-closure audit (D1, fm-g2c): parse the workspace's
//! `Cargo.lock` and the committed `SUITE_ALLOWLIST.tsv`, and refuse any
//! package the allowlist does not admit — the CI teeth behind "no new
//! unreviewed direct runtime dependencies".
//!
//! Both parsers are hand-rolled over line formats (no TOML/serde — the
//! auditor of the closure cannot itself expand the closure). `Cargo.lock`
//! is stable, line-oriented TOML the subset parser below covers fully. The
//! readers deliberately reject syntax they do not understand: silently
//! omitting one malformed package would turn the governance gate fail-open.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt;

const CARGO_LOCK_FILE: &str = "Cargo.lock";
const ALLOWLIST_FILE: &str = "SUITE_ALLOWLIST.tsv";
const CARGO_LOCK_PREAMBLE: &str = "# This file is automatically @generated by Cargo.\n\
# It is not intended for manual editing.\n\
version = 4\n\n";
const MAX_DOCUMENT_BYTES: usize = 8 * 1024 * 1024;
const MAX_LINE_BYTES: usize = 16 * 1024;
const MAX_FIELD_BYTES: usize = 1024;
const MAX_PACKAGE_ROWS: usize = 100_000;
const ALLOWLIST_FIELD_COUNT: usize = 15;
const ALLOWLIST_COLUMNS: [&str; ALLOWLIST_FIELD_COUNT] = [
    "name",
    "version",
    "source",
    "checksum",
    "features",
    "license",
    "build_script",
    "proc_macro",
    "native_link",
    "build_net",
    "unsafe_audit",
    "class",
    "reason",
    "owner",
    "upgrade_policy",
];

/// A governed-closure authority file that could not be parsed exactly.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ClosureParseError {
    /// A whole document exceeded a resource or encoding boundary.
    Document {
        /// The authority file carrying the invalid document.
        file: &'static str,
        /// The bounded reason for refusal.
        detail: String,
    },
    /// A line did not use the canonical supported syntax.
    Syntax {
        /// The authority file carrying the invalid line.
        file: &'static str,
        /// 1-based line number.
        line: usize,
        /// The bounded reason for refusal.
        detail: String,
    },
    /// A TSV row carried the wrong number of fields.
    Arity {
        /// The authority file carrying the invalid row.
        file: &'static str,
        /// 1-based line number.
        line: usize,
        /// Fields the format requires.
        expected: usize,
        /// Fields the row actually had.
        found: usize,
    },
    /// Two records claimed the same package identity incompatibly.
    DuplicateAuthority {
        /// The authority file carrying the duplicate.
        file: &'static str,
        /// 1-based line of the duplicate.
        line: usize,
        /// Bounded package identity.
        identity: String,
        /// 1-based line of the first declaration.
        previous_line: usize,
    },
}

impl fmt::Display for ClosureParseError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Document { file, detail } => write!(f, "{file}: {detail}"),
            Self::Syntax { file, line, detail } => write!(f, "{file}:{line}: {detail}"),
            Self::Arity {
                file,
                line,
                expected,
                found,
            } => write!(
                f,
                "{file}:{line}: allowlist row has {found} fields, expected {expected}"
            ),
            Self::DuplicateAuthority {
                file,
                line,
                identity,
                previous_line,
            } => write!(
                f,
                "{file}:{line}: package authority {identity:?} conflicts with line {previous_line}"
            ),
        }
    }
}

impl std::error::Error for ClosureParseError {}

fn document_error(file: &'static str, detail: impl Into<String>) -> ClosureParseError {
    ClosureParseError::Document {
        file,
        detail: detail.into(),
    }
}

fn syntax_error(file: &'static str, line: usize, detail: impl Into<String>) -> ClosureParseError {
    ClosureParseError::Syntax {
        file,
        line,
        detail: detail.into(),
    }
}

fn validate_document(file: &'static str, text: &str) -> Result<(), ClosureParseError> {
    if text.len() > MAX_DOCUMENT_BYTES {
        return Err(document_error(
            file,
            format!("document exceeds the {MAX_DOCUMENT_BYTES}-byte format limit"),
        ));
    }
    if text.is_empty() {
        return Err(document_error(file, "document is empty"));
    }
    if text.as_bytes().contains(&b'\r') {
        return Err(document_error(file, "CR line endings are not canonical"));
    }
    if !text.ends_with('\n') {
        return Err(document_error(file, "document must end with a newline"));
    }
    for (index, raw) in text.lines().enumerate() {
        let line = index + 1;
        if raw.len() > MAX_LINE_BYTES {
            return Err(syntax_error(
                file,
                line,
                format!("line exceeds the {MAX_LINE_BYTES}-byte format limit"),
            ));
        }
        if raw
            .chars()
            .any(|character| character.is_control() && character != '\t')
        {
            return Err(syntax_error(
                file,
                line,
                "line contains a control character",
            ));
        }
        if raw
            .as_bytes()
            .last()
            .is_some_and(|byte| matches!(byte, b' ' | b'\t'))
        {
            return Err(syntax_error(
                file,
                line,
                "trailing whitespace is not canonical",
            ));
        }
    }
    Ok(())
}

fn canonical_string(
    file: &'static str,
    line: usize,
    field: &'static str,
    encoded: &str,
) -> Result<String, ClosureParseError> {
    let Some(value) = encoded
        .strip_prefix('"')
        .and_then(|value| value.strip_suffix('"'))
    else {
        return Err(syntax_error(
            file,
            line,
            format!("`{field}` must be a quoted string"),
        ));
    };
    if value.is_empty() {
        return Err(syntax_error(file, line, format!("`{field}` is empty")));
    }
    if value.len() > MAX_FIELD_BYTES {
        return Err(syntax_error(
            file,
            line,
            format!("`{field}` exceeds the {MAX_FIELD_BYTES}-byte field limit"),
        ));
    }
    if value
        .chars()
        .any(|character| character.is_control() || matches!(character, '"' | '\\'))
    {
        return Err(syntax_error(
            file,
            line,
            format!("`{field}` is not a canonical unescaped string"),
        ));
    }
    Ok(value.to_owned())
}

fn advance_field(
    line: usize,
    field: &'static str,
    rank: usize,
    previous_rank: &mut usize,
) -> Result<(), ClosureParseError> {
    if rank <= *previous_rank {
        return Err(syntax_error(
            CARGO_LOCK_FILE,
            line,
            format!("`{field}` is repeated or out of canonical order"),
        ));
    }
    *previous_rank = rank;
    Ok(())
}

fn parse_package_block(block: &str, start_line: usize) -> Result<LockedPackage, ClosureParseError> {
    let mut lines = block.lines().enumerate();
    if lines.next().map(|(_, line)| line) != Some("[[package]]") {
        return Err(syntax_error(
            CARGO_LOCK_FILE,
            start_line,
            "expected a `[[package]]` block",
        ));
    }

    let mut name = None;
    let mut version = None;
    let mut source = None;
    let mut checksum = None;
    let mut previous_rank = 0_usize;
    let mut in_dependencies = false;
    let mut dependency_count = 0_usize;

    for (offset, raw) in lines {
        let line = start_line + offset;
        if in_dependencies {
            if raw == "]" {
                if dependency_count == 0 {
                    return Err(syntax_error(
                        CARGO_LOCK_FILE,
                        line,
                        "empty dependencies must use `dependencies = []`",
                    ));
                }
                in_dependencies = false;
                continue;
            }
            let Some(encoded) = raw
                .strip_prefix(' ')
                .and_then(|value| value.strip_suffix(','))
            else {
                return Err(syntax_error(
                    CARGO_LOCK_FILE,
                    line,
                    "malformed dependency-array entry",
                ));
            };
            let _ = canonical_string(CARGO_LOCK_FILE, line, "dependency", encoded)?;
            dependency_count += 1;
            continue;
        }

        if raw == "dependencies = [" || raw == "dependencies = []" {
            advance_field(line, "dependencies", 5, &mut previous_rank)?;
            in_dependencies = raw.ends_with('[');
            continue;
        }

        let Some((key, encoded)) = raw.split_once(" = ") else {
            return Err(syntax_error(
                CARGO_LOCK_FILE,
                line,
                "expected a canonical `key = \"value\"` field",
            ));
        };
        let (rank, field) = match key {
            "name" => (1, "name"),
            "version" => (2, "version"),
            "source" => (3, "source"),
            "checksum" => (4, "checksum"),
            "dependencies" => {
                return Err(syntax_error(
                    CARGO_LOCK_FILE,
                    line,
                    "dependencies must use canonical array syntax",
                ));
            }
            _ => {
                return Err(syntax_error(CARGO_LOCK_FILE, line, "unknown package field"));
            }
        };
        advance_field(line, field, rank, &mut previous_rank)?;
        let value = canonical_string(CARGO_LOCK_FILE, line, field, encoded)?;
        match key {
            "name" => name = Some(value),
            "version" => version = Some(value),
            "source" => source = Some(value),
            "checksum" => checksum = Some(value),
            _ => {
                return Err(syntax_error(CARGO_LOCK_FILE, line, "unknown package field"));
            }
        }
    }

    if in_dependencies {
        return Err(syntax_error(
            CARGO_LOCK_FILE,
            start_line,
            "unterminated dependency array",
        ));
    }
    let Some(name) = name else {
        return Err(syntax_error(
            CARGO_LOCK_FILE,
            start_line,
            "package is missing `name`",
        ));
    };
    let Some(version) = version else {
        return Err(syntax_error(
            CARGO_LOCK_FILE,
            start_line,
            "package is missing `version`",
        ));
    };
    match source.as_deref() {
        None if checksum.is_some() => {
            return Err(syntax_error(
                CARGO_LOCK_FILE,
                start_line,
                "path package has a checksum but no source",
            ));
        }
        Some(value) if value.starts_with("registry+") => {
            let Some(value) = checksum.as_deref() else {
                return Err(syntax_error(
                    CARGO_LOCK_FILE,
                    start_line,
                    "registry package is missing `checksum`",
                ));
            };
            if value.len() != 64
                || !value
                    .bytes()
                    .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
            {
                return Err(syntax_error(
                    CARGO_LOCK_FILE,
                    start_line,
                    "registry checksum must be 64 lowercase hexadecimal characters",
                ));
            }
        }
        Some(value) if value.starts_with("git+") => {
            if checksum.is_some() {
                return Err(syntax_error(
                    CARGO_LOCK_FILE,
                    start_line,
                    "git package must not carry a registry checksum",
                ));
            }
        }
        Some(_) => {
            return Err(syntax_error(
                CARGO_LOCK_FILE,
                start_line,
                "package source must be a supported registry or git source",
            ));
        }
        None => {}
    }

    Ok(LockedPackage {
        name,
        version,
        source,
        checksum,
    })
}

/// One package as recorded in `Cargo.lock`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LockedPackage {
    pub name: String,
    pub version: String,
    /// `None` for workspace path members (Cargo omits `source`).
    pub source: Option<String>,
    /// `None` for path members (Cargo omits `checksum`).
    pub checksum: Option<String>,
}

/// Parse canonical Cargo lockfile v4 text into its package list.
///
/// # Errors
///
/// Returns [`ClosureParseError`] if the document is oversized,
/// noncanonical, incomplete, or contains a duplicate `(name, version)`
/// identity that the allowlist could not distinguish.
pub fn parse_cargo_lock(text: &str) -> Result<Vec<LockedPackage>, ClosureParseError> {
    validate_document(CARGO_LOCK_FILE, text)?;
    if text.ends_with("\n\n") {
        return Err(document_error(
            CARGO_LOCK_FILE,
            "document must not end with a blank line",
        ));
    }
    let Some(body) = text.strip_prefix(CARGO_LOCK_PREAMBLE) else {
        let mut found = text.lines();
        let mut line = 1_usize;
        for (index, expected) in CARGO_LOCK_PREAMBLE.lines().enumerate() {
            line = index + 1;
            if found.next() != Some(expected) {
                break;
            }
        }
        return Err(syntax_error(
            CARGO_LOCK_FILE,
            line,
            "expected the canonical Cargo lockfile v4 preamble",
        ));
    };
    if body.is_empty() {
        return Err(document_error(CARGO_LOCK_FILE, "lockfile has no packages"));
    }
    let Some(package_text) = body.strip_suffix('\n') else {
        return Err(document_error(
            CARGO_LOCK_FILE,
            "document must end with a newline",
        ));
    };

    let mut packages = Vec::new();
    let mut identities: BTreeMap<(String, String), usize> = BTreeMap::new();
    let mut start_line = 5_usize;
    for block in package_text.split("\n\n") {
        if packages.len() >= MAX_PACKAGE_ROWS {
            return Err(document_error(
                CARGO_LOCK_FILE,
                format!("lockfile exceeds the {MAX_PACKAGE_ROWS}-package format limit"),
            ));
        }
        let block_lines = block.lines().count();
        let package = parse_package_block(block, start_line)?;
        let identity = (package.name.clone(), package.version.clone());
        if let Some(previous_line) = identities.insert(identity.clone(), start_line) {
            return Err(ClosureParseError::DuplicateAuthority {
                file: CARGO_LOCK_FILE,
                line: start_line,
                identity: format!("{} {}", identity.0, identity.1),
                previous_line,
            });
        }
        packages.push(package);
        start_line = start_line.saturating_add(block_lines + 1);
    }
    Ok(packages)
}

/// One row of the allowlist.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AllowRow {
    pub name: String,
    pub version: String,
    pub source: String,
    pub checksum: String,
    pub class: String,
}

fn validate_allowlist_field(
    line: usize,
    column: &'static str,
    value: &str,
) -> Result<(), ClosureParseError> {
    if value.is_empty() {
        return Err(syntax_error(
            ALLOWLIST_FILE,
            line,
            format!("`{column}` field is empty"),
        ));
    }
    if value.len() > MAX_FIELD_BYTES {
        return Err(syntax_error(
            ALLOWLIST_FILE,
            line,
            format!("`{column}` exceeds the {MAX_FIELD_BYTES}-byte field limit"),
        ));
    }
    if value.trim() != value || value.chars().any(char::is_control) {
        return Err(syntax_error(
            ALLOWLIST_FILE,
            line,
            format!("`{column}` field is padded or contains a control character"),
        ));
    }
    Ok(())
}

fn validate_allowlist_vocabulary(
    line: usize,
    fields: &[&str; ALLOWLIST_FIELD_COUNT],
) -> Result<(), ClosureParseError> {
    let [
        _,
        _,
        source,
        checksum,
        _,
        _,
        build_script,
        proc_macro,
        _,
        build_net,
        unsafe_audit,
        class,
        _,
        _,
        _,
    ] = *fields;
    if !matches!(source, "workspace" | "path" | "crates-io")
        && !(source.starts_with("git+") && source.ends_with("@SUITE.lock"))
    {
        return Err(syntax_error(
            ALLOWLIST_FILE,
            line,
            "`source` is not a governed source vocabulary value",
        ));
    }
    if !matches!(checksum, "-" | "TBD")
        && (checksum.len() != 64
            || !checksum
                .bytes()
                .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte)))
    {
        return Err(syntax_error(
            ALLOWLIST_FILE,
            line,
            "`checksum` must be `-`, `TBD`, or 64 lowercase hexadecimal characters",
        ));
    }
    if source == "crates-io" && checksum == "-" {
        return Err(syntax_error(
            ALLOWLIST_FILE,
            line,
            "a crates-io row must carry a checksum or `TBD`",
        ));
    }
    if source != "crates-io" && checksum != "-" {
        return Err(syntax_error(
            ALLOWLIST_FILE,
            line,
            "workspace, path, and git rows must use checksum `-`",
        ));
    }
    if !matches!(build_script, "yes" | "no") {
        return Err(syntax_error(
            ALLOWLIST_FILE,
            line,
            "`build_script` must be `yes` or `no`",
        ));
    }
    if !matches!(proc_macro, "yes" | "no" | "via-derive") {
        return Err(syntax_error(
            ALLOWLIST_FILE,
            line,
            "`proc_macro` must be `yes`, `no`, or `via-derive`",
        ));
    }
    if !matches!(build_net, "yes" | "no") {
        return Err(syntax_error(
            ALLOWLIST_FILE,
            line,
            "`build_net` must be `yes` or `no`",
        ));
    }
    if !matches!(
        unsafe_audit,
        "forbid" | "expansion" | "audited-ffi" | "pending"
    ) {
        return Err(syntax_error(
            ALLOWLIST_FILE,
            line,
            "`unsafe_audit` is not a governed vocabulary value",
        ));
    }
    if !matches!(
        class,
        "workspace" | "runtime" | "ffi" | "build" | "dev" | "fuzz" | "pending"
    ) {
        return Err(syntax_error(
            ALLOWLIST_FILE,
            line,
            "`class` is not a governed vocabulary value",
        ));
    }
    if checksum == "TBD" && class != "pending" {
        return Err(syntax_error(
            ALLOWLIST_FILE,
            line,
            "only a pending row may defer its checksum as `TBD`",
        ));
    }
    Ok(())
}

/// Parse canonical `SUITE_ALLOWLIST.tsv` text (comments and blanks skipped).
///
/// Multiple rows for one `(name, version)` are retained when their source and
/// checksum agree, because distinct governed consumers can carry different
/// feature or class policy. Conflicting core authority is rejected.
///
/// # Errors
///
/// Returns [`ClosureParseError`] if the document is oversized,
/// noncanonical, malformed, empty, or contains conflicting package
/// authority.
pub fn parse_allowlist(text: &str) -> Result<Vec<AllowRow>, ClosureParseError> {
    validate_document(ALLOWLIST_FILE, text)?;
    let mut rows = Vec::new();
    let mut exact_rows: BTreeMap<String, usize> = BTreeMap::new();
    let mut authorities: BTreeMap<(String, String), (usize, String, String)> = BTreeMap::new();

    for (index, raw) in text.lines().enumerate() {
        let line = index + 1;
        if raw.is_empty() || raw.starts_with('#') {
            continue;
        }
        if rows.len() >= MAX_PACKAGE_ROWS {
            return Err(document_error(
                ALLOWLIST_FILE,
                format!("allowlist exceeds the {MAX_PACKAGE_ROWS}-row format limit"),
            ));
        }
        let fields: Vec<&str> = raw.split('\t').collect();
        let found = fields.len();
        let Ok(fields): Result<[&str; ALLOWLIST_FIELD_COUNT], _> = fields.try_into() else {
            return Err(ClosureParseError::Arity {
                file: ALLOWLIST_FILE,
                line,
                expected: ALLOWLIST_FIELD_COUNT,
                found,
            });
        };
        for (column, value) in ALLOWLIST_COLUMNS.into_iter().zip(fields.iter().copied()) {
            validate_allowlist_field(line, column, value)?;
        }
        validate_allowlist_vocabulary(line, &fields)?;

        let [
            name,
            version,
            source,
            checksum,
            _,
            _,
            _,
            _,
            _,
            _,
            _,
            class,
            _,
            _,
            _,
        ] = fields;

        if let Some(previous_line) = exact_rows.insert(raw.to_owned(), line) {
            return Err(ClosureParseError::DuplicateAuthority {
                file: ALLOWLIST_FILE,
                line,
                identity: format!("{name} {version} exact row"),
                previous_line,
            });
        }
        let identity = (name.to_owned(), version.to_owned());
        if let Some((previous_line, previous_source, previous_checksum)) =
            authorities.get(&identity)
        {
            if previous_source != source || previous_checksum != checksum {
                return Err(ClosureParseError::DuplicateAuthority {
                    file: ALLOWLIST_FILE,
                    line,
                    identity: format!("{} {}", identity.0, identity.1),
                    previous_line: *previous_line,
                });
            }
        } else {
            authorities.insert(identity, (line, source.to_owned(), checksum.to_owned()));
        }
        rows.push(AllowRow {
            name: name.to_owned(),
            version: version.to_owned(),
            source: source.to_owned(),
            checksum: checksum.to_owned(),
            class: class.to_owned(),
        });
    }
    if rows.is_empty() {
        return Err(document_error(
            ALLOWLIST_FILE,
            "allowlist has no package rows",
        ));
    }
    Ok(rows)
}

/// A closure violation, ready for a CI failure message.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Violation {
    /// A locked package with no allowlist row.
    Unlisted { name: String, version: String },
    /// A locked package whose recorded checksum differs from the
    /// allowlist's.
    ChecksumMismatch {
        name: String,
        locked: String,
        allowed: String,
    },
    /// A locked package came from a different source class or suite repo than
    /// the allowlist row admits.
    SourceMismatch {
        name: String,
        locked: String,
        allowed: String,
    },
    /// An allowlist row marked as consumed (non-pending, non-workspace)
    /// that no locked package matches — a stale row is an audit smell.
    StaleRow { name: String },
}

impl std::fmt::Display for Violation {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Unlisted { name, version } => write!(
                f,
                "package `{name} {version}` is in Cargo.lock but NOT in SUITE_ALLOWLIST.tsv — \
                 the governed closure (D1) admits nothing unlisted"
            ),
            Self::ChecksumMismatch {
                name,
                locked,
                allowed,
            } => write!(
                f,
                "package `{name}` checksum drift: lock has {locked}, allowlist has {allowed}"
            ),
            Self::SourceMismatch {
                name,
                locked,
                allowed,
            } => write!(
                f,
                "package `{name}` source drift: lock has {locked}, allowlist admits {allowed}"
            ),
            Self::StaleRow { name } => write!(
                f,
                "allowlist row `{name}` is marked consumed but absent from Cargo.lock — \
                 remove or re-class the row deliberately"
            ),
        }
    }
}

fn source_is_admitted(locked: Option<&str>, allowed: &str) -> bool {
    match locked {
        None => matches!(allowed, "workspace" | "path"),
        Some("registry+https://github.com/rust-lang/crates.io-index") => allowed == "crates-io",
        Some(source) if source.starts_with("git+") => {
            let Some(expected_repo) = allowed
                .strip_prefix("git+")
                .and_then(|value| value.strip_suffix("@SUITE.lock"))
            else {
                return false;
            };
            let repository = source
                .strip_prefix("git+")
                .and_then(|value| value.split(['?', '#']).next())
                .and_then(|value| value.rsplit('/').next())
                .map(|value| value.strip_suffix(".git").unwrap_or(value));
            repository == Some(expected_repo)
        }
        Some(_) => false,
    }
}

/// Audit the lock against the allowlist. Empty result = the closure is
/// exactly the governed universe.
#[must_use]
pub fn audit(lock: &[LockedPackage], allowlist: &[AllowRow]) -> Vec<Violation> {
    audit_with_aux(lock, &[], allowlist)
}

/// The ADR-0003 form: non-member crates (the fuzz harness, non-member
/// spikes like G0-5's bridge) keep their own committed lockfiles, and
/// their packages carry allowlist rows like anything else. Admission and
/// checksum rules are uniform across every governed lock; a consumed row
/// is stale only when absent from all of them.
#[must_use]
pub fn audit_with_aux(
    lock: &[LockedPackage],
    aux_locks: &[Vec<LockedPackage>],
    allowlist: &[AllowRow],
) -> Vec<Violation> {
    let mut violations = Vec::new();
    let mut seen: BTreeSet<(&str, &str)> = BTreeSet::new();
    let mut audited: BTreeSet<(&str, &str, Option<&str>, Option<&str>)> = BTreeSet::new();
    let mut allowed_by_package: BTreeMap<(&str, &str), &AllowRow> = BTreeMap::new();
    for row in allowlist {
        allowed_by_package
            .entry((row.name.as_str(), row.version.as_str()))
            .or_insert(row);
    }
    for package in lock.iter().chain(aux_locks.iter().flatten()) {
        let key = (package.name.as_str(), package.version.as_str());
        seen.insert(key);
        let audit_key = (
            package.name.as_str(),
            package.version.as_str(),
            package.source.as_deref(),
            package.checksum.as_deref(),
        );
        if !audited.insert(audit_key) {
            continue; // identical package records need only one verdict
        }
        // Rows are keyed by (name, version), which is what the file's own
        // schema has always said and what independently-resolved locks
        // require: the G0-5 spike's PyO3 graph pins `syn 2`, the G0-8 spike's
        // Metal graph pins `syn 3`, and neither can move. Keying by name alone
        // would let one non-shipped spike's transitive constraint veto
        // another's — a governance failure dressed as a governance check.
        // Every version still needs its own reviewed row and its own checksum,
        // so nothing is loosened: an unlisted *version* fails exactly like an
        // unlisted package. (ADR-0008.)
        match allowed_by_package.get(&key).copied() {
            None => violations.push(Violation::Unlisted {
                name: package.name.clone(),
                version: package.version.clone(),
            }),
            Some(row) => {
                if !source_is_admitted(package.source.as_deref(), &row.source) {
                    violations.push(Violation::SourceMismatch {
                        name: package.name.clone(),
                        locked: package.source.clone().unwrap_or_else(|| "path".to_owned()),
                        allowed: row.source.clone(),
                    });
                }
                let locked_sum = package.checksum.as_deref().unwrap_or("-");
                if row.checksum != "TBD" && row.checksum != locked_sum {
                    violations.push(Violation::ChecksumMismatch {
                        name: package.name.clone(),
                        locked: locked_sum.to_string(),
                        allowed: row.checksum.clone(),
                    });
                }
            }
        }
    }
    for row in allowlist {
        let consumed_class = row.class != "pending";
        if consumed_class && !seen.contains(&(row.name.as_str(), row.version.as_str())) {
            violations.push(Violation::StaleRow {
                name: row.name.clone(),
            });
        }
    }
    violations
}
