//! Correctness oracles (§16.3 plane 1, fm-t1v).
//!
//! §16.3 names three test planes; this module is plane 1's machinery. Its
//! layout follows §16.3's own taxonomy for the plane — every oracle below
//! is filed under exactly one of these rows, and the integration tests in
//! `tests/oracles.rs` assert each measured error against its tolerance:
//!
//! 1. **Analytic ground truths.**
//!    - *Arc length vs closed forms* — [`circle_arc_length_rel_error`]
//!      (quadratic circle model vs the analytic circumference),
//!      [`quadratic_arc_length_vs_quadrature`] and
//!      [`path_arc_length_vs_quadrature`] (the closed form of
//!      `fmn_geom::arclength` vs an independent Gauss–Legendre integral —
//!      the ellipse case: a scaled circle model has no elementary
//!      circumference, so the honest reference is a high-precision
//!      integral of the model itself, computed by a *different* method).
//!    - *Path-boolean identities* — [`boolean_union_commutes_area_error`],
//!      [`boolean_partition_area_error`], [`boolean_de_morgan_area_error`].
//!    - *Winding invariants* — [`winding_translation_max_error`] (integer
//!      translations preserve winding numbers), [`probe_winding`] and
//!      [`winding_probes_max_error`] (nested containment: the number of
//!      signed turns at a probe, whose parity each fill rule reads
//!      differently — the tests assert the per-rule filledness flips).
//!    - *Color-model round-trips* — the sRGB transfer functions live in
//!      `fmn-frame`, a deliberate dev-only edge of this crate, so the
//!      round-trip measurement (`srgb_decode ∘ srgb_encode`, and the full
//!      byte → decode → encode → byte pipeline) is an oracle *test* in
//!      `tests/oracles.rs`, not a function here.
//!    - *TeX Appendix-G placement parameters* — [`tex_appendix_g_errors`]
//!      measures the remaining taxonomy rows through the pinned fmd-math
//!      engine: the σ₁₃/σ₁₄/σ₁₅ superscript shifts, the σ₁₆ subscript
//!      shift, rule 18's 4θ script separation, and rule 11's radical
//!      overbar. The axis-centered fraction bar (σ₂₂, ξ₈) is already
//!      pinned by `fmn-tex/tests/fmd_math_surface.rs`
//!      (`typeset_produces_placed_output_through_the_pin`) and is not
//!      duplicated here; the pin's own upstream suite covers the full
//!      parameter family, but that suite does not run in this repo's CI,
//!      which is what this oracle is for.
//!
//! 2. **Metamorphic laws, restricted to valid laws.**
//!    - *Integer-pixel translation equivariance* — a frame-level law; it
//!      lives with the other frame-level assertions in `tests/oracles.rs`
//!      (same dev-only `fmn-frame` edge as the color oracles). Its domain
//!      boundary, found by measurement, is documented on the test.
//!    - *Stateless resampling* — [`stateless_resampling_max_error`]:
//!      resampling a path at a second density (uniform subdivision) and
//!      evaluating both densities at common arc-length parameters yields
//!      points that lie on the original curve.
//!    - *Subdivision invariance* — [`boolean_subdivision_area_error`]:
//!      boolean results are invariant under path resampling. The valid
//!      domain is *area* agreement within a tolerance that scales with
//!      the flattening bound — see the function's docs for the boundary.
//!
//! 3. **Structural fixtures against the Reference** (§16.4's loose
//!    tolerances, since we compute in f64 over the same formulas).
//!    [`FixtureCorpus`] builds on [`crate::npy`] to load the
//!    `fixtures/npy` corpus with manifest-hash verification. The corpus
//!    rows and who compares them:
//!    - *constructor point arrays* (arc component arrays) and *positional
//!      API results* (partial-curve extraction, parameter evaluation, the
//!      integer/residue curve walk) — this module's tests, exercising the
//!      rows added with this bead (`arc_half_n8`, `partial_quad_*`,
//!      `quad_eval`, `integer_interpolate`).
//!    - *family shapes* (Polygon, Rectangle, Line, Circle, Arc, Ellipse,
//!      RegularPolygon point arrays) — already locked against the
//!      Reference by `fmn-library/tests/geometry_parity.rs` (30 cases,
//!      generated by `scripts/gen_geometry_fixtures.py`), so they are not
//!      re-fixed here; duplicating them would only assert the same
//!      formulas twice.
//!    - `point_from_proportion` positional results are deliberately *not*
//!      fixture-compatible: our proportion layer is true arc length
//!      (fm-xci, BN-03) where the Reference's is a chord heuristic, so
//!      there is no coincident formula to fixture.
//!
//! Every function here returns its **measured error** (or the measurement
//! record) rather than asserting: the library stays panic-free and the
//! test target owns the pass/fail bar, per this crate's doctrine.

use std::collections::BTreeMap;
use std::fmt;
use std::io::Read;
use std::path::{Path, PathBuf};

use fmn_core::constants::TAU;
use fmn_core::types::Vec3;
use fmn_geom::arclength::{ArcLengthTable, quadratic_arc_length};
use fmn_geom::bezier;
use fmn_geom::boolean::{
    BooleanError, BooleanOperation, BooleanOptions, BooleanResult, path_boolean,
};
use fmn_geom::distance::distance_to_quadratic;
use fmn_geom::quadpath::QuadPath;
use fmn_geom::space_ops::get_winding_number;
use fmn_hash::sha256;

use crate::npy::{NpyArray, NpyData, read_npy};

/// A failure to produce an oracle measurement (distinct from a measurement
/// that exceeds its tolerance — that is the test's call, not this type's).
#[derive(Debug)]
pub enum OracleError {
    /// A path boolean refused or exhausted a budget.
    Boolean(BooleanError),
    /// A geometry constructor refused its inputs.
    Geom(String),
    /// The TeX engine's bundled faces failed to load, or a typeset call
    /// refused the probe source.
    Tex(String),
    /// A fixture row was missing, corrupt, or shaped wrong.
    Fixture(String),
}

impl fmt::Display for OracleError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Boolean(e) => write!(f, "boolean oracle input refused: {e}"),
            Self::Geom(e) => write!(f, "geometry oracle input refused: {e}"),
            Self::Tex(e) => write!(f, "TeX oracle failed to produce a layout: {e}"),
            Self::Fixture(e) => write!(f, "fixture corpus: {e}"),
        }
    }
}

impl std::error::Error for OracleError {}

impl From<BooleanError> for OracleError {
    fn from(e: BooleanError) -> Self {
        Self::Boolean(e)
    }
}

// =====================================================================
// 1. Analytic ground truths — arc length vs closed forms
// =====================================================================

/// Relative error of the quadratic circle model's arc length against the
/// analytic circumference: `|L − 2πr| / (2πr)` for the full-circle
/// [`QuadPath::try_arc`] at `radius`.
///
/// The model is sixteen quadratic Béziers standing in for the circle (the
/// BN-09 density rule), so this error is *not* rounding — it is the
/// approximation shortfall of the model itself, and the test's tolerance
/// is a property of the model, pinned against regression. Measured:
/// 1.006e-4 relative, independent of radius.
#[must_use]
pub fn circle_arc_length_rel_error(radius: f64) -> f64 {
    let path = QuadPath::try_arc(0.0, TAU, radius, [0.0; 3], None)
        .expect("the oracle's fixed full-turn component request is valid");
    let measured = ArcLengthTable::for_path(&path).total();
    let analytic = TAU * radius.abs();
    if analytic == 0.0 {
        return 0.0;
    }
    (measured - analytic).abs() / analytic
}

/// Nodes and weights for 3-point Gauss–Legendre quadrature on `[0, 1]`
/// (exact for polynomials through degree 5; the integrand here — the norm
/// of a linear vector — is smooth, so panels converge fast).
const GL3: [(f64, f64); 3] = [
    (0.5 - 0.5 * 0.774_596_669_241_483, 5.0 / 9.0),
    (0.5, 8.0 / 9.0),
    (0.5 + 0.5 * 0.774_596_669_241_483, 5.0 / 9.0),
];

/// The speed `|B'(t)|` of one quadratic, the quadrature integrand. This is
/// an *independent* evaluation: [`quadratic_arc_length`] integrates a
/// closed-form antiderivative, this samples the derivative directly.
fn quadratic_speed(a0: Vec3, h: Vec3, a1: Vec3, t: f64) -> f64 {
    let d = [
        2.0 * ((1.0 - t) * (h[0] - a0[0]) + t * (a1[0] - h[0])),
        2.0 * ((1.0 - t) * (h[1] - a0[1]) + t * (a1[1] - h[1])),
        2.0 * ((1.0 - t) * (h[2] - a0[2]) + t * (a1[2] - h[2])),
    ];
    (d[0] * d[0] + d[1] * d[1] + d[2] * d[2]).sqrt()
}

/// Composite 3-point Gauss–Legendre integral of the quadratic's speed
/// over `panels` equal panels. Monotonic in accuracy; deterministic.
fn quadrature_arc_length(a0: Vec3, h: Vec3, a1: Vec3, panels: usize) -> f64 {
    let panels = panels.max(1);
    let width = 1.0 / panels as f64;
    let mut total = 0.0;
    for panel in 0..panels {
        let base = panel as f64 * width;
        for (node, weight) in GL3 {
            total += weight * quadratic_speed(a0, h, a1, base + node * width);
        }
    }
    total * width * 0.5
}

/// Absolute error of the closed-form [`quadratic_arc_length`] against an
/// independent Gauss–Legendre integral of the same curve's speed, at
/// `panels` panels. This is the quadratic-Bézier row of the taxonomy: the
/// two computations share no code path (one evaluates an antiderivative
/// with a logarithm; the other samples the derivative), so agreement is
/// evidence for the closed form, not for a common mistake.
#[must_use]
pub fn quadratic_arc_length_vs_quadrature(a0: Vec3, h: Vec3, a1: Vec3, panels: usize) -> f64 {
    let closed = quadratic_arc_length(a0, h, a1);
    let numeric = quadrature_arc_length(a0, h, a1, panels);
    (closed - numeric).abs()
}

/// Relative error of a whole path's [`ArcLengthTable`] total against the
/// same independent quadrature summed curve by curve, at `panels` panels
/// per curve.
///
/// This is the ellipse row: an ellipse-shaped quadratic model (a circle
/// model under a non-uniform scale) has no elementary circumference, so
/// the analytic reference for the *model's* length is a high-precision
/// integral, and computing it by a different method keeps the check
/// honest. Returns 0.0 for an empty path.
#[must_use]
pub fn path_arc_length_vs_quadrature(path: &QuadPath, panels: usize) -> f64 {
    let closed = ArcLengthTable::for_path(path).total();
    if closed == 0.0 {
        return 0.0;
    }
    let numeric: f64 = path
        .bezier_tuples()
        .map(|[a0, h, a1]| quadrature_arc_length(a0, h, a1, panels))
        .sum();
    (closed - numeric).abs() / closed
}

// =====================================================================
// 1. Analytic ground truths — path-boolean identities
// =====================================================================

/// The signed fill area of a boolean result: the exact quadratic boundary
/// integral `⅓·cross(p0,h) + ⅙·cross(p0,p2) + ⅓·cross(h,p2)` per piece
/// plus each subpath's implicit closing chord, signed per contour so
/// oppositely wound holes subtract. For the flatten-and-clip route every
/// piece is a line quadratic (`h` on the chord) and the formula reduces
/// to the anchor shoelace exactly; for the curve-aware routes it is the
/// exact area of the curve-preserving output the anchor polygon would
/// only approximate (fm-qjy).
fn fill_area(result: &BooleanResult) -> f64 {
    exact_path_area(&result.path)
}

/// The exact quadratic boundary integral of any path, including each
/// subpath's implicit fill-closing chord (matching `area_vector`'s cyclic
/// wrap and Stage-1 fill semantics; identical values on line-only paths).
fn exact_path_area(path: &QuadPath) -> f64 {
    let cross = |a: [f64; 3], b: [f64; 3]| a[0] * b[1] - a[1] * b[0];
    path.subpaths()
        .iter()
        .map(|subpath| {
            let pieces: f64 = subpath
                .windows(3)
                .step_by(2)
                .map(|piece| {
                    (cross(piece[0], piece[1])
                        + 0.5 * cross(piece[0], piece[2])
                        + cross(piece[1], piece[2]))
                        / 3.0
                })
                .sum();
            let first = subpath[0];
            let last = subpath[subpath.len() - 1];
            pieces + 0.5 * cross(last, first)
        })
        .sum::<f64>()
        .abs()
}

/// One boolean evaluated for the identity oracles.
fn boolean_area(
    subject: &QuadPath,
    clip: &QuadPath,
    operation: BooleanOperation,
    options: BooleanOptions,
) -> Result<f64, OracleError> {
    let result = path_boolean(subject, clip, operation, options)?;
    Ok(fill_area(&result))
}

/// `|area(A∪B) − area(B∪A)|` — union commutativity, measured on the
/// arrangement outputs.
///
/// # Errors
/// [`OracleError::Boolean`] if either evaluation refuses its inputs.
pub fn boolean_union_commutes_area_error(
    a: &QuadPath,
    b: &QuadPath,
    options: BooleanOptions,
) -> Result<f64, OracleError> {
    let forward = boolean_area(a, b, BooleanOperation::Union, options)?;
    let backward = boolean_area(b, a, BooleanOperation::Union, options)?;
    Ok((forward - backward).abs())
}

/// `|area(A∩B) + area(A−B) − area(A)|` — the intersection/difference
/// partition of the subject. `area(A)` is measured by the same exact
/// quadratic boundary integral as the boolean outputs, so the identity is
/// exact for polygonal subjects (the oracles use corner rectangles) and
/// stays exact for curve-preserving route outputs; for flattened curved
/// subjects the flatten-tolerance boundary of
/// [`boolean_subdivision_area_error`] applies.
///
/// # Errors
/// [`OracleError::Boolean`] if an evaluation refuses its inputs.
pub fn boolean_partition_area_error(
    a: &QuadPath,
    b: &QuadPath,
    options: BooleanOptions,
) -> Result<f64, OracleError> {
    let intersection = boolean_area(a, b, BooleanOperation::Intersection, options)?;
    let difference = boolean_area(a, b, BooleanOperation::Difference, options)?;
    let subject = exact_path_area(a);
    Ok((intersection + difference - subject).abs())
}

/// De Morgan through a universe: `|area(A∪B) − (area(U) − area((U−A) ∩ (U−B)))|`
/// where `universe` must contain both operands in its filled set. The
/// complements `U−A` and `U−B` are what make this an arrangement identity
/// rather than a restatement of commutativity.
///
/// # Errors
/// [`OracleError::Boolean`] if an evaluation refuses its inputs.
pub fn boolean_de_morgan_area_error(
    a: &QuadPath,
    b: &QuadPath,
    universe: &QuadPath,
    options: BooleanOptions,
) -> Result<f64, OracleError> {
    let union = boolean_area(a, b, BooleanOperation::Union, options)?;
    let not_a = path_boolean(universe, a, BooleanOperation::Difference, options)?;
    let not_b = path_boolean(universe, b, BooleanOperation::Difference, options)?;
    let complement_of_union = path_boolean(
        &not_a.path,
        &not_b.path,
        BooleanOperation::Intersection,
        options,
    )?;
    let whole = exact_path_area(universe);
    Ok((union - (whole - fill_area(&complement_of_union))).abs())
}

// =====================================================================
// 1. Analytic ground truths — winding invariants
// =====================================================================

/// The winding number of the closed polyline `points` about `query`
/// (xy-plane). [`get_winding_number`] winds about the origin; translating
/// the polyline by `−query` recenters it.
#[must_use]
pub fn winding_number_about(points: &[Vec3], query: Vec3) -> f64 {
    let recentered: Vec<Vec3> = points
        .iter()
        .map(|p| [p[0] - query[0], p[1] - query[1], p[2] - query[2]])
        .collect();
    get_winding_number(&recentered)
}

/// Maximum deviation from integer invariance under integer translations:
/// for each `(polygon, query, translation)` triple this compares
/// `w(P about q)` against `w(P+t about q+t)` — the winding number is a
/// translation-covariant quantity, so the two must agree to rounding.
/// Returns the largest discrepancy found; ~1e-15 in practice.
#[must_use]
pub fn winding_translation_max_error(
    polygons: &[&[Vec3]],
    queries: &[Vec3],
    translations: &[Vec3],
) -> f64 {
    let mut worst = 0.0f64;
    for &polygon in polygons {
        for &query in queries {
            let base = winding_number_about(polygon, query);
            for &t in translations {
                let shifted: Vec<Vec3> = polygon
                    .iter()
                    .map(|p| [p[0] + t[0], p[1] + t[1], p[2] + t[2]])
                    .collect();
                let moved = winding_number_about(
                    &shifted,
                    [query[0] + t[0], query[1] + t[1], query[2] + t[2]],
                );
                worst = worst.max((base - moved).abs());
            }
        }
    }
    worst
}

/// One probe of a nested-containment winding measurement.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct WindingProbe {
    /// The probe point (xy).
    pub query: Vec3,
    /// The winding number the contours produce there, as measured.
    pub measured: f64,
    /// The exact integer the geometry dictates.
    pub expected: i64,
}

/// Error of one probe: `|measured − expected|`.
#[must_use]
pub fn winding_probe_error(probe: &WindingProbe) -> f64 {
    (probe.measured - probe.expected as f64).abs()
}

/// Measure the winding number of `contours` (each a closed polyline) at
/// `query`: the sum of the per-contour winding numbers. Nested opposite-
/// wound contours cancel (a hole reads 0); nested same-wound contours
/// accumulate (a doubly-wound region reads ±2) — the parity difference
/// the fill rules key on.
#[must_use]
pub fn probe_winding(contours: &[&[Vec3]], query: Vec3) -> WindingProbe {
    let measured: f64 = contours
        .iter()
        .map(|c| winding_number_about(c, query))
        .sum();
    WindingProbe {
        query,
        measured,
        expected: measured.round() as i64,
    }
}

/// Largest probe error over a set, the number a test asserts small.
#[must_use]
pub fn winding_probes_max_error(probes: &[WindingProbe]) -> f64 {
    probes.iter().map(winding_probe_error).fold(0.0, f64::max)
}

// =====================================================================
// 1. Analytic ground truths — TeX Appendix-G placement parameters
// =====================================================================

/// The measured Appendix-G placement errors (in ems) for the taxonomy
/// rows not already pinned by `fmn-tex`'s surface test. Every field is an
/// absolute error against the published Computer Modern parameter
/// ([`fmd_math::metrics::CM`]), except `script_separation_over_4theta`,
/// which is a clearance margin: `(sup_y − sub_y) − 4θ`, required to be
/// **positive** by rule 18 rather than near zero.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct TexAppendixG {
    /// σ₁₃: display-style uncramped superscript shift (`x^2`, Display).
    pub display_superscript_shift: f64,
    /// σ₁₄: non-display uncramped superscript shift (`x^2`, Text).
    pub text_superscript_shift: f64,
    /// σ₁₅: cramped superscript shift (`\sqrt{x^2}`, Display).
    pub cramped_superscript_shift: f64,
    /// σ₁₆: lone subscript shift (`x_i`, Display).
    pub lone_subscript_shift: f64,
    /// Rule 18 margin for `x_i^2` in Display: the measured
    /// superscript-to-subscript separation minus 4θ. Valid when positive.
    pub script_separation_over_4theta: f64,
    /// ξ₈: the radical overbar's thickness (`\sqrt{x}`, Display).
    pub radical_rule_thickness: f64,
    /// Rule 11 margin: the clearance between the `\sqrt{x}` overbar and
    /// the radicand's height minus ψ (θ + x-height/4). Valid when
    /// positive (CM's surd overshoots, so this is strictly positive).
    pub radical_clearance_over_psi: f64,
}

/// Measure the Appendix-G rows through the pinned fmd-math engine at its
/// published CM constants. Cases are chosen so the clearance terms of the
/// rules do not bind (short glyphs, display style), making the published
/// parameter the exact expected coordinate — the same discipline as the
/// pin's upstream placement suite, asserted here so a SUITE.lock bump
/// that drifted placement fails in *this* repo's CI.
///
/// # Errors
/// [`OracleError::Tex`] if the bundled faces fail to load or a probe
/// source fails to typeset.
pub fn tex_appendix_g_errors() -> Result<TexAppendixG, OracleError> {
    use fmd_math::Style;

    let engine = fmd_math::Engine::bundled().map_err(|e| OracleError::Tex(e.to_string()))?;
    let c = engine.constants();
    let typeset = |src: &str, style: Style| {
        engine
            .typeset(src, style)
            .map_err(|e| OracleError::Tex(format!("{src:?}: {e}")))
    };
    let glyph_y = |layout: &fmd_math::Layout, ch: char, src: &str| {
        layout
            .glyphs
            .iter()
            .find(|g| g.ch == ch)
            .map(|g| g.y)
            .ok_or_else(|| OracleError::Tex(format!("{src:?}: no {ch:?} glyph")))
    };

    let display_scripts = typeset("x^2", Style::Display)?;
    let text_scripts = typeset("x^2", Style::Text)?;
    let cramped = typeset(r"\sqrt{x^2}", Style::Display)?;
    let lone_sub = typeset("x_i", Style::Display)?;
    let both = typeset("x_i^2", Style::Display)?;
    let radicand = typeset("x", Style::Display)?;
    let radical = typeset(r"\sqrt{x}", Style::Display)?;

    let rule = radical
        .rules
        .first()
        .ok_or_else(|| OracleError::Tex(r"\sqrt{x}: no overbar rule".to_string()))?;
    let psi = c.rule_thickness + 0.25 * c.x_height;

    Ok(TexAppendixG {
        display_superscript_shift: (glyph_y(&display_scripts, '2', "x^2")? - c.sup1).abs(),
        text_superscript_shift: (glyph_y(&text_scripts, '2', "x^2")? - c.sup2).abs(),
        cramped_superscript_shift: (glyph_y(&cramped, '2', r"\sqrt{x^2}")? - c.sup3).abs(),
        lone_subscript_shift: (glyph_y(&lone_sub, 'i', "x_i")? + c.sub1).abs(),
        script_separation_over_4theta: (glyph_y(&both, '2', "x_i^2")?
            - glyph_y(&both, 'i', "x_i^2")?)
            - 4.0 * c.rule_thickness,
        radical_rule_thickness: (rule.height - c.rule_thickness).abs(),
        radical_clearance_over_psi: (rule.y - radicand.height) - psi,
    })
}

// =====================================================================
// 2. Metamorphic laws — stateless resampling, subdivision invariance
// =====================================================================

/// The stateless-resampling law: clone `path`, subdivide every curve into
/// `inserts + 1` sub-curves ([`QuadPath::insert_n_curves`]), then at each
/// arc-length fraction in `alphas` evaluate the **resampled** path and
/// measure how far that point lies off the **original** curve (minimum
/// distance to any of the original's quadratics, via
/// [`distance_to_quadratic`]). Returns the worst such distance.
///
/// The law's domain: subdivision of a quadratic at a parameter is exact
/// up to rounding (de Casteljau), so the resampled path traces the same
/// geometric curve and this error is ~1e-12 for order-one geometry. It is
/// *not* claimed for arc-length fractions below the table's inversion
/// accuracy on degenerate (zero-length or cusp) curves — the probes in
/// `alphas` stay interior for that reason.
#[must_use]
pub fn stateless_resampling_max_error(path: &QuadPath, inserts: usize, alphas: &[f64]) -> f64 {
    let mut resampled = path.clone();
    let _ = resampled.insert_n_curves(inserts);
    let table = ArcLengthTable::for_path(&resampled);
    let original_curves: Vec<[Vec3; 3]> = path.bezier_tuples().collect();
    let mut worst = 0.0f64;
    for &alpha in alphas {
        let Some((curve, t)) = table.curve_and_t_at(&resampled, alpha) else {
            continue;
        };
        let Some(point) = resampled.nth_curve_point(curve, t) else {
            continue;
        };
        let distance = original_curves
            .iter()
            .map(|[a0, h, a1]| distance_to_quadratic(*a0, *h, *a1, point))
            .fold(f64::INFINITY, f64::min);
        worst = worst.max(distance);
    }
    worst
}

/// The subdivision-invariance law for booleans: `|area(op(A, B)) −
/// area(op(A′, B))|` where `A′` is `A` resampled by
/// [`QuadPath::insert_n_curves`].
///
/// The valid domain is **area agreement within flatten-induced drift**:
/// the certified boolean flattens curves to `options.tolerance` before
/// clipping, and resampling moves the flattening's segment boundaries, so
/// two flattenings of the same curve may differ by O(perimeter ×
/// tolerance) in area. Bit-level output equality is *not* a valid law
/// here — the arrangement legitimately differs at its own rounding scale.
/// On the probe scene (unit-circle subject, polygonal clip, scene
/// tolerance) the measured drift is exactly 0.0 for union, intersection,
/// and difference: the deterministic flatten reproduces the same chords
/// under uniform subdivision. The test pins a small bound rather than
/// exact zero so the law does not overclaim beyond its probe.
///
/// # Errors
/// [`OracleError::Boolean`] if an evaluation refuses its inputs.
pub fn boolean_subdivision_area_error(
    a: &QuadPath,
    b: &QuadPath,
    operation: BooleanOperation,
    inserts: usize,
    options: BooleanOptions,
) -> Result<f64, OracleError> {
    let mut resampled = a.clone();
    let _ = resampled.insert_n_curves(inserts);
    let base = boolean_area(a, b, operation, options)?;
    let subdivided = boolean_area(&resampled, b, operation, options)?;
    Ok((base - subdivided).abs())
}

// =====================================================================
// 3. Structural fixtures against the Reference
// =====================================================================

/// One MANIFEST.tsv row.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ManifestRow {
    /// Declared numpy descr (e.g. `<f8`).
    pub dtype: String,
    /// Declared shape, `x`-joined (e.g. `17x3`).
    pub shape: String,
    /// Declared sha256 of the file bytes, lowercase hex.
    pub sha256: String,
    /// Generator expression that produced the fixture.
    pub formula: String,
}

/// The canonical `fixtures/npy` corpus. Loading binds the exact four-line
/// provenance prelude and generator-defined row order; every fixture read
/// then checks its sha256 before decoding, so drift is a named failure rather
/// than a silent tolerance miss.
#[derive(Clone, Debug)]
pub struct FixtureCorpus {
    root: PathBuf,
    manifest: BTreeMap<String, ManifestRow>,
}

const FIXTURE_MANIFEST_HEADER: &str = "# fmn npy fixture manifest v1";
const FIXTURE_MANIFEST_REFERENCE: &str =
    "# reference: 3b1b/manim @ 6199a00d4c1b1127ebe45cb629c3f22538b10e13";
const FIXTURE_MANIFEST_GENERATOR: &str = "# generator: scripts/gen_npy_fixtures.py (numpy 2.2.4)";
const FIXTURE_MANIFEST_COLUMNS: &str = "# columns: file\tdtype\tshape\tsha256\tformula";
const MAX_FIXTURE_MANIFEST_BYTES: u64 = 1024 * 1024;
const MAX_FIXTURE_MANIFEST_LINE_BYTES: usize = 512;
const MAX_FIXTURE_NAME_BYTES: usize = 128;
const MAX_FIXTURE_DTYPE_BYTES: usize = 8;
const MAX_FIXTURE_SHAPE_BYTES: usize = 64;
const MAX_FIXTURE_HASH_BYTES: usize = 64;
const MAX_FIXTURE_FORMULA_BYTES: usize = 256;
const MAX_NPY_FIXTURE_BYTES: u64 = 16 * 1024 * 1024;

#[derive(Clone, Copy)]
struct FixtureManifestSpec {
    name: &'static str,
    dtype: &'static str,
    shape: &'static str,
    formula: &'static str,
}

const FIXTURE_MANIFEST_SPECS: [FixtureManifestSpec; 9] = [
    FixtureManifestSpec {
        name: "arc_quarter_n4.npy",
        dtype: "<f8",
        shape: "9x3",
        formula: "quadratic_bezier_points_for_arc(TAU/4, n_components=4)",
    },
    FixtureManifestSpec {
        name: "arc_full_n8.npy",
        dtype: "<f8",
        shape: "17x3",
        formula: "quadratic_bezier_points_for_arc(TAU, n_components=8)",
    },
    FixtureManifestSpec {
        name: "arc_neg_third_n2.npy",
        dtype: "<f8",
        shape: "5x3",
        formula: "quadratic_bezier_points_for_arc(-TAU/3, n_components=2)",
    },
    FixtureManifestSpec {
        name: "arc_half_n8.npy",
        dtype: "<f8",
        shape: "17x3",
        formula: "quadratic_bezier_points_for_arc(TAU/2, n_components=8)",
    },
    FixtureManifestSpec {
        name: "partial_quad.npy",
        dtype: "<f8",
        shape: "3x3",
        formula: "partial_quadratic_bezier_points(PARTIAL_QUAD, 0.25, 0.75)",
    },
    FixtureManifestSpec {
        name: "partial_quad_first_half.npy",
        dtype: "<f8",
        shape: "3x3",
        formula: "partial_quadratic_bezier_points(PARTIAL_QUAD, 0.0, 0.5)",
    },
    FixtureManifestSpec {
        name: "partial_quad_second_half.npy",
        dtype: "<f8",
        shape: "3x3",
        formula: "partial_quadratic_bezier_points(PARTIAL_QUAD, 0.5, 1.0)",
    },
    FixtureManifestSpec {
        name: "quad_eval.npy",
        dtype: "<f8",
        shape: "9x3",
        formula: "bezier(PARTIAL_QUAD)(t) for t in {0, 1/8, ..., 1}",
    },
    FixtureManifestSpec {
        name: "integer_interpolate.npy",
        dtype: "<f8",
        shape: "5x2",
        formula: "integer_interpolate(0, 10, a) for a in {0.05, 0.25, 0.5, 0.75, 0.95}",
    },
];

fn read_bounded_artifact(path: &Path, max_bytes: u64, kind: &str) -> Result<Vec<u8>, String> {
    let metadata = std::fs::symlink_metadata(path)
        .map_err(|error| format!("cannot inspect {kind}: {error}"))?;
    if !metadata.file_type().is_file() {
        return Err(format!("{kind} is not a regular file"));
    }
    if metadata.len() > max_bytes {
        return Err(format!(
            "{kind} is {} bytes, exceeding the {max_bytes}-byte limit",
            metadata.len()
        ));
    }
    let read_limit = max_bytes
        .checked_add(1)
        .ok_or_else(|| format!("{kind} byte limit cannot be represented"))?;
    let file = std::fs::File::open(path).map_err(|error| format!("cannot open {kind}: {error}"))?;
    let mut bytes = Vec::new();
    file.take(read_limit)
        .read_to_end(&mut bytes)
        .map_err(|error| format!("cannot read {kind}: {error}"))?;
    if u64::try_from(bytes.len()).unwrap_or(u64::MAX) > max_bytes {
        return Err(format!(
            "{kind} grew beyond the {max_bytes}-byte limit while being read"
        ));
    }
    Ok(bytes)
}

fn split_fixture_manifest_row(line: &str) -> Option<[&str; 5]> {
    let mut fields = line.split('\t');
    let exact = [
        fields.next()?,
        fields.next()?,
        fields.next()?,
        fields.next()?,
        fields.next()?,
    ];
    fields.next().is_none().then_some(exact)
}

fn canonical_fixture_name(name: &str) -> bool {
    let Some(stem) = name.strip_suffix(".npy") else {
        return false;
    };
    !stem.is_empty()
        && stem
            .bytes()
            .all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit() || byte == b'_')
}

fn canonical_decimal(value: &str) -> bool {
    !value.is_empty()
        && (value.len() == 1 || !value.starts_with('0'))
        && value.bytes().all(|byte| byte.is_ascii_digit())
        && value.parse::<usize>().is_ok_and(|parsed| parsed > 0)
}

fn canonical_fixture_shape(shape: &str) -> bool {
    let mut dimensions = shape.split('x');
    let Some(rows) = dimensions.next() else {
        return false;
    };
    let Some(width) = dimensions.next() else {
        return false;
    };
    dimensions.next().is_none()
        && canonical_decimal(rows)
        && canonical_decimal(width)
        && matches!(width, "2" | "3")
}

fn lowercase_sha256(digest: &str) -> bool {
    digest.len() == MAX_FIXTURE_HASH_BYTES
        && digest
            .bytes()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
}

fn parse_fixture_manifest(text: &str) -> Result<BTreeMap<String, ManifestRow>, String> {
    if u64::try_from(text.len()).unwrap_or(u64::MAX) > MAX_FIXTURE_MANIFEST_BYTES {
        return Err(format!(
            "MANIFEST.tsv exceeds the {MAX_FIXTURE_MANIFEST_BYTES}-byte limit"
        ));
    }
    let Some(body) = text.strip_suffix('\n') else {
        return Err("MANIFEST.tsv must end with exactly one line feed".to_string());
    };
    if body.contains('\r') {
        return Err("MANIFEST.tsv must use line-feed separators, not carriage returns".to_string());
    }

    let prelude = [
        FIXTURE_MANIFEST_HEADER,
        FIXTURE_MANIFEST_REFERENCE,
        FIXTURE_MANIFEST_GENERATOR,
        FIXTURE_MANIFEST_COLUMNS,
    ];
    let mut lines = body.split('\n').enumerate();
    for (expected_index, expected) in prelude.into_iter().enumerate() {
        let line_number = expected_index + 1;
        let Some((_, actual)) = lines.next() else {
            return Err(format!(
                "MANIFEST.tsv line {line_number} must be {expected:?}"
            ));
        };
        if actual.len() > MAX_FIXTURE_MANIFEST_LINE_BYTES {
            return Err(format!(
                "MANIFEST.tsv line {line_number} exceeds the {MAX_FIXTURE_MANIFEST_LINE_BYTES}-byte line limit"
            ));
        }
        if actual != expected {
            return Err(format!(
                "MANIFEST.tsv line {line_number} must be {expected:?}"
            ));
        }
    }

    let mut manifest = BTreeMap::new();
    for (index, line) in lines {
        let line_number = index + 1;
        let row_index = manifest.len();
        if row_index == FIXTURE_MANIFEST_SPECS.len() {
            return Err(format!(
                "MANIFEST.tsv line {line_number} exceeds the {}-row fixture census",
                FIXTURE_MANIFEST_SPECS.len()
            ));
        }
        if line.len() > MAX_FIXTURE_MANIFEST_LINE_BYTES {
            return Err(format!(
                "MANIFEST.tsv line {line_number} exceeds the {MAX_FIXTURE_MANIFEST_LINE_BYTES}-byte line limit"
            ));
        }
        let Some([name, dtype, shape, sha256, formula]) = split_fixture_manifest_row(line) else {
            return Err(format!(
                "MANIFEST.tsv line {line_number} must contain exactly 5 tab-separated fields"
            ));
        };
        for (field_name, field, max_bytes) in [
            ("file", name, MAX_FIXTURE_NAME_BYTES),
            ("dtype", dtype, MAX_FIXTURE_DTYPE_BYTES),
            ("shape", shape, MAX_FIXTURE_SHAPE_BYTES),
            ("sha256", sha256, MAX_FIXTURE_HASH_BYTES),
            ("formula", formula, MAX_FIXTURE_FORMULA_BYTES),
        ] {
            if field.is_empty() {
                return Err(format!(
                    "MANIFEST.tsv line {line_number} has an empty {field_name} field"
                ));
            }
            if field.len() > max_bytes {
                return Err(format!(
                    "MANIFEST.tsv line {line_number} {field_name} exceeds its {max_bytes}-byte field limit"
                ));
            }
        }
        if !canonical_fixture_name(name) {
            return Err(format!(
                "MANIFEST.tsv line {line_number} file must be one lowercase single-component .npy name"
            ));
        }
        if !matches!(dtype, "<f8" | "<f4" | "<i8") {
            return Err(format!(
                "MANIFEST.tsv line {line_number} dtype is outside the owned NPY subset"
            ));
        }
        if !canonical_fixture_shape(shape) {
            return Err(format!(
                "MANIFEST.tsv line {line_number} shape must be a canonical positive rowsx2 or rowsx3 declaration"
            ));
        }
        if !lowercase_sha256(sha256) {
            return Err(format!(
                "MANIFEST.tsv line {line_number} sha256 must be exactly 64 lowercase hexadecimal digits"
            ));
        }
        if !formula
            .bytes()
            .all(|byte| byte == b' ' || byte.is_ascii_graphic())
        {
            return Err(format!(
                "MANIFEST.tsv line {line_number} formula must contain printable ASCII only"
            ));
        }
        if manifest.contains_key(name) {
            return Err(format!(
                "MANIFEST.tsv line {line_number} duplicates an earlier fixture name"
            ));
        }

        let expected = FIXTURE_MANIFEST_SPECS[row_index];
        for (field_name, actual, expected_value) in [
            ("file", name, expected.name),
            ("dtype", dtype, expected.dtype),
            ("shape", shape, expected.shape),
            ("formula", formula, expected.formula),
        ] {
            if actual != expected_value {
                return Err(format!(
                    "MANIFEST.tsv line {line_number} {field_name} must be {expected_value:?}"
                ));
            }
        }
        manifest.insert(
            name.to_string(),
            ManifestRow {
                dtype: dtype.to_string(),
                shape: shape.to_string(),
                sha256: sha256.to_string(),
                formula: formula.to_string(),
            },
        );
    }
    if manifest.len() != FIXTURE_MANIFEST_SPECS.len() {
        return Err(format!(
            "MANIFEST.tsv must contain exactly {} generator-defined fixture rows",
            FIXTURE_MANIFEST_SPECS.len()
        ));
    }
    Ok(manifest)
}

fn shape_matches(declared: &str, actual: &[usize]) -> bool {
    let mut dimensions = declared.split('x');
    actual.iter().all(|actual_dimension| {
        dimensions
            .next()
            .and_then(|declared_dimension| declared_dimension.parse::<usize>().ok())
            == Some(*actual_dimension)
    }) && dimensions.next().is_none()
}

impl FixtureCorpus {
    /// Load the manifest rooted at `root` (the directory holding
    /// MANIFEST.tsv).
    ///
    /// # Errors
    /// [`OracleError::Fixture`] if the manifest is unreadable or a row is
    /// malformed.
    pub fn load(root: &Path) -> Result<Self, OracleError> {
        let manifest_path = root.join("MANIFEST.tsv");
        let bytes =
            read_bounded_artifact(&manifest_path, MAX_FIXTURE_MANIFEST_BYTES, "MANIFEST.tsv")
                .map_err(|detail| {
                    OracleError::Fixture(format!(
                        "{detail} (regenerate with scripts/gen_npy_fixtures.py)"
                    ))
                })?;
        let text = String::from_utf8(bytes)
            .map_err(|error| OracleError::Fixture(format!("MANIFEST.tsv is not UTF-8: {error}")))?;
        let manifest = parse_fixture_manifest(&text).map_err(OracleError::Fixture)?;
        Ok(Self {
            root: root.to_path_buf(),
            manifest,
        })
    }

    /// Number of manifest rows.
    #[must_use]
    pub fn len(&self) -> usize {
        self.manifest.len()
    }

    /// Whether the manifest is empty.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.manifest.is_empty()
    }

    /// Fixture names in stable lexical order.
    pub fn names(&self) -> impl Iterator<Item = &str> {
        self.manifest.keys().map(String::as_str)
    }

    /// Read one fixture after binding its bytes to the manifest hash.
    ///
    /// # Errors
    /// [`OracleError::Fixture`] on a missing row, an unreadable or oversized
    /// file, or a hash mismatch.
    pub fn bytes(&self, name: &str) -> Result<Vec<u8>, OracleError> {
        let row = self
            .manifest
            .get(name)
            .ok_or_else(|| OracleError::Fixture(format!("{name} missing from MANIFEST.tsv")))?;
        let bytes =
            read_bounded_artifact(&self.root.join(name), MAX_NPY_FIXTURE_BYTES, "NPY fixture")
                .map_err(|detail| OracleError::Fixture(format!("{name}: {detail}")))?;
        let digest = sha256(&bytes).to_hex();
        // ubs:ignore — fixture-integrity hash comparison, not a secret
        if digest != row.sha256 {
            return Err(OracleError::Fixture(format!(
                "{name}: sha256 {digest} does not match MANIFEST.tsv {} — regenerate or investigate",
                row.sha256
            )));
        }
        Ok(bytes)
    }

    /// Read one fixture, verifying its manifest hash, dtype, and shape.
    ///
    /// # Errors
    /// [`OracleError::Fixture`] on a missing row, an unreadable file, a
    /// hash, dtype, or shape mismatch, or a decode failure.
    pub fn array(&self, name: &str) -> Result<NpyArray, OracleError> {
        let row = self
            .manifest
            .get(name)
            .ok_or_else(|| OracleError::Fixture(format!("{name} missing from MANIFEST.tsv")))?;
        let bytes = self.bytes(name)?;
        let array = read_npy(&bytes).map_err(|e| OracleError::Fixture(format!("{name}: {e}")))?;
        if array.data.dtype().descr() != row.dtype {
            return Err(OracleError::Fixture(format!(
                "{name}: dtype {} does not match manifest {}",
                array.data.dtype().descr(),
                row.dtype
            )));
        }
        if !shape_matches(&row.shape, &array.shape) {
            return Err(OracleError::Fixture(format!(
                "{name}: decoded shape {:?} does not match the manifest declaration",
                array.shape
            )));
        }
        Ok(array)
    }

    /// One fixture as rows of f64 (any width).
    ///
    /// # Errors
    /// [`OracleError::Fixture`] on the [`Self::array`] failures, a non-f64
    /// payload, or a non-2-D shape.
    pub fn rows(&self, name: &str) -> Result<Vec<Vec<f64>>, OracleError> {
        let array = self.array(name)?;
        if array.shape.len() != 2 {
            return Err(OracleError::Fixture(format!(
                "{name}: expected a 2-D array, got {:?}",
                array.shape
            )));
        }
        let width = array.shape[1];
        let NpyData::F64(data) = array.data else {
            return Err(OracleError::Fixture(format!("{name}: not an f64 array")));
        };
        Ok(data.chunks(width).map(<[f64]>::to_vec).collect())
    }

    /// One fixture as 3-D points (`Nx3`).
    ///
    /// # Errors
    /// [`OracleError::Fixture`] on the [`Self::rows`] failures or a width
    /// other than 3.
    pub fn points(&self, name: &str) -> Result<Vec<Vec3>, OracleError> {
        let rows = self.rows(name)?;
        if rows.first().is_some_and(|r| r.len() != 3) {
            return Err(OracleError::Fixture(format!("{name}: not an Nx3 array")));
        }
        Ok(rows.into_iter().map(|r| [r[0], r[1], r[2]]).collect())
    }
}

/// The asymmetric off-axis quadratic the generator hardcodes as
/// `PARTIAL_QUAD` (`scripts/gen_npy_fixtures.py`); the partial-curve and
/// parameter-evaluation fixture rows are functions of exactly this curve.
pub const REFERENCE_QUAD: [Vec3; 3] = [[-1.0, 0.5, 0.25], [0.75, 2.0, -0.5], [2.0, -1.0, 1.0]];

/// Evaluate the fixture quadratic at parameter `t` — the fmn side of the
/// `quad_eval` row, through the one quadratic evaluator
/// ([`bezier::quadratic_point`]).
#[must_use]
pub fn reference_quad_point(t: f64) -> Vec3 {
    bezier::quadratic_point(REFERENCE_QUAD[0], REFERENCE_QUAD[1], REFERENCE_QUAD[2], t)
}

#[cfg(test)]
mod tests {
    use super::read_bounded_artifact;
    use std::path::PathBuf;

    #[test]
    fn bounded_artifact_reader_checks_exact_size_oversize_and_file_type() {
        let crate_root = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        let manifest = crate_root.join("Cargo.toml");
        let size = std::fs::metadata(&manifest)
            .expect("crate manifest metadata")
            .len();
        assert_eq!(
            u64::try_from(
                read_bounded_artifact(&manifest, size, "test artifact")
                    .unwrap()
                    .len()
            )
            .expect("manifest length fits u64"),
            size,
            "a file at the exact byte limit must be accepted"
        );

        let error = read_bounded_artifact(&manifest, size - 1, "test artifact")
            .expect_err("an oversized file must be refused");
        assert!(error.contains("exceeding"), "wrong oversize error: {error}");

        let error = read_bounded_artifact(&crate_root, size, "test artifact")
            .expect_err("a directory must be refused");
        assert!(
            error.contains("not a regular file"),
            "wrong file-type error: {error}"
        );
    }
}
