//! The typed `fmn` parser contract (§13.6).
//!
//! GENERATED from API_SCHEMA.tsv + API_OVERLAY.tsv by
//! fmn_conformance::schema — regenerate, never hand-edit.
//! Reference pin: 6199a00d4c1b1127ebe45cb629c3f22538b10e13
//!
//! Regenerate:  UPDATE_API_ARTIFACTS=1 cargo test -p fmn-conformance \
//!                  --test api_schema

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CommandScope {
    Global,
    Render,
    Doctor,
    Batch,
    Studio,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FlagAction {
    SetTrue,
    Store,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FlagArity {
    None,
    One,
    Optional,
    Many,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FlagStatus {
    Same,
    Improved,
    Tiered,
    Excluded,
    Unreviewed,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FlagSource {
    Reference,
    Native,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct FlagSpec {
    pub options: &'static [&'static str],
    pub binding: &'static str,
    pub command: CommandScope,
    pub action: FlagAction,
    pub arity: FlagArity,
    pub default: Option<&'static str>,
    pub value_type: Option<&'static str>,
    pub status: FlagStatus,
    pub source: FlagSource,
    pub help: &'static str,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SubcommandSpec {
    pub command: CommandScope,
    pub status: FlagStatus,
    pub help: &'static str,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ExitCodeSpec {
    pub code: u8,
    pub name: &'static str,
    pub meaning: &'static str,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InteractionKind {
    AtMostOne,
    Conflicts,
    RequiresAny,
    Implies,
    Exclusive,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct InteractionSpec {
    pub id: &'static str,
    pub kind: InteractionKind,
    pub operands: &'static [&'static str],
    pub exit_code: Option<&'static str>,
    pub message: &'static str,
}

pub const FLAG_SPECS: &[FlagSpec] = &[
    FlagSpec {
        options: &["--autoreload"],
        binding: "autoreload",
        command: CommandScope::Render,
        action: FlagAction::SetTrue,
        arity: FlagArity::None,
        default: Some("false"),
        value_type: None,
        status: FlagStatus::Tiered,
        source: FlagSource::Reference,
        help: "Automatically reload Python modules to pick up code changes across different files",
    },
    FlagSpec {
        options: &["--clear-cache"],
        binding: "clear_cache",
        command: CommandScope::Global,
        action: FlagAction::SetTrue,
        arity: FlagArity::None,
        default: Some("false"),
        value_type: None,
        status: FlagStatus::Improved,
        source: FlagSource::Reference,
        help: "Erase the cache used for Tex and Text Mobjects",
    },
    FlagSpec {
        options: &["--config_file"],
        binding: "config_file",
        command: CommandScope::Global,
        action: FlagAction::Store,
        arity: FlagArity::One,
        default: None,
        value_type: None,
        status: FlagStatus::Same,
        source: FlagSource::Reference,
        help: "Path to the custom configuration file",
    },
    FlagSpec {
        options: &["--file_name"],
        binding: "file_name",
        command: CommandScope::Render,
        action: FlagAction::Store,
        arity: FlagArity::One,
        default: None,
        value_type: None,
        status: FlagStatus::Same,
        source: FlagSource::Reference,
        help: "Name for the movie or image file",
    },
    FlagSpec {
        options: &["--finder"],
        binding: "finder",
        command: CommandScope::Render,
        action: FlagAction::SetTrue,
        arity: FlagArity::None,
        default: Some("false"),
        value_type: None,
        status: FlagStatus::Improved,
        source: FlagSource::Reference,
        help: "Show the output file in finder",
    },
    FlagSpec {
        options: &["--fps"],
        binding: "fps",
        command: CommandScope::Render,
        action: FlagAction::Store,
        arity: FlagArity::One,
        default: None,
        value_type: Some("int"),
        status: FlagStatus::Same,
        source: FlagSource::Reference,
        help: "Frame rate, as an integer",
    },
    FlagSpec {
        options: &["--hd"],
        binding: "hd",
        command: CommandScope::Render,
        action: FlagAction::SetTrue,
        arity: FlagArity::None,
        default: Some("false"),
        value_type: None,
        status: FlagStatus::Same,
        source: FlagSource::Reference,
        help: "Render at a 1080p",
    },
    FlagSpec {
        options: &["--leave_progress_bars"],
        binding: "leave_progress_bars",
        command: CommandScope::Render,
        action: FlagAction::SetTrue,
        arity: FlagArity::None,
        default: Some("false"),
        value_type: None,
        status: FlagStatus::Same,
        source: FlagSource::Reference,
        help: "Leave progress bars displayed in terminal",
    },
    FlagSpec {
        options: &["--log-level"],
        binding: "log_level",
        command: CommandScope::Global,
        action: FlagAction::Store,
        arity: FlagArity::One,
        default: None,
        value_type: None,
        status: FlagStatus::Same,
        source: FlagSource::Reference,
        help: "Level of messages to Display, can be DEBUG / INFO / WARNING / ERROR / CRITICAL",
    },
    FlagSpec {
        options: &["--pix_fmt"],
        binding: "pix_fmt",
        command: CommandScope::Render,
        action: FlagAction::Store,
        arity: FlagArity::One,
        default: None,
        value_type: None,
        status: FlagStatus::Same,
        source: FlagSource::Reference,
        help: "Pixel format to use for the output of ffmpeg, defaults to `yuv420p`",
    },
    FlagSpec {
        options: &["--prerun"],
        binding: "prerun",
        command: CommandScope::Render,
        action: FlagAction::SetTrue,
        arity: FlagArity::None,
        default: Some("false"),
        value_type: None,
        status: FlagStatus::Improved,
        source: FlagSource::Reference,
        help: "Calculate total framecount, to display in a progress bar, by doing an initial run of the scene which skips animations.",
    },
    FlagSpec {
        options: &["--show_animation_progress"],
        binding: "show_animation_progress",
        command: CommandScope::Render,
        action: FlagAction::SetTrue,
        arity: FlagArity::None,
        default: Some("false"),
        value_type: None,
        status: FlagStatus::Same,
        source: FlagSource::Reference,
        help: "Show progress bar for each animation",
    },
    FlagSpec {
        options: &["--subdivide"],
        binding: "subdivide",
        command: CommandScope::Render,
        action: FlagAction::SetTrue,
        arity: FlagArity::None,
        default: Some("false"),
        value_type: None,
        status: FlagStatus::Same,
        source: FlagSource::Reference,
        help: "Divide the output animation into individual movie files for each animation",
    },
    FlagSpec {
        options: &["--uhd"],
        binding: "uhd",
        command: CommandScope::Render,
        action: FlagAction::SetTrue,
        arity: FlagArity::None,
        default: Some("false"),
        value_type: None,
        status: FlagStatus::Same,
        source: FlagSource::Reference,
        help: "Render at a 4k",
    },
    FlagSpec {
        options: &["--vcodec"],
        binding: "vcodec",
        command: CommandScope::Render,
        action: FlagAction::Store,
        arity: FlagArity::One,
        default: None,
        value_type: None,
        status: FlagStatus::Same,
        source: FlagSource::Reference,
        help: "Video codec to use with ffmpeg",
    },
    FlagSpec {
        options: &["--video_dir"],
        binding: "video_dir",
        command: CommandScope::Render,
        action: FlagAction::Store,
        arity: FlagArity::One,
        default: None,
        value_type: None,
        status: FlagStatus::Same,
        source: FlagSource::Reference,
        help: "Directory to write video",
    },
    FlagSpec {
        options: &["-a", "--write_all"],
        binding: "write_all",
        command: CommandScope::Render,
        action: FlagAction::SetTrue,
        arity: FlagArity::None,
        default: Some("false"),
        value_type: None,
        status: FlagStatus::Same,
        source: FlagSource::Reference,
        help: "Write all the scenes from a file",
    },
    FlagSpec {
        options: &["-c", "--color"],
        binding: "background",
        command: CommandScope::Render,
        action: FlagAction::Store,
        arity: FlagArity::One,
        default: None,
        value_type: None,
        status: FlagStatus::Same,
        source: FlagSource::Reference,
        help: "Background color",
    },
    FlagSpec {
        options: &["-e", "--embed"],
        binding: "embed",
        command: CommandScope::Render,
        action: FlagAction::Store,
        arity: FlagArity::One,
        default: None,
        value_type: None,
        status: FlagStatus::Tiered,
        source: FlagSource::Reference,
        help: "Adds a breakpoint at the inputted file dropping into an interactive iPython session at that point of the code.",
    },
    FlagSpec {
        options: &["-f", "--full_screen"],
        binding: "full_screen",
        command: CommandScope::Render,
        action: FlagAction::SetTrue,
        arity: FlagArity::None,
        default: Some("false"),
        value_type: None,
        status: FlagStatus::Same,
        source: FlagSource::Reference,
        help: "Show window in full screen",
    },
    FlagSpec {
        options: &["-i", "--gif"],
        binding: "gif",
        command: CommandScope::Render,
        action: FlagAction::SetTrue,
        arity: FlagArity::None,
        default: Some("false"),
        value_type: None,
        status: FlagStatus::Same,
        source: FlagSource::Reference,
        help: "Save the video as gif",
    },
    FlagSpec {
        options: &["-l", "--low_quality"],
        binding: "low_quality",
        command: CommandScope::Render,
        action: FlagAction::SetTrue,
        arity: FlagArity::None,
        default: Some("false"),
        value_type: None,
        status: FlagStatus::Same,
        source: FlagSource::Reference,
        help: "Render at 480p",
    },
    FlagSpec {
        options: &["-m", "--medium_quality"],
        binding: "medium_quality",
        command: CommandScope::Render,
        action: FlagAction::SetTrue,
        arity: FlagArity::None,
        default: Some("false"),
        value_type: None,
        status: FlagStatus::Same,
        source: FlagSource::Reference,
        help: "Render at 720p",
    },
    FlagSpec {
        options: &["-n", "--start_at_animation_number"],
        binding: "animation_range",
        command: CommandScope::Render,
        action: FlagAction::Store,
        arity: FlagArity::One,
        default: None,
        value_type: None,
        status: FlagStatus::Improved,
        source: FlagSource::Reference,
        help: "Start rendering not from the first animation, but from another, specified by its index. If you pass in two comma separated values, e.g. \"3,6\", it will end the rendering at the second value",
    },
    FlagSpec {
        options: &["-o", "--open"],
        binding: "open",
        command: CommandScope::Render,
        action: FlagAction::SetTrue,
        arity: FlagArity::None,
        default: Some("false"),
        value_type: None,
        status: FlagStatus::Improved,
        source: FlagSource::Reference,
        help: "Automatically open the saved file once its done",
    },
    FlagSpec {
        options: &["-p", "--presenter_mode"],
        binding: "presenter_mode",
        command: CommandScope::Render,
        action: FlagAction::SetTrue,
        arity: FlagArity::None,
        default: Some("false"),
        value_type: None,
        status: FlagStatus::Same,
        source: FlagSource::Reference,
        help: "Scene will stay paused during wait calls until space bar or right arrow is hit, like a slide show",
    },
    FlagSpec {
        options: &["-q", "--quiet"],
        binding: "quiet",
        command: CommandScope::Global,
        action: FlagAction::SetTrue,
        arity: FlagArity::None,
        default: Some("false"),
        value_type: None,
        status: FlagStatus::Same,
        source: FlagSource::Reference,
        help: "",
    },
    FlagSpec {
        options: &["-r", "--resolution"],
        binding: "resolution",
        command: CommandScope::Render,
        action: FlagAction::Store,
        arity: FlagArity::One,
        default: None,
        value_type: None,
        status: FlagStatus::Improved,
        source: FlagSource::Reference,
        help: "Resolution, passed as \"WxH\", e.g. \"1920x1080\"",
    },
    FlagSpec {
        options: &["-s", "--skip_animations"],
        binding: "skip_animations",
        command: CommandScope::Render,
        action: FlagAction::SetTrue,
        arity: FlagArity::None,
        default: Some("false"),
        value_type: None,
        status: FlagStatus::Same,
        source: FlagSource::Reference,
        help: "Save the last frame",
    },
    FlagSpec {
        options: &["-t", "--transparent"],
        binding: "transparent",
        command: CommandScope::Render,
        action: FlagAction::SetTrue,
        arity: FlagArity::None,
        default: Some("false"),
        value_type: None,
        status: FlagStatus::Improved,
        source: FlagSource::Reference,
        help: "Render to a movie file with an alpha channel",
    },
    FlagSpec {
        options: &["-v", "--version"],
        binding: "version",
        command: CommandScope::Global,
        action: FlagAction::SetTrue,
        arity: FlagArity::None,
        default: Some("false"),
        value_type: None,
        status: FlagStatus::Same,
        source: FlagSource::Reference,
        help: "Display the version of manimgl",
    },
    FlagSpec {
        options: &["-w", "--write_file"],
        binding: "write_file",
        command: CommandScope::Render,
        action: FlagAction::SetTrue,
        arity: FlagArity::None,
        default: Some("false"),
        value_type: None,
        status: FlagStatus::Same,
        source: FlagSource::Reference,
        help: "Render the scene as a movie file",
    },
    FlagSpec {
        options: &["file"],
        binding: "file",
        command: CommandScope::Render,
        action: FlagAction::Store,
        arity: FlagArity::Optional,
        default: None,
        value_type: None,
        status: FlagStatus::Same,
        source: FlagSource::Reference,
        help: "Path to file holding the python code for the scene",
    },
    FlagSpec {
        options: &["scene_names"],
        binding: "scene_names",
        command: CommandScope::Render,
        action: FlagAction::Store,
        arity: FlagArity::Many,
        default: None,
        value_type: None,
        status: FlagStatus::Same,
        source: FlagSource::Reference,
        help: "Name of the Scene class you want to see",
    },
    FlagSpec {
        options: &["-h", "--help"],
        binding: "help",
        command: CommandScope::Global,
        action: FlagAction::SetTrue,
        arity: FlagArity::None,
        default: Some("False"),
        value_type: None,
        status: FlagStatus::Improved,
        source: FlagSource::Native,
        help: "Show command help and exit",
    },
    FlagSpec {
        options: &["--robot"],
        binding: "robot",
        command: CommandScope::Global,
        action: FlagAction::SetTrue,
        arity: FlagArity::None,
        default: Some("False"),
        value_type: None,
        status: FlagStatus::Improved,
        source: FlagSource::Native,
        help: "Emit only schema-versioned NDJSON records",
    },
    FlagSpec {
        options: &["--reproducible"],
        binding: "reproducible",
        command: CommandScope::Global,
        action: FlagAction::SetTrue,
        arity: FlagArity::None,
        default: Some("False"),
        value_type: None,
        status: FlagStatus::Improved,
        source: FlagSource::Native,
        help: "Select certified CPU rendering and canonical certified artifacts",
    },
    FlagSpec {
        options: &["--threads"],
        binding: "threads",
        command: CommandScope::Global,
        action: FlagAction::Store,
        arity: FlagArity::One,
        default: None,
        value_type: Some("usize"),
        status: FlagStatus::Improved,
        source: FlagSource::Native,
        help: "Bound render-team CPU threads",
    },
    FlagSpec {
        options: &["--ffmpeg"],
        binding: "ffmpeg",
        command: CommandScope::Global,
        action: FlagAction::Store,
        arity: FlagArity::One,
        default: None,
        value_type: Some("path"),
        status: FlagStatus::Improved,
        source: FlagSource::Native,
        help: "Absolute path to the optional ffmpeg executable",
    },
    FlagSpec {
        options: &["--cache-dir"],
        binding: "cache_dir",
        command: CommandScope::Global,
        action: FlagAction::Store,
        arity: FlagArity::One,
        default: None,
        value_type: Some("path"),
        status: FlagStatus::Improved,
        source: FlagSource::Native,
        help: "Explicit FrankenManim content-store root",
    },
    FlagSpec {
        options: &["--format"],
        binding: "format",
        command: CommandScope::Render,
        action: FlagAction::Store,
        arity: FlagArity::One,
        default: Some("auto"),
        value_type: Some("output_format"),
        status: FlagStatus::Improved,
        source: FlagSource::Native,
        help: "Select auto, png, png-sequence, gif, y4m, wav, or video output",
    },
    FlagSpec {
        options: &["--math-pack"],
        binding: "math_pack",
        command: CommandScope::Render,
        action: FlagAction::Store,
        arity: FlagArity::One,
        default: Some("default"),
        value_type: Some("pack"),
        status: FlagStatus::Improved,
        source: FlagSource::Native,
        help: "Select an fmd-math preamble pack",
    },
    FlagSpec {
        options: &["--budget-ms"],
        binding: "budget_ms",
        command: CommandScope::Batch,
        action: FlagAction::Store,
        arity: FlagArity::One,
        default: None,
        value_type: Some("u64"),
        status: FlagStatus::Improved,
        source: FlagSource::Native,
        help: "Wall-clock budget for the batch",
    },
    FlagSpec {
        options: &["--max-scenes"],
        binding: "max_scenes",
        command: CommandScope::Batch,
        action: FlagAction::Store,
        arity: FlagArity::One,
        default: None,
        value_type: Some("usize"),
        status: FlagStatus::Improved,
        source: FlagSource::Native,
        help: "Bound simultaneously active scene jobs",
    },
    FlagSpec {
        options: &["--fail-fast"],
        binding: "fail_fast",
        command: CommandScope::Batch,
        action: FlagAction::SetTrue,
        arity: FlagArity::None,
        default: Some("False"),
        value_type: None,
        status: FlagStatus::Improved,
        source: FlagSource::Native,
        help: "Cancel remaining jobs after the first failure",
    },
    FlagSpec {
        options: &["--manifest-dir"],
        binding: "manifest_dir",
        command: CommandScope::Batch,
        action: FlagAction::Store,
        arity: FlagArity::One,
        default: None,
        value_type: Some("path"),
        status: FlagStatus::Improved,
        source: FlagSource::Native,
        help: "Write per-scene manifests under this directory",
    },
    FlagSpec {
        options: &["--require-ffmpeg"],
        binding: "require_ffmpeg",
        command: CommandScope::Doctor,
        action: FlagAction::SetTrue,
        arity: FlagArity::None,
        default: Some("False"),
        value_type: None,
        status: FlagStatus::Improved,
        source: FlagSource::Native,
        help: "Exit with capability status when ffmpeg is unavailable",
    },
    FlagSpec {
        options: &["--bind"],
        binding: "bind",
        command: CommandScope::Studio,
        action: FlagAction::Store,
        arity: FlagArity::One,
        default: Some("127.0.0.1"),
        value_type: Some("ip"),
        status: FlagStatus::Improved,
        source: FlagSource::Native,
        help: "Loopback address for the Studio host",
    },
    FlagSpec {
        options: &["--port"],
        binding: "port",
        command: CommandScope::Studio,
        action: FlagAction::Store,
        arity: FlagArity::One,
        default: Some("0"),
        value_type: Some("u16"),
        status: FlagStatus::Improved,
        source: FlagSource::Native,
        help: "Studio TCP port, with zero selecting an ephemeral port",
    },
    FlagSpec {
        options: &["--no-browser"],
        binding: "no_browser",
        command: CommandScope::Studio,
        action: FlagAction::SetTrue,
        arity: FlagArity::None,
        default: Some("False"),
        value_type: None,
        status: FlagStatus::Improved,
        source: FlagSource::Native,
        help: "Do not launch the host browser",
    },
    FlagSpec {
        options: &["--tui"],
        binding: "tui",
        command: CommandScope::Studio,
        action: FlagAction::SetTrue,
        arity: FlagArity::None,
        default: Some("False"),
        value_type: None,
        status: FlagStatus::Improved,
        source: FlagSource::Native,
        help: "Attach the kitty or sixel terminal client",
    },
    FlagSpec {
        options: &["--checkpoint-frames"],
        binding: "checkpoint_frames",
        command: CommandScope::Studio,
        action: FlagAction::Store,
        arity: FlagArity::One,
        default: Some("120"),
        value_type: Some("u64"),
        status: FlagStatus::Improved,
        source: FlagSource::Native,
        help: "Maximum frames between replay checkpoints",
    },
    FlagSpec {
        options: &["--preview-codec"],
        binding: "preview_codec",
        command: CommandScope::Studio,
        action: FlagAction::Store,
        arity: FlagArity::One,
        default: Some("png"),
        value_type: Some("preview_codec"),
        status: FlagStatus::Improved,
        source: FlagSource::Native,
        help: "Select permanent multipart PNG or optional MJPEG preview",
    },
];

pub const SUBCOMMAND_SPECS: &[SubcommandSpec] = &[
    SubcommandSpec {
        command: CommandScope::Render,
        status: FlagStatus::Same,
        help: "Render one or more selected scenes",
    },
    SubcommandSpec {
        command: CommandScope::Doctor,
        status: FlagStatus::Improved,
        help: "Report capabilities and the derived ExecutionPlan",
    },
    SubcommandSpec {
        command: CommandScope::Batch,
        status: FlagStatus::Improved,
        help: "Render a bounded multi-scene farm under asupersync",
    },
    SubcommandSpec {
        command: CommandScope::Studio,
        status: FlagStatus::Improved,
        help: "Run the isolated-worker live Studio",
    },
];

pub const EXIT_CODE_SPECS: &[ExitCodeSpec] = &[
    ExitCodeSpec {
        code: 0,
        name: "success",
        meaning: "The requested command completed",
    },
    ExitCodeSpec {
        code: 2,
        name: "usage",
        meaning: "Arguments, flag interactions, or selection syntax are invalid",
    },
    ExitCodeSpec {
        code: 3,
        name: "config",
        meaning: "A configuration file or resolved value is invalid",
    },
    ExitCodeSpec {
        code: 4,
        name: "capability",
        meaning: "A required optional capability is unavailable",
    },
    ExitCodeSpec {
        code: 5,
        name: "scene",
        meaning: "Scene discovery, construction, or execution failed",
    },
    ExitCodeSpec {
        code: 6,
        name: "render",
        meaning: "Rasterization, output, or publication failed",
    },
    ExitCodeSpec {
        code: 7,
        name: "cancelled",
        meaning: "The operation was cooperatively cancelled",
    },
    ExitCodeSpec {
        code: 8,
        name: "budget",
        meaning: "A declared time, memory, or concurrency budget was exhausted",
    },
    ExitCodeSpec {
        code: 70,
        name: "internal",
        meaning: "An invariant failed inside FrankenManim",
    },
];

pub const INTERACTION_SPECS: &[InteractionSpec] = &[
    InteractionSpec {
        id: "quality-exclusive",
        kind: InteractionKind::AtMostOne,
        operands: &["low_quality", "medium_quality", "hd", "uhd", "resolution"],
        exit_code: Some("usage"),
        message: "choose at most one quality preset or explicit resolution",
    },
    InteractionSpec {
        id: "open-writes",
        kind: InteractionKind::Implies,
        operands: &["open", "write_file"],
        exit_code: None,
        message: "--open implies durable output",
    },
    InteractionSpec {
        id: "finder-writes",
        kind: InteractionKind::Implies,
        operands: &["finder", "write_file"],
        exit_code: None,
        message: "--finder implies durable output",
    },
    InteractionSpec {
        id: "gif-writes",
        kind: InteractionKind::Implies,
        operands: &["gif", "write_file"],
        exit_code: None,
        message: "--gif implies durable output",
    },
    InteractionSpec {
        id: "transparent-writes",
        kind: InteractionKind::Implies,
        operands: &["transparent", "write_file"],
        exit_code: None,
        message: "--transparent implies durable output",
    },
    InteractionSpec {
        id: "codec-writes",
        kind: InteractionKind::Implies,
        operands: &["vcodec", "write_file"],
        exit_code: None,
        message: "--vcodec implies durable output",
    },
    InteractionSpec {
        id: "pixel-format-writes",
        kind: InteractionKind::Implies,
        operands: &["pix_fmt", "write_file"],
        exit_code: None,
        message: "--pix_fmt implies durable output",
    },
    InteractionSpec {
        id: "subdivide-writes",
        kind: InteractionKind::Implies,
        operands: &["subdivide", "write_file"],
        exit_code: None,
        message: "--subdivide implies durable output",
    },
    InteractionSpec {
        id: "filename-writes",
        kind: InteractionKind::Implies,
        operands: &["file_name", "write_file"],
        exit_code: None,
        message: "--file_name implies durable output",
    },
    InteractionSpec {
        id: "video-directory-writes",
        kind: InteractionKind::Implies,
        operands: &["video_dir", "write_file"],
        exit_code: None,
        message: "--video_dir implies durable output",
    },
    InteractionSpec {
        id: "skip-vs-subdivide",
        kind: InteractionKind::Conflicts,
        operands: &["skip_animations", "subdivide"],
        exit_code: Some("usage"),
        message: "--skip_animations cannot produce per-animation subdivisions",
    },
    InteractionSpec {
        id: "write-all-vs-selection",
        kind: InteractionKind::Conflicts,
        operands: &["write_all", "scene_names"],
        exit_code: Some("usage"),
        message: "--write_all cannot accompany explicit scene names",
    },
    InteractionSpec {
        id: "embed-vs-certified",
        kind: InteractionKind::Conflicts,
        operands: &["embed", "reproducible"],
        exit_code: Some("usage"),
        message: "interactive embed points are outside certified execution",
    },
    InteractionSpec {
        id: "reload-vs-certified",
        kind: InteractionKind::Conflicts,
        operands: &["autoreload", "reproducible"],
        exit_code: Some("usage"),
        message: "a changing source tree is outside one certified input closure",
    },
    InteractionSpec {
        id: "clear-cache-only",
        kind: InteractionKind::Exclusive,
        operands: &["clear_cache"],
        exit_code: Some("usage"),
        message: "--clear-cache is a standalone lifecycle action",
    },
    InteractionSpec {
        id: "version-only",
        kind: InteractionKind::Exclusive,
        operands: &["version"],
        exit_code: Some("usage"),
        message: "--version is a standalone query",
    },
    InteractionSpec {
        id: "help-only",
        kind: InteractionKind::Exclusive,
        operands: &["help"],
        exit_code: Some("usage"),
        message: "--help is a standalone query for the selected command",
    },
];
