//! Structural parity for the geometry lineage (fm-oab, §12.1, §16.4).
//!
//! `fixtures/geometry.txt` is generated by
//! `scripts/gen_geometry_fixtures.py`, which transcribes the pinned
//! Reference's constructor formulas into NumPy and records the point
//! arrays they produce. Each case here rebuilds the same shape through
//! fmn-library and compares point for point.
//!
//! Tolerance is the plan's loose f32 bar (§16.4): the fixtures are f64
//! from NumPy, we compute in f64 too, but the two arrive at the same
//! points by different association (a rotation matrix applied one way
//! versus another), so `1e-9` is the honest bar for a coordinate of order
//! one — not bit equality, which would only be asserting that two
//! programs multiply in the same order.
//!
//! Where our rule differs on purpose the fixture says so: every arc case
//! carries both component counts, and the density assertion is that ours
//! is the documented BN-09 value **and** never coarser than the
//! Reference's.

use fmn_core::types::Vec3;
use fmn_library::arc::{Arc, Circle, Dot, Ellipse};
use fmn_library::line::{Elbow, Line};
use fmn_library::poly::{CubicBezier, Polygon, Rectangle, RegularPolygon};
use fmn_library::vmobject::VMobject;
use std::collections::HashMap;

const TOL: f64 = 1e-9;

struct Case {
    name: String,
    kind: String,
    params: HashMap<String, Vec<f64>>,
    note: Option<String>,
    points: Vec<Vec3>,
}

impl Case {
    fn scalar(&self, key: &str) -> f64 {
        self.params
            .get(key)
            .unwrap_or_else(|| panic!("{}: no `{key}`", self.name))[0]
    }

    fn opt(&self, key: &str) -> Option<f64> {
        self.params.get(key).map(|v| v[0])
    }

    fn point(&self, key: &str) -> Vec3 {
        let v = self
            .params
            .get(key)
            .unwrap_or_else(|| panic!("{}: no `{key}`", self.name));
        [v[0], v[1], v[2]]
    }

    fn point_list(&self, key: &str) -> Vec<Vec3> {
        let v = self
            .params
            .get(key)
            .unwrap_or_else(|| panic!("{}: no `{key}`", self.name));
        v.as_chunks::<3>()
            .0
            .iter()
            .map(|c| [c[0], c[1], c[2]])
            .collect()
    }
}

fn load() -> Vec<Case> {
    let path = format!("{}/fixtures/geometry.txt", env!("CARGO_MANIFEST_DIR"));
    let content = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("reading {path}: {e}"));
    let mut cases = Vec::new();
    let mut current: Option<Case> = None;
    let mut want_points = 0usize;

    for line in content.lines() {
        if line.starts_with('#') || line.is_empty() {
            continue;
        }
        if let Some(name) = line.strip_prefix("case ") {
            current = Some(Case {
                name: name.to_string(),
                kind: String::new(),
                params: HashMap::new(),
                note: None,
                points: Vec::new(),
            });
            want_points = 0;
            continue;
        }
        let case = current.as_mut().expect("field outside case");
        if let Some(kind) = line.strip_prefix("kind ") {
            case.kind = kind.to_string();
        } else if let Some(rest) = line.strip_prefix("p ") {
            let (key, values) = rest.split_once(' ').expect("param needs a value");
            let parsed: Vec<f64> = values
                .split('\t')
                .map(|t| t.trim().parse().expect("numeric param"))
                .collect();
            case.params.insert(key.to_string(), parsed);
        } else if let Some(note) = line.strip_prefix("note ") {
            case.note = Some(note.to_string());
        } else if let Some(count) = line.strip_prefix("points ") {
            want_points = count.parse().expect("point count");
        } else if line == "end" {
            let case = current.take().expect("end outside case");
            assert_eq!(case.points.len(), want_points, "{}: point count", case.name);
            cases.push(case);
        } else {
            let row: Vec<f64> = line
                .split('\t')
                .map(|t| t.parse().expect("numeric point"))
                .collect();
            case.points.push([row[0], row[1], row[2]]);
        }
    }
    assert!(!cases.is_empty(), "no cases parsed");
    cases
}

#[track_caller]
fn assert_points(actual: &[Vec3], expected: &[Vec3], what: &str) {
    assert_eq!(
        actual.len(),
        expected.len(),
        "{what}: point count {} vs expected {}",
        actual.len(),
        expected.len()
    );
    for (i, (a, e)) in actual.iter().zip(expected).enumerate() {
        for k in 0..3 {
            assert!(
                (a[k] - e[k]).abs() < TOL,
                "{what}: point {i} component {k}: {a:?} vs expected {e:?}"
            );
        }
    }
}

fn build(case: &Case) -> VMobject {
    match case.kind.as_str() {
        "arc" => {
            let mut arc = Arc::new()
                .start_angle(case.scalar("start_angle"))
                .angle(case.scalar("angle"))
                .radius(case.scalar("radius"))
                .arc_center(case.point("center"));
            // The fixture records the count our rule chooses; passing it
            // explicitly would make the density assertion vacuous, so the
            // build stays on the default and the count is checked
            // separately below.
            if let Some(explicit) = case.opt("explicit_n_components") {
                arc = arc.n_components(explicit as usize);
            }
            arc.build()
        }
        "circle" => Circle::new()
            .radius(case.scalar("radius"))
            .arc_center(case.point("center"))
            .build(),
        "dot" => Dot::new()
            .radius(case.scalar("radius"))
            .point(case.point("center"))
            .build(),
        "ellipse" => Ellipse::new()
            .width(case.scalar("width"))
            .height(case.scalar("height"))
            .build(),
        "polygon" => Polygon::new(case.point_list("vertices")).build(),
        "polyline" => Polygon::polyline(case.point_list("vertices")).build(),
        "regular_polygon" => {
            let mut poly =
                RegularPolygon::new(case.scalar("n") as usize).radius(case.scalar("radius"));
            if let Some(angle) = case.opt("start_angle") {
                poly = poly.start_angle(angle);
            }
            poly.build()
        }
        "rectangle" => Rectangle::new()
            .width(case.scalar("width"))
            .height(case.scalar("height"))
            .build(),
        "square" => Rectangle::square(case.scalar("side_length")).build(),
        "line" => Line::new(case.point("start"), case.point("end"))
            .buff(case.scalar("buff"))
            .build(),
        "elbow" => Elbow::new()
            .width(case.scalar("width"))
            .angle(case.scalar("angle"))
            .build(),
        "cubic" => CubicBezier::new(
            case.point("a0"),
            case.point("h0"),
            case.point("h1"),
            case.point("a1"),
        )
        .build(),
        other => panic!("{}: unhandled kind `{other}`", case.name),
    }
}

#[test]
fn constructors_match_the_reference() {
    let cases = load();
    let mut kinds: HashMap<&str, usize> = HashMap::new();
    for case in &cases {
        *kinds.entry(case.kind.as_str()).or_default() += 1;
        let built = build(case);
        match case.note.as_deref() {
            // A case that only pins its endpoints: the interior split is
            // the cubic converter's, and fm-6cf owns that.
            Some("endpoints_only") => {
                let points = built.points();
                assert!(points.len() >= 2, "{}: no points", case.name);
                assert_points(
                    &[points[0], *points.last().expect("non-empty")],
                    &case.points,
                    &case.name,
                );
            }
            _ => assert_points(built.points(), &case.points, &case.name),
        }
    }

    for kind in [
        "arc",
        "circle",
        "dot",
        "ellipse",
        "polygon",
        "regular_polygon",
        "rectangle",
        "line",
        "elbow",
    ] {
        assert!(kinds.contains_key(kind), "fixture lost its `{kind}` cases");
    }
}

#[test]
fn the_arc_density_rule_is_ours_and_never_coarser() {
    let cases = load();
    let mut checked = 0;
    for case in cases.iter().filter(|c| c.kind == "arc") {
        let arc = Arc::new().angle(case.scalar("angle"));
        let ours = case.scalar("n_components") as usize;
        let theirs = case.scalar("reference_n_components") as usize;
        assert_eq!(
            arc.component_count(),
            ours,
            "{}: BN-09 component count",
            case.name
        );
        assert!(
            ours >= theirs,
            "{}: ours ({ours}) is coarser than the Reference's ({theirs})",
            case.name
        );
        checked += 1;
    }
    assert!(checked >= 6, "only {checked} arc cases");
}

#[test]
fn every_built_path_keeps_the_shared_anchor_invariant() {
    // The layout is API surface (§7.1): user code indexes these points,
    // and alignment reads them as QuadPaths. A constructor that produced
    // an even-length run would be a latent panic everywhere downstream.
    for case in load() {
        let built = build(&case);
        let n = built.points().len();
        assert!(
            n == 0 || n % 2 == 1,
            "{}: point run of length {n} is not shared-anchor",
            case.name
        );
        built
            .path()
            .unwrap_or_else(|e| panic!("{}: {e}", case.name));
    }
}
