//! The governed-closure CI gate (D1, fm-g2c): the real workspace lock
//! must audit clean against the committed allowlist, SUITE.lock must
//! parse and agree with the pinned toolchain, and an injected unlisted
//! package must be caught (the negative test the bead demands).

use fmn_conformance::closure::{
    AllowRow, LockedPackage, Violation, audit, audit_with_aux, parse_allowlist, parse_cargo_lock,
};

const LOCK_PREAMBLE: &str = "# This file is automatically @generated by Cargo.\n\
# It is not intended for manual editing.\n\
version = 4\n\n";

fn repo_file(name: &str) -> String {
    let path = format!("{}/../../{name}", env!("CARGO_MANIFEST_DIR"));
    // The panic!/unreachable! macros are off-limits repo-wide (UBS); a
    // missing governed file must still fail the test loudly, with context.
    std::fs::read_to_string(&path)
        .unwrap_or_else(|e| std::panic::panic_any(format!("reading {path}: {e}")))
}

fn lock_document(package_blocks: &str) -> String {
    let mut document = String::from(LOCK_PREAMBLE);
    document.push_str(package_blocks);
    if !document.ends_with('\n') {
        document.push('\n');
    }
    document
}

fn must_parse_lock(text: &str) -> Vec<LockedPackage> {
    parse_cargo_lock(text)
        .unwrap_or_else(|error| std::panic::panic_any(format!("valid Cargo.lock: {error}")))
}

fn must_parse_allowlist(text: &str) -> Vec<AllowRow> {
    parse_allowlist(text).unwrap_or_else(|error| {
        std::panic::panic_any(format!("valid SUITE_ALLOWLIST.tsv: {error}"))
    })
}

/// Committed lockfiles of governed NON-member crates (ADR-0003: the fuzz
/// harness, non-member spikes). Their packages carry class=dev/fuzz rows;
/// the audit walks each lock that exists.
const AUX_LOCKS: &[&str] = &[
    "spikes/g0-5-python-ext/Cargo.lock",
    "spikes/g0-8-accelerator/Cargo.lock",
    "fuzz/Cargo.lock",
    // W5 wasm tier 1 (fm-l97): the headless smoke probe's independent lock.
    // Its universe is a subset of the governed closure; the row set above
    // admits it exactly like the spike locks.
    "wasm-smoke/Cargo.lock",
];

#[test]
fn workspace_closure_is_exactly_the_governed_universe() {
    let lock = must_parse_lock(&repo_file("Cargo.lock"));
    assert!(
        lock.len() >= 20,
        "lock parser found only {} packages — parser or lock broken",
        lock.len()
    );
    let allowlist = must_parse_allowlist(&repo_file("SUITE_ALLOWLIST.tsv"));
    let aux: Vec<_> = AUX_LOCKS
        .iter()
        .map(|name| {
            let text = repo_file(name);
            must_parse_lock(&text)
        })
        .collect();
    assert_eq!(aux.len(), AUX_LOCKS.len(), "every governed lock must parse");
    let violations = audit_with_aux(&lock, &aux, &allowlist);
    assert!(
        violations.is_empty(),
        "governed-closure violations:\n{}",
        violations
            .iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join("\n")
    );
}

#[test]
fn cargo_lock_parser_rejects_malformed_or_ambiguous_records() {
    let cases = [
        lock_document("[[package]]\nname = \"missing-version\"\n"),
        lock_document("[[package]]\nname = \"repeated\"\nname = \"again\"\nversion = \"1.0.0\"\n"),
        lock_document("[[package]]\nname = \"unknown\"\nversion = \"1.0.0\"\nmagic = \"hidden\"\n"),
        lock_document(
            "[[package]]\nname = \"unterminated\"\nversion = \"1.0.0\"\ndependencies = [\n \"dep\",\n",
        ),
        lock_document(
            "[[package]]\nname = \"duplicate\"\nversion = \"1.0.0\"\n\n\
             [[package]]\nname = \"duplicate\"\nversion = \"1.0.0\"\n",
        ),
    ];
    for case in cases {
        assert!(
            parse_cargo_lock(&case).is_err(),
            "malformed lockfile was accepted: {case:?}"
        );
    }
}

#[test]
fn allowlist_parser_rejects_malformed_or_conflicting_rows() {
    const ROW: &str = "demo\t1.0.0\tcrates-io\taaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\t-\tMIT\tno\tno\tno\tno\tforbid\truntime\treason\tfm\tpolicy\n";
    let cases = [
        "demo\t1.0.0\tcrates-io\t-\t-\tMIT\tno\tno\tno\tno\tforbid\truntime\treason\tfm\n".to_owned(),
        "demo\t1.0.0\tcrates-io\t-\t-\tMIT\tno\tno\tno\tno\tforbid\truntime\treason\tfm\tpolicy\textra\n".to_owned(),
        "demo \t1.0.0\tcrates-io\t-\t-\tMIT\tno\tno\tno\tno\tforbid\truntime\treason\tfm\tpolicy\n".to_owned(),
        "demo\t1.0.0\tcrates-io\tshort\t-\tMIT\tno\tno\tno\tno\tforbid\truntime\treason\tfm\tpolicy\n".to_owned(),
        "demo\t1.0.0\tcrates-io\tTBD\t-\tMIT\tno\tno\tno\tno\tforbid\truntime\treason\tfm\tpolicy\n".to_owned(),
        format!("{ROW}{ROW}"),
        format!(
            "{ROW}demo\t1.0.0\tcrates-io\tbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\t-\tMIT\tno\tno\tno\tno\tforbid\tdev\treason\tfm\tpolicy\n"
        ),
    ];
    for case in cases {
        assert!(
            parse_allowlist(&case).is_err(),
            "malformed allowlist was accepted: {case:?}"
        );
    }
}

#[test]
fn allowlist_parser_preserves_consistent_multi_context_rows() {
    let rows = must_parse_allowlist(
        "wasm-bindgen\t0.2.126\tcrates-io\taaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\tdefault\tMIT/Apache-2.0\tno\tyes\tno\tno\texpansion\truntime\twasm surface\tfm\tdeliberate\n\
         wasm-bindgen\t0.2.126\tcrates-io\taaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\tdefault,std\tMIT OR Apache-2.0\tyes\tno\tno\tno\texpansion\tdev\tscheduler harness\tfm\twith-pin\n",
    );
    assert_eq!(rows.len(), 2);
    assert_eq!(rows[0].checksum, rows[1].checksum);
    assert_ne!(rows[0].class, rows[1].class);
}

#[test]
fn governed_parsers_enforce_canonical_encoding_and_line_bounds() {
    let mut no_final_newline =
        lock_document("[[package]]\nname = \"no-newline\"\nversion = \"1.0.0\"\n");
    assert_eq!(no_final_newline.pop(), Some('\n'));
    assert!(parse_cargo_lock(&no_final_newline).is_err());

    let crlf =
        lock_document("[[package]]\nname = \"crlf\"\nversion = \"1.0.0\"\n").replace('\n', "\r\n");
    assert!(parse_cargo_lock(&crlf).is_err());

    let oversized_line = format!("#{}\n", "x".repeat(16 * 1024 + 1));
    assert!(parse_allowlist(&oversized_line).is_err());
}

#[test]
fn injected_unlisted_package_is_caught() {
    // The negative test: a package smuggled into the lock must fail loud.
    let mut lock_text = repo_file("Cargo.lock");
    lock_text.push_str(
        "\n[[package]]\nname = \"smuggled-dep\"\nversion = \"1.2.3\"\n\
         source = \"registry+https://github.com/rust-lang/crates.io-index\"\n\
         checksum = \"deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef\"\n",
    );
    let lock = must_parse_lock(&lock_text);
    let allowlist = must_parse_allowlist(&repo_file("SUITE_ALLOWLIST.tsv"));
    let violations = audit(&lock, &allowlist);
    assert!(
        violations.iter().any(|v| matches!(
            v,
            Violation::Unlisted { name, .. } if name == "smuggled-dep"
        )),
        "the smuggled package was not flagged: {violations:?}"
    );
}

#[test]
fn a_listed_package_at_an_unlisted_version_is_still_caught() {
    // ADR-0008 keys rows by (name, version) so independently-resolved spike
    // locks can carry different majors of a shared build-time dependency. The
    // loosening it must NOT introduce: a package sliding to an unreviewed
    // version because some other version of the same name happens to be listed.
    let lock_text = lock_document(
        "[[package]]\nname = \"syn\"\nversion = \"9.9.9\"\n\
         source = \"registry+https://github.com/rust-lang/crates.io-index\"\n\
         checksum = \"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\"\n",
    );
    let lock = must_parse_lock(&lock_text);
    let allowlist = must_parse_allowlist(
        "syn\t2.0.119\tcrates-io\taaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\t-\tMIT\tno\tno\tno\tno\tforbid\tdev\treason\tfm\tw\n",
    );
    let violations = audit(&lock, &allowlist);
    assert!(
        violations
            .iter()
            .any(|v| matches!(v, Violation::Unlisted { name, version } if name == "syn" && version == "9.9.9")),
        "an unreviewed version slipped through: {violations:?}"
    );
}

#[test]
fn two_versions_of_one_package_are_admitted_when_both_are_listed() {
    // The other half of ADR-0008, and the case that actually occurs: the G0-5
    // spike's PyO3 graph pins `syn 2`, the G0-8 spike's Metal graph pins
    // `syn 3`, both are non-shipped, both are reviewed.
    let a_text = lock_document(
        "[[package]]\nname = \"syn\"\nversion = \"2.0.119\"\n\
         source = \"registry+https://github.com/rust-lang/crates.io-index\"\n\
         checksum = \"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\"\n",
    );
    let b_text = lock_document(
        "[[package]]\nname = \"syn\"\nversion = \"3.0.3\"\n\
         source = \"registry+https://github.com/rust-lang/crates.io-index\"\n\
         checksum = \"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\"\n",
    );
    let a = must_parse_lock(&a_text);
    let b = must_parse_lock(&b_text);
    let allowlist = must_parse_allowlist(
        "syn\t2.0.119\tcrates-io\taaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\t-\tMIT\tno\tno\tno\tno\tforbid\tdev\treason\tfm\tw\n\
         syn\t3.0.3\tcrates-io\tbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\t-\tMIT\tno\tno\tno\tno\tforbid\tdev\treason\tfm\tw\n",
    );
    assert!(audit_with_aux(&a, &[b], &allowlist).is_empty());
}

#[test]
fn checksum_drift_is_caught() {
    let lock_text = lock_document(
        "[[package]]\nname = \"pyo3\"\nversion = \"0.23.0\"\n\
         source = \"registry+https://github.com/rust-lang/crates.io-index\"\n\
         checksum = \"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\"\n",
    );
    let lock = must_parse_lock(&lock_text);
    // A consumed row with a pinned checksum that differs must flag.
    let allowlist = must_parse_allowlist(
        "pyo3\t0.23.0\tcrates-io\tbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\tx\tMIT\tyes\tyes\tpython\tno\texpansion\tffi\treason\tfm\tpolicy\n",
    );
    let violations = audit(&lock, &allowlist);
    assert!(
        violations
            .iter()
            .any(|v| matches!(v, Violation::ChecksumMismatch { name, .. } if name == "pyo3")),
        "checksum drift not flagged: {violations:?}"
    );
    // TBD checksums (pending rows) do not flag — consumption fills them.
    let pending = must_parse_allowlist(
        "pyo3\t0.23.0\tcrates-io\tTBD\tx\tMIT\tyes\tyes\tpython\tno\texpansion\tpending\treason\tfm\tpolicy\n",
    );
    assert!(audit(&lock, &pending).is_empty());
}

#[test]
fn source_drift_in_an_auxiliary_lock_is_caught() {
    let admitted_text = lock_document(
        "[[package]]\nname = \"suite-crate\"\nversion = \"1.0.0\"\n\
         source = \"git+https://github.com/example/expected?rev=1111111111111111111111111111111111111111#1111111111111111111111111111111111111111\"\n",
    );
    let drifted_text = lock_document(
        "[[package]]\nname = \"suite-crate\"\nversion = \"1.0.0\"\n\
         source = \"git+https://github.com/example/different?rev=2222222222222222222222222222222222222222#2222222222222222222222222222222222222222\"\n",
    );
    let admitted = must_parse_lock(&admitted_text);
    let drifted = must_parse_lock(&drifted_text);
    let allowlist = must_parse_allowlist(
        "suite-crate\t1.0.0\tgit+expected@SUITE.lock\t-\t-\tMIT\tno\tno\tno\tno\tforbid\tdev\treason\tfm\twith-pin\n",
    );
    let violations = audit_with_aux(&admitted, &[drifted], &allowlist);
    assert!(
        violations
            .iter()
            .any(|violation| matches!(violation, Violation::SourceMismatch { name, .. } if name == "suite-crate")),
        "source drift in a second lock was not flagged: {violations:?}"
    );
}

#[test]
fn stale_consumed_rows_are_caught() {
    let lock_text = lock_document("[[package]]\nname = \"fmn-core\"\nversion = \"0.1.0\"\n");
    let lock = must_parse_lock(&lock_text);
    let allowlist = must_parse_allowlist(
        "fmn-core\t0.1.0\tworkspace\t-\t-\tMIT\tno\tno\tno\tno\tforbid\tworkspace\tsubstrate\tfm\tw\n\
         ghost-crate\t1.0\tcrates-io\tcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc\t-\tMIT\tno\tno\tno\tno\tpending\truntime\tgone\tfm\tw\n",
    );
    let violations = audit(&lock, &allowlist);
    assert!(
        violations
            .iter()
            .any(|v| matches!(v, Violation::StaleRow { name } if name == "ghost-crate")),
        "stale consumed row not flagged: {violations:?}"
    );
}

#[test]
fn git_dependencies_ride_their_suite_lock_pins() {
    // ADR-0004: every foundation crate consumed as a git dependency must
    // resolve to exactly the commit its repo's SUITE.lock row pins — the
    // lock is the single authority, and a drifted rev is a closure
    // violation even if the allowlist row matches.
    let suite_lock = repo_file("SUITE.lock");
    let pin_for = |repo: &str| -> String {
        suite_lock
            .lines()
            .find(|l| l.starts_with(&format!("{repo}\t")))
            .and_then(|l| l.split('\t').nth(1))
            .unwrap_or_else(|| std::panic::panic_any(format!("SUITE.lock must pin {repo}")))
            .to_string()
    };
    let cargo_lock = repo_file("Cargo.lock");
    // (git-dep package name, owning repo in SUITE.lock)
    let git_deps = [
        ("asupersync", "asupersync"),
        ("fmd-font", "franken_markdown"),
        ("fmd-math", "franken_markdown"),
        ("ft-kernel-metal", "frankentorch"),
        ("block", "rust-block"),
        ("fsci-integrate", "frankenscipy"),
        ("fsci-opt", "frankenscipy"),
        ("fsci-runtime", "frankenscipy"),
    ];
    for (pkg, repo) in git_deps {
        let pin = pin_for(repo);
        let mut found = false;
        let mut lines = cargo_lock.lines();
        while let Some(line) = lines.next() {
            if line.trim() == format!("name = \"{pkg}\"") {
                // The package's source line follows within its block.
                for follow in lines.by_ref() {
                    if follow.starts_with("[[package]]") {
                        break;
                    }
                    if let Some(source) = follow.trim().strip_prefix("source = \"") {
                        assert!(
                            source.starts_with("git+"),
                            "{pkg}: expected a git source, got {source}"
                        );
                        let resolved = source
                            .split('#')
                            .nth(1)
                            .map(|s| s.trim_end_matches('"'))
                            .unwrap_or("");
                        assert_eq!(
                            resolved, pin,
                            "{pkg}: Cargo.lock resolves {resolved} but SUITE.lock pins {repo} at {pin} — run the §6 upgrade ritual"
                        );
                        found = true;
                        break;
                    }
                }
            }
        }
        assert!(found, "{pkg} not found in Cargo.lock with a source line");
    }
}

#[test]
fn suite_lock_parses_and_matches_the_pinned_toolchain() {
    let suite_lock = repo_file("SUITE.lock");
    // The rustc pin must equal rust-toolchain.toml's channel — one truth.
    let rustc_line = suite_lock
        .lines()
        .find(|l| l.starts_with("rustc\t"))
        .expect("SUITE.lock must pin rustc");
    let pinned = rustc_line.split('\t').nth(1).expect("rustc pin value");
    let toolchain = repo_file("rust-toolchain.toml");
    assert!(
        toolchain.contains(&format!("channel = \"{pinned}\"")),
        "SUITE.lock rustc pin `{pinned}` disagrees with rust-toolchain.toml"
    );
    // Every [repos] row pins a full 40-hex commit.
    let mut in_repos = false;
    let mut repo_rows = 0;
    for line in suite_lock.lines() {
        if line.starts_with('[') {
            in_repos = line == "[repos]";
            continue;
        }
        if in_repos && !line.starts_with('#') && !line.trim().is_empty() {
            let commit = line.split('\t').nth(1).unwrap_or("");
            assert_eq!(commit.len(), 40, "repo pin not a full commit: {line}");
            assert!(
                commit.chars().all(|c| c.is_ascii_hexdigit()),
                "repo pin not hex: {line}"
            );
            repo_rows += 1;
        }
    }
    assert_eq!(repo_rows, 7, "all seven foundation repos must be pinned");
}
