//! Copy semantics to the Reference's letter (fm-ncq, §8.3): the fixture
//! corpus in `fixtures/copy_semantics.txt` is generated by
//! `scripts/gen_copy_fixtures.py`, which transcribes `mobject.py`'s
//! `copy()` / `generate_target` / `save_state` / `restore` verbatim onto
//! mock objects and records the structural facts. Each case is rebuilt here
//! as a Stage family, the same operation performed, and the same facts
//! asserted of `copy_family_mapped` and the target/saved-state machinery.
//!
//! Arena-specific contracts the Reference has no analogue for (live views,
//! diamond sharing under the ratified family model, snapshot round-trips,
//! typed refusals) are covered by the direct tests at the bottom.

use fmn_mobject::record::RecordSchema;
use fmn_mobject::{Mob, Mobject, RecordBuffer, Stage, StageError};

// ------------------------------------------------------------ fixture rig

struct Case {
    name: String,
    /// `(parent_index, n_points)` in family (depth-first) order.
    nodes: Vec<(i64, usize)>,
    /// `(attr, owner_index, target_index)` declared aliases.
    aliases: Vec<(String, usize, usize)>,
    /// `(node_index, count)` updater registrations.
    updaters: Vec<(usize, usize)>,
    /// `EXPECT <key> <values…>` facts.
    expects: Vec<(String, Vec<String>)>,
}

fn parse_cases() -> Vec<Case> {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/fixtures/copy_semantics.txt");
    let text = std::fs::read_to_string(path).expect("fixture file present");
    let mut cases = Vec::new();
    let mut current: Option<Case> = None;
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let mut parts = line.split_whitespace();
        let tag = parts.next().expect("nonempty line");
        let rest: Vec<&str> = parts.collect();
        match tag {
            "CASE" => {
                current = Some(Case {
                    name: rest[0].to_string(),
                    nodes: Vec::new(),
                    aliases: Vec::new(),
                    updaters: Vec::new(),
                    expects: Vec::new(),
                });
            }
            "NODE" => {
                let case = current.as_mut().expect("NODE inside CASE");
                let parent: i64 = rest[1].parse().expect("parent index");
                let n_points: usize = rest[2].parse().expect("point count");
                case.nodes.push((parent, n_points));
            }
            "ALIAS" => {
                let case = current.as_mut().expect("ALIAS inside CASE");
                case.aliases.push((
                    rest[0].to_string(),
                    rest[1].parse().expect("owner index"),
                    rest[2].parse().expect("target index"),
                ));
            }
            "UPDATERS" => {
                let case = current.as_mut().expect("UPDATERS inside CASE");
                case.updaters.push((
                    rest[0].parse().expect("node index"),
                    rest[1].parse().expect("updater count"),
                ));
            }
            "EXPECT" => {
                let case = current.as_mut().expect("EXPECT inside CASE");
                case.expects.push((
                    rest[0].to_string(),
                    rest[1..].iter().map(|s| (*s).to_string()).collect(),
                ));
            }
            "END" => cases.push(current.take().expect("END closes CASE")),
            other => panic!("unknown fixture tag {other}"),
        }
    }
    assert!(!cases.is_empty(), "fixture corpus parsed");
    cases
}

/// Rebuild the case's tree; returns the family in fixture (DFS) order.
fn build(stage: &mut Stage, case: &Case) -> Vec<Mob> {
    let mut mobs: Vec<Mob> = Vec::with_capacity(case.nodes.len());
    for &(parent, n_points) in &case.nodes {
        let mob = stage.add(Mobject::from_points(&vec![[0.0; 3]; n_points]));
        if parent >= 0 {
            #[allow(clippy::cast_sign_loss)]
            stage.attach(mobs[parent as usize], mob).expect("tree edge");
        }
        mobs.push(mob);
    }
    for &(index, count) in &case.updaters {
        for _ in 0..count {
            stage
                .add_updater(mobs[index], |_, _| {}, false)
                .expect("live");
        }
    }
    assert_eq!(
        stage.family(mobs[0]),
        mobs,
        "fixture DFS order matches engine family order ({})",
        case.name
    );
    mobs
}

fn fact(v: &[String]) -> bool {
    v.last().expect("fact value") == "1"
}

// -------------------------------------------------- the fixture corpus run

#[test]
fn fixture_corpus_copy_facts() {
    for case in parse_cases() {
        match case.name.as_str() {
            "save_then_generate" | "generate_then_save" | "restore_roundtrip" => continue,
            _ => {}
        }
        let mut stage = Stage::new();
        let mobs = build(&mut stage, &case);
        let external = stage.add(Mobject::from_points(&[[0.0; 3]]));
        // Pre-copy state mirroring the transcription: links set then cleared.
        let map = stage.copy_family_mapped(mobs[0]).expect("copy succeeds");
        let copy_family = stage.family(map.root());

        for (key, values) in &case.expects {
            match key.as_str() {
                "family_size" => {
                    let n: usize = values[0].parse().expect("size");
                    assert_eq!(map.len(), n, "{}: map size", case.name);
                    assert_eq!(copy_family.len(), n, "{}: copy family size", case.name);
                }
                "order_preserved" => {
                    assert!(fact(values), "{}: reference order fact", case.name);
                    for (i, &orig) in mobs.iter().enumerate() {
                        assert_eq!(
                            map.get(orig),
                            Some(copy_family[i]),
                            "{}: family index {i} preserved",
                            case.name
                        );
                    }
                }
                "alias" => {
                    // EXPECT alias <attr> <owner> <old_index> <new_index>:
                    // the binding tier remaps `owner.attr` through the map;
                    // the Reference measured the remapped target's index.
                    let old: usize = values[2].parse().expect("old index");
                    let new: usize = values[3].parse().expect("new index");
                    assert_eq!(
                        map.get(mobs[old]),
                        Some(copy_family[new]),
                        "{}: alias {} remap",
                        case.name,
                        values[0]
                    );
                }
                "updaters_shared" => {
                    let index: usize = values[0].parse().expect("node index");
                    let count: usize = values[1].parse().expect("count");
                    assert!(fact(values), "{}: reference sharing fact", case.name);
                    let orig_ids = stage.updater_ids(mobs[index]);
                    let copy_ids = stage.updater_ids(copy_family[index]);
                    assert_eq!(orig_ids.len(), count, "{}: updater count", case.name);
                    assert_eq!(
                        orig_ids, copy_ids,
                        "{}: updaters shared by reference (ids equal)",
                        case.name
                    );
                }
                "root_parents_cleared" => {
                    assert!(fact(values));
                    assert!(
                        stage.get(map.root()).expect("live").parents().is_empty(),
                        "{}: copy root detached",
                        case.name
                    );
                    assert!(
                        !stage.roots().contains(&map.root()),
                        "{}: copy never rooted",
                        case.name
                    );
                }
                "pointers_cleared" => {
                    assert!(fact(values));
                    for &(_, copied) in map.pairs() {
                        assert_eq!(stage.target(copied), None, "{}", case.name);
                        assert_eq!(stage.saved_state(copied), None, "{}", case.name);
                    }
                }
                "data_independent" => {
                    assert!(fact(values));
                    for &orig in &mobs {
                        let len = stage.get(orig).expect("live").buffer.len();
                        for i in 0..len {
                            stage.get_mut(orig).expect("live").buffer.write(
                                i,
                                "point",
                                &[99.0, 99.0, 99.0],
                            );
                        }
                    }
                    for &(_, copied) in map.pairs() {
                        let buffer = &stage.get(copied).expect("live").buffer;
                        let sum: f32 = buffer
                            .read_column("point")
                            .expect("point column")
                            .iter()
                            .sum();
                        assert_eq!(sum, 0.0, "{}: copy data untouched", case.name);
                    }
                }
                "uniforms_independent" => {
                    assert!(fact(values));
                    for &orig in &mobs {
                        stage
                            .get_mut(orig)
                            .expect("live")
                            .uniforms_mut()
                            .is_fixed_in_frame = 0.75;
                    }
                    for &(_, copied) in map.pairs() {
                        assert_eq!(
                            stage
                                .get(copied)
                                .expect("live")
                                .uniforms()
                                .is_fixed_in_frame,
                            0.0,
                            "{}: copy uniforms untouched",
                            case.name
                        );
                    }
                }
                "external_alias_shared" => {
                    assert!(fact(values));
                    // Engine equivalent: an out-of-family mobject is not in
                    // the map — the binding leaves the alias pointing at the
                    // shared original.
                    assert_eq!(map.get(external), None, "{}", case.name);
                }
                other => panic!("unhandled fact {other} in {}", case.name),
            }
        }
    }
}

#[test]
fn fixture_link_topology_save_then_generate() {
    let case = parse_cases()
        .into_iter()
        .find(|c| c.name == "save_then_generate")
        .expect("case present");
    let mut stage = Stage::new();
    let mobs = build(&mut stage, &case);
    let saved = stage.save_state(mobs[0]).expect("save");
    let target = stage.generate_target(mobs[0]).expect("generate");
    for (key, values) in &case.expects {
        match key.as_str() {
            "target_saved_state_is_saved" => {
                assert!(fact(values));
                assert_eq!(stage.saved_state(target), Some(saved));
            }
            "saved_target_is_none" => {
                assert!(fact(values));
                assert_eq!(stage.target(saved), None);
            }
            "family_size" | "order_preserved" => {}
            other => panic!("unhandled fact {other}"),
        }
    }
    assert_eq!(stage.target(mobs[0]), Some(target));
    assert_eq!(stage.saved_state(mobs[0]), Some(saved));
}

#[test]
fn fixture_link_topology_generate_then_save() {
    let case = parse_cases()
        .into_iter()
        .find(|c| c.name == "generate_then_save")
        .expect("case present");
    let mut stage = Stage::new();
    let mobs = build(&mut stage, &case);
    let target = stage.generate_target(mobs[0]).expect("generate");
    let saved = stage.save_state(mobs[0]).expect("save");
    for (key, values) in &case.expects {
        match key.as_str() {
            "saved_target_is_target" => {
                assert!(fact(values));
                assert_eq!(stage.target(saved), Some(target));
            }
            "target_saved_state_is_none" => {
                assert!(fact(values));
                assert_eq!(stage.saved_state(target), None);
            }
            "family_size" | "order_preserved" => {}
            other => panic!("unhandled fact {other}"),
        }
    }
}

#[test]
fn fixture_restore_roundtrip() {
    let case = parse_cases()
        .into_iter()
        .find(|c| c.name == "restore_roundtrip")
        .expect("case present");
    let mut stage = Stage::new();
    let mobs = build(&mut stage, &case);
    let (root, child) = (mobs[0], mobs[1]);
    stage
        .get_mut(root)
        .expect("live")
        .buffer
        .write(0, "point", &[1.0, 2.0, 3.0]);
    stage
        .get_mut(child)
        .expect("live")
        .buffer
        .write(1, "point", &[4.0, 5.0, 6.0]);
    stage.save_state(root).expect("save");
    stage
        .get_mut(root)
        .expect("live")
        .buffer
        .write(0, "point", &[9.0, 9.0, 9.0]);
    stage
        .get_mut(child)
        .expect("live")
        .buffer
        .write(1, "point", &[8.0, 8.0, 8.0]);
    stage
        .get_mut(child)
        .expect("live")
        .uniforms_mut()
        .is_fixed_in_frame = 0.5;

    stage.restore_mobject(root).expect("restore");
    assert!(fact(
        &case
            .expects
            .iter()
            .find(|(k, _)| k == "restore_roundtrip")
            .expect("fact")
            .1
    ));
    assert_eq!(
        stage.get(root).expect("live").buffer.read(0, "point"),
        Some(vec![1.0, 2.0, 3.0])
    );
    assert_eq!(
        stage.get(child).expect("live").buffer.read(1, "point"),
        Some(vec![4.0, 5.0, 6.0])
    );
    assert_eq!(
        stage.get(child).expect("live").uniforms().is_fixed_in_frame,
        0.0,
        "become copies uniforms back"
    );

    // Repeated restore keeps working (the saved link survives restore).
    stage
        .get_mut(root)
        .expect("live")
        .buffer
        .write(0, "point", &[5.0, 5.0, 5.0]);
    stage.restore_mobject(root).expect("restore again");
    assert!(fact(
        &case
            .expects
            .iter()
            .find(|(k, _)| k == "restore_repeatable")
            .expect("fact")
            .1
    ));
    assert_eq!(
        stage.get(root).expect("live").buffer.read(0, "point"),
        Some(vec![1.0, 2.0, 3.0])
    );
}

// --------------------------------------- property: copies never alias back

/// No copy ever references an original's family member: every edge of every
/// copied entry stays inside the copied family (fm-ncq's remap-correctness
/// property, over the whole random corpus).
#[test]
fn property_no_copy_references_original_family() {
    for case in parse_cases() {
        if case.nodes.is_empty() {
            continue;
        }
        let mut stage = Stage::new();
        let mobs = build(&mut stage, &case);
        let map = stage.copy_family_mapped(mobs[0]).expect("copy succeeds");
        let copies: Vec<Mob> = map.pairs().iter().map(|&(_, new)| new).collect();
        for &copied in &copies {
            let entry = stage.get(copied).expect("live");
            for edge in entry.submobjects().iter().chain(entry.parents()) {
                assert!(
                    copies.contains(edge),
                    "{}: copy edge stays inside the copied family",
                    case.name
                );
                assert!(
                    !mobs.contains(edge),
                    "{}: copy never references an original member",
                    case.name
                );
            }
        }
        // And the originals gained no edges into the copy.
        for &orig in &mobs {
            let entry = stage.get(orig).expect("live");
            for edge in entry.submobjects().iter().chain(entry.parents()) {
                assert!(
                    !copies.contains(edge),
                    "{}: originals untouched by the copy",
                    case.name
                );
            }
        }
    }
}

// ------------------------------------------------- arena-specific contracts

/// Diamond-shared members follow the ratified family model (G0-1/D-11):
/// copied exactly once, sharing preserved — where the Reference's per-child
/// recursion would duplicate the shared node.
#[test]
fn diamond_sharing_preserved() {
    let mut stage = Stage::new();
    let root = stage.add(Mobject::new());
    let left = stage.add(Mobject::new());
    let right = stage.add(Mobject::new());
    let shared = stage.add(Mobject::from_points(&[[1.0, 0.0, 0.0]]));
    stage.attach(root, left).unwrap();
    stage.attach(root, right).unwrap();
    stage.attach(left, shared).unwrap();
    stage.attach(right, shared).unwrap();

    let map = stage.copy_family_mapped(root).expect("copy");
    assert_eq!(map.len(), 4, "each member copied exactly once");
    let left_copy = map.get(left).unwrap();
    let right_copy = map.get(right).unwrap();
    let shared_copy = map.get(shared).unwrap();
    assert_eq!(stage.get(left_copy).unwrap().submobjects(), &[shared_copy]);
    assert_eq!(stage.get(right_copy).unwrap().submobjects(), &[shared_copy]);
    assert_eq!(
        stage.get(shared_copy).unwrap().parents(),
        &[left_copy, right_copy],
        "diamond sharing preserved in the copy"
    );
}

/// Copies start with zero live views; a live view on the original stays
/// attached to the original's storage and never observes the copy (§8.2/V2).
#[test]
fn views_stay_on_the_original() {
    let mut stage = Stage::new();
    let mob = stage.add(Mobject::from_points(&[[1.0, 2.0, 3.0]]));
    let view = stage.get_mut(mob).unwrap().buffer.export_view(true);
    let copy = stage.copy_family(mob).expect("copy");

    let orig_buffer = &stage.get(mob).unwrap().buffer;
    let copy_buffer = &stage.get(copy).unwrap().buffer;
    assert_eq!(copy_buffer.live_view_count(), 0, "copy starts view-free");
    assert_eq!(orig_buffer.live_view_count(), 1, "original keeps its view");
    assert!(view.is_attached_to(orig_buffer));
    assert!(!view.is_attached_to(copy_buffer));

    // A write through the live view moves the original, never the copy.
    view.write(0, "point", &[7.0, 7.0, 7.0]);
    assert_eq!(
        stage.get(mob).unwrap().buffer.read(0, "point"),
        Some(vec![7.0, 7.0, 7.0])
    );
    assert_eq!(
        stage.get(copy).unwrap().buffer.read(0, "point"),
        Some(vec![1.0, 2.0, 3.0])
    );
}

/// `become_mobject` detaches outstanding views exactly as under resize (V6)
/// and bumps revisions past the old ones, so mirrors and bbox signatures
/// can never confuse the new contents with the old.
#[test]
fn become_detaches_views_and_advances_revisions() {
    let mut stage = Stage::new();
    let a = stage.add(Mobject::from_points(&[[1.0, 0.0, 0.0]]));
    let b = stage.add(Mobject::from_points(&[[2.0, 0.0, 0.0], [3.0, 0.0, 0.0]]));
    let view = stage.get_mut(a).unwrap().buffer.export_view(false);
    let rev_before = stage.get(a).unwrap().buffer.revision();

    stage.become_mobject(a, b, false).expect("become");

    let buffer = &stage.get(a).unwrap().buffer;
    assert_eq!(buffer.len(), 2, "records replaced, length matches source");
    assert_eq!(buffer.read(1, "point"), Some(vec![3.0, 0.0, 0.0]));
    assert!(!view.is_attached_to(buffer), "old view detached (V6)");
    assert!(
        buffer.revision() > rev_before,
        "revisions advance past the old generation"
    );
}

#[test]
fn become_shape_and_schema_refusals() {
    let mut stage = Stage::new();
    // Shape mismatch: 1-node family vs 2-node family.
    let single = stage.add(Mobject::from_points(&[[0.0; 3]]));
    let parent = stage.add(Mobject::new());
    let child = stage.add(Mobject::from_points(&[[0.0; 3]]));
    stage.attach(parent, child).unwrap();
    assert_eq!(
        stage.become_mobject(single, parent, false),
        Err(StageError::FamilyShapeMismatch)
    );

    // Schema mismatch: same shape, different record layout.
    let custom = RecordBuffer::new(RecordSchema::new(&[("weird", 2)], &[], &[]), 1);
    let odd = stage.add(Mobject::new());
    stage.get_mut(odd).unwrap().buffer = custom;
    assert_eq!(
        stage.become_mobject(single, odd, false),
        Err(StageError::SchemaMismatch)
    );

    // Nothing was half-become: the precheck refused before any write.
    assert_eq!(stage.get(single).unwrap().buffer.len(), 1);
}

#[test]
fn become_match_updaters_shares_root_list_only() {
    let mut stage = Stage::new();
    let a = stage.add(Mobject::from_points(&[[0.0; 3]]));
    let a_child = stage.add(Mobject::from_points(&[[0.0; 3]]));
    stage.attach(a, a_child).unwrap();
    let b = stage.add(Mobject::from_points(&[[0.0; 3]]));
    let b_child = stage.add(Mobject::from_points(&[[0.0; 3]]));
    stage.attach(b, b_child).unwrap();
    stage.add_updater(b, |_, _| {}, false).unwrap();
    stage.add_updater(b_child, |_, _| {}, false).unwrap();

    stage.become_mobject(a, b, false).expect("become");
    assert!(
        stage.updater_ids(a).is_empty(),
        "updaters untouched by default"
    );

    stage.become_mobject(a, b, true).expect("become with match");
    assert_eq!(
        stage.updater_ids(a),
        stage.updater_ids(b),
        "match_updaters shares the root's list by reference"
    );
    assert!(
        stage.updater_ids(a_child).is_empty(),
        "match_updaters is root-only, exactly the Reference call"
    );
}

#[test]
fn restore_without_save_is_the_named_error() {
    let mut stage = Stage::new();
    let mob = stage.add(Mobject::from_points(&[[0.0; 3]]));
    assert_eq!(stage.restore_mobject(mob), Err(StageError::NoSavedState));
}

/// Replacing a target unlinks the old one but leaves it alive: explicit
/// delete is the only destructor (the Reference's dropped target survives
/// while user code holds it).
#[test]
fn regenerated_target_leaves_old_target_alive() {
    let mut stage = Stage::new();
    let mob = stage.add(Mobject::from_points(&[[0.0; 3]]));
    let first = stage.generate_target(mob).expect("generate");
    let second = stage.generate_target(mob).expect("regenerate");
    assert_ne!(first, second);
    assert_eq!(stage.target(mob), Some(second));
    assert!(stage.contains(first), "old target stays alive");
}

/// Tracker state copies by value with the entry (a copied ValueTracker
/// carries the value, independently).
#[test]
fn tracker_state_copies_by_value() {
    let mut stage = Stage::new();
    let tracker = stage.add_value_tracker(2.5);
    let copy = stage.copy_family(tracker).expect("copy");
    assert_eq!(stage.tracker_value(copy), Some(2.5));
    stage.set_tracker_value(tracker, 9.0).expect("set");
    assert_eq!(stage.tracker_value(copy), Some(2.5), "independent state");

    // become copies tracker state across, like data.
    stage.become_mobject(copy, tracker, false).expect("become");
    assert_eq!(stage.tracker_value(copy), Some(9.0));
}

/// Stage snapshots preserve the target/saved-state links, so Studio undo
/// and replay barriers restore the whole §8.3 state.
#[test]
fn snapshot_preserves_copy_links() {
    let mut stage = Stage::new();
    let mob = stage.add(Mobject::from_points(&[[1.0, 0.0, 0.0]]));
    let saved = stage.save_state(mob).expect("save");
    let target = stage.generate_target(mob).expect("generate");

    let snap = stage.snapshot();
    let wiped = stage.add(Mobject::new());
    stage.generate_target(mob).expect("replace target");
    stage.restore(&snap);

    assert_eq!(stage.target(mob), Some(target));
    assert_eq!(stage.saved_state(mob), Some(saved));
    assert_eq!(stage.saved_state(target), Some(saved));
    assert!(!stage.contains(wiped), "post-snapshot handles went stale");
}

#[test]
fn copy_of_stale_handle_is_refused() {
    let mut stage = Stage::new();
    let mob = stage.add(Mobject::from_points(&[[0.0; 3]]));
    stage.delete(mob).expect("delete");
    assert_eq!(
        stage.copy_family_mapped(mob).err(),
        Some(StageError::StaleHandle)
    );
    assert_eq!(
        stage.generate_target(mob).err(),
        Some(StageError::StaleHandle)
    );
    assert_eq!(stage.save_state(mob).err(), Some(StageError::StaleHandle));
}
