//! Structural parity against the pinned Reference
//! (`3b1b/manim` @ `6199a00d`): fixtures under `fixtures/` are generated by
//! `scripts/gen_geom_fixtures.py` from the Reference's own code. The
//! `quadpath_cases` op sequences here mirror, by name, the sequences in that
//! script — keep the two in sync.
//!
//! Tolerances: pure-f64 fixtures compare at 1e-9 (solver pivoting order may
//! differ from LAPACK); VMobject-driven fixtures compare at 5e-6 because the
//! Reference stores points in f32 while we compute in f64 (§6.1) — the
//! plan's "loose f32 tolerances" for structural fixtures.

use fmn_core::constants::{DEG, TAU};
use fmn_core::types::Vec3;
use fmn_geom::bezier;
use fmn_geom::cubic;
use fmn_geom::smoothing;
use fmn_geom::{AnchorMode, QuadPath};

const F64_TOL: f64 = 1e-9;
const F32_TOL: f64 = 5e-6;

fn fixture(name: &str) -> String {
    let path = format!("{}/fixtures/{name}", env!("CARGO_MANIFEST_DIR"));
    std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("reading {path}: {e}"))
}

/// Split a fixture file into `case`-blocks of non-comment lines.
fn cases(content: &str) -> Vec<(String, Vec<String>)> {
    let mut out = Vec::new();
    let mut current: Option<(String, Vec<String>)> = None;
    for line in content.lines() {
        if line.starts_with('#') || line.is_empty() {
            continue;
        }
        if let Some(name) = line.strip_prefix("case ") {
            current = Some((name.to_string(), Vec::new()));
        } else if line == "end" {
            out.push(current.take().expect("end outside case"));
        } else if let Some((_, lines)) = current.as_mut() {
            lines.push(line.to_string());
        }
    }
    out
}

/// Parse `label <n>` followed by `n` tab-separated points, starting at
/// `lines[*index]`; advances the index.
fn parse_points(lines: &[String], index: &mut usize, label: &str) -> Vec<Vec3> {
    let header = &lines[*index];
    let count: usize = header
        .strip_prefix(&format!("{label} "))
        .unwrap_or_else(|| panic!("expected `{label} <n>`, got `{header}`"))
        .parse()
        .unwrap();
    *index += 1;
    let mut points = Vec::with_capacity(count);
    for _ in 0..count {
        let row: Vec<f64> = lines[*index]
            .split('\t')
            .map(|x| x.parse().unwrap())
            .collect();
        points.push([row[0], row[1], row[2]]);
        *index += 1;
    }
    points
}

fn assert_points_close(actual: &[Vec3], expected: &[Vec3], tol: f64, context: &str) {
    assert_eq!(
        actual.len(),
        expected.len(),
        "{context}: point count {} vs expected {}",
        actual.len(),
        expected.len()
    );
    for (i, (a, e)) in actual.iter().zip(expected.iter()).enumerate() {
        for k in 0..3 {
            assert!(
                (a[k] - e[k]).abs() < tol,
                "{context}: point {i} component {k}: {} vs {}",
                a[k],
                e[k]
            );
        }
    }
}

#[test]
fn smooth_cubic_handles_match_scipy_solves() {
    for (name, lines) in cases(&fixture("smooth_cubic_handles.txt")) {
        let mut i = 0;
        let anchors = parse_points(&lines, &mut i, "anchors");
        let h1_expected = parse_points(&lines, &mut i, "h1");
        let h2_expected = parse_points(&lines, &mut i, "h2");
        let (h1, h2) = smoothing::smooth_cubic_handles(&anchors).unwrap();
        assert_points_close(&h1, &h1_expected, F64_TOL, &format!("{name}/h1"));
        assert_points_close(&h2, &h2_expected, F64_TOL, &format!("{name}/h2"));
    }
}

#[test]
fn approx_smooth_handles_match_reference() {
    for (name, lines) in cases(&fixture("approx_smooth_handles.txt")) {
        let mut i = 0;
        let anchors = parse_points(&lines, &mut i, "anchors");
        let expected = parse_points(&lines, &mut i, "handles");
        let handles = smoothing::approx_smooth_quadratic_handles(&anchors);
        assert_points_close(&handles, &expected, F64_TOL, &name);
    }
}

#[test]
fn quadratic_approximation_of_cubic_matches_reference() {
    for (name, lines) in cases(&fixture("quad_approx_cubic.txt")) {
        let mut i = 0;
        let control = parse_points(&lines, &mut i, "cubic");
        let expected = parse_points(&lines, &mut i, "quads");
        let out =
            cubic::quadratic_approximation_of_cubic(control[0], control[1], control[2], control[3]);
        assert_points_close(&out, &expected, F64_TOL, &name);
    }
}

#[test]
fn arc_points_match_reference() {
    for (name, lines) in cases(&fixture("arc_points.txt")) {
        let angle: f64 = lines[0].strip_prefix("angle ").unwrap().parse().unwrap();
        let n: usize = lines[1]
            .strip_prefix("n_components ")
            .unwrap()
            .parse()
            .unwrap();
        let mut i = 2;
        let expected = parse_points(&lines, &mut i, "points");
        let points = bezier::quadratic_points_for_arc(angle, n);
        assert_points_close(&points, &expected, F64_TOL, &name);
    }
}

/// Build the QuadPath op sequence mirroring the same-named generator case.
fn build_case(name: &str) -> QuadPath {
    let p = |x: f64, y: f64| -> Vec3 { [x, y, 0.0] };
    let mut path = QuadPath::new();
    match name {
        "line_quad_multi" => {
            path.start_new_path(p(0.0, 0.0));
            path.add_line_to(p(1.0, 0.0), true).unwrap();
            path.add_quadratic_bezier_curve_to(p(1.5, 1.0), p(2.0, 0.0), true)
                .unwrap();
            path.start_new_path(p(3.0, 0.0));
            path.add_line_to(p(4.0, 1.0), true).unwrap();
        }
        "corners_closed_square" => {
            path.set_points_as_corners(&[
                p(0.0, 0.0),
                p(2.0, 0.0),
                p(2.0, 2.0),
                p(0.0, 2.0),
                p(0.0, 0.0),
            ])
            .unwrap();
        }
        "cubic_curve" => {
            path.start_new_path(p(0.0, 0.0));
            path.add_cubic_bezier_curve_to(p(0.0, 1.0), p(1.0, 2.0), p(2.0, 2.0))
                .unwrap();
        }
        "cubic_simple_approx" => {
            path.set_use_simple_quadratic_approx(true);
            path.start_new_path(p(0.0, 0.0));
            path.add_cubic_bezier_curve_to(p(1.0, 0.25), p(2.0, 0.5), p(3.0, 1.0))
                .unwrap();
        }
        "smooth_chain" => {
            path.start_new_path(p(0.0, 0.0));
            path.add_line_to(p(1.0, 1.0), true).unwrap();
            path.add_smooth_curve_to(p(2.0, 0.0)).unwrap();
            path.add_smooth_curve_to(p(3.0, 1.0)).unwrap();
        }
        "smooth_cubic_chain" => {
            path.start_new_path(p(0.0, 0.0));
            path.add_smooth_cubic_curve_to(p(0.5, 1.0), p(1.0, 1.0))
                .unwrap();
            path.add_smooth_cubic_curve_to(p(2.0, 0.0), p(2.5, 0.5))
                .unwrap();
        }
        "arc_to_quarter" => {
            path.start_new_path(p(1.0, 0.0));
            path.add_arc_to(p(0.0, 1.0), TAU / 4.0, Some(4)).unwrap();
        }
        "close_path_line" => {
            path.set_points_as_corners(&[p(0.0, 0.0), p(2.0, 0.0), p(1.0, 2.0)])
                .unwrap();
            path.close_path(false).unwrap();
        }
        "close_path_smooth" => {
            path.set_points_as_corners(&[p(0.0, 0.0), p(2.0, 0.0), p(1.0, 2.0)])
                .unwrap();
            path.close_path(true).unwrap();
        }
        "start_new_path_singleton" => {
            path.start_new_path(p(0.0, 0.0));
            path.start_new_path(p(1.0, 1.0));
        }
        "single_point" => {
            path.start_new_path(p(1.0, 2.0));
        }
        "reverse_multi" => {
            path = build_case("line_quad_multi");
            path.reverse_points();
        }
        "make_jagged_arc" => {
            path.set_points(bezier::quadratic_points_for_arc(TAU / 4.0, 4))
                .unwrap();
            path.change_anchor_mode(AnchorMode::Jagged).unwrap();
        }
        "approx_smooth_zigzag" => {
            path.set_points_as_corners(&[
                p(0.0, 0.0),
                p(1.0, 1.0),
                p(2.0, 0.0),
                p(3.0, 1.0),
                p(4.0, 0.0),
            ])
            .unwrap();
            path.make_smooth(true).unwrap();
        }
        "subdivide_sharp_arc" => {
            path.set_points(bezier::quadratic_points_for_arc(TAU / 4.0, 1))
                .unwrap();
            path.subdivide_sharp_curves(30.0 * DEG);
        }
        "insert_curves" => {
            path.set_points_as_corners(&[p(0.0, 0.0), p(1.0, 0.0), p(4.0, 0.0)])
                .unwrap();
            path.insert_n_curves(3);
        }
        "null_line" => {
            path.start_new_path(p(0.0, 0.0));
            path.add_line_to(p(0.0, 0.0), true).unwrap();
            path.add_line_to(p(1.0, 0.0), true).unwrap();
        }
        "two_subpaths_last_closed" => {
            path.set_points_as_corners(&[p(5.0, 5.0), p(6.0, 5.0)])
                .unwrap();
            let mut other = QuadPath::new();
            other
                .set_points_as_corners(&[p(0.0, 0.0), p(2.0, 0.0), p(2.0, 2.0), p(0.0, 0.0)])
                .unwrap();
            let other_points = other.points().to_vec();
            path.add_subpath(&other_points).unwrap();
        }
        other => panic!("unknown fixture case `{other}` — sync with gen_geom_fixtures.py"),
    }
    path
}

#[test]
fn quadpath_op_sequences_match_vmobject() {
    for (name, lines) in cases(&fixture("quadpath_cases.txt")) {
        let mut i = 0;
        let expected_points = parse_points(&lines, &mut i, "points");
        let expected_ends: Vec<usize> = lines[i]
            .strip_prefix("ends ")
            .unwrap()
            .split('\t')
            .map(|x| x.parse().unwrap())
            .collect();
        let expected_closed = lines[i + 1].strip_prefix("closed ").unwrap() == "1";
        let expected_angles: Vec<f64> = lines[i + 2]
            .strip_prefix("joint_angles ")
            .unwrap()
            .split('\t')
            .map(|x| x.parse().unwrap())
            .collect();

        let path = build_case(&name);
        assert_points_close(path.points(), &expected_points, F32_TOL, &name);
        assert_eq!(
            path.subpath_end_indices(),
            expected_ends,
            "{name}: subpath ends"
        );
        assert_eq!(path.is_closed(), expected_closed, "{name}: closure");
        let angles = path.joint_angles();
        assert_eq!(
            angles.len(),
            expected_angles.len(),
            "{name}: joint angle count"
        );
        if path.num_points() < 3 {
            // The Reference's joint angles for sub-curve paths are its
            // `np.ones` data default (never computed) — an initialization
            // artifact, not semantics. We report the correct 0.0 (D5).
            assert!(
                angles.iter().all(|a| *a == 0.0),
                "{name}: degenerate angles"
            );
        } else {
            for (k, (a, e)) in angles.iter().zip(expected_angles.iter()).enumerate() {
                assert!(
                    (a - e).abs() < F32_TOL,
                    "{name}: joint angle {k}: {a} vs {e}"
                );
            }
        }
    }
}
