//! space_ops + rotation-convention parity (fm-ngx, §7.5, §2.2, §16.4).
//!
//! `fixtures/space_ops.txt` is generated by
//! `scripts/gen_space_ops_fixtures.py`, which imports the pinned
//! Reference's own `manimlib/utils/space_ops.py` (and, underneath it,
//! scipy's `Rotation`) and records what it actually returns. Every case
//! below re-runs that call through fmn-geom and compares.
//!
//! Tolerances. Everything here is f64-in/f64-out with no f32 storage
//! anywhere, so the only sources of difference are (a) our transcendentals
//! (fmn-dmath, not the platform libm) and (b) arithmetic association. Both
//! are sub-ulp-ish, so the bar is tight: [`TOL`] absolute. Angles compare
//! modulo 2π ([`assert_angle`]) because an angle exactly at the ±π branch
//! is the *same angle* whichever side the last bit lands on — the wrap is
//! a representation choice, not a value.

use std::collections::HashMap;

use fmn_core::constants::{PI, TAU};
use fmn_core::types::Vec3;
use fmn_geom::rotation::{self, EulerSeq, Quat};
use fmn_geom::space_ops as so;

const TOL: f64 = 1e-12;

// ------------------------------------------------------------------ fixture

#[derive(Debug, Clone)]
enum Field {
    /// A single line of tab/space-separated numbers.
    Values(Vec<f64>),
    /// A `key rows <n>` block of `n` numeric rows.
    Rows(Vec<Vec<f64>>),
    /// A non-numeric token (an Euler sequence).
    Text(String),
}

struct Case {
    name: String,
    op: String,
    fields: HashMap<String, Field>,
}

impl Case {
    fn values(&self, key: &str) -> &[f64] {
        match self.fields.get(key) {
            Some(Field::Values(v)) => v,
            other => panic!("{}: field `{key}` is {other:?}, wanted values", self.name),
        }
    }

    fn scalar(&self, key: &str) -> f64 {
        let v = self.values(key);
        assert_eq!(v.len(), 1, "{}: field `{key}` is not a scalar", self.name);
        v[0]
    }

    /// Point fields are read through the Reference's own 2D→3D promotion,
    /// because the Reference passes 2-vectors to `tri_area` and friends.
    fn vec3(&self, key: &str) -> Vec3 {
        let v = self.values(key);
        assert!(
            v.len() == 2 || v.len() == 3,
            "{}: field `{key}` is not a point",
            self.name
        );
        so::promote_point(v)
    }

    fn quat(&self, key: &str) -> Quat {
        let v = self.values(key);
        assert_eq!(
            v.len(),
            4,
            "{}: field `{key}` is not a quaternion",
            self.name
        );
        [v[0], v[1], v[2], v[3]]
    }

    fn angles(&self, key: &str) -> [f64; 3] {
        let v = self.values(key);
        assert_eq!(v.len(), 3, "{}: field `{key}` is not 3 angles", self.name);
        [v[0], v[1], v[2]]
    }

    fn rows(&self, key: &str) -> &[Vec<f64>] {
        match self.fields.get(key) {
            Some(Field::Rows(r)) => r,
            other => panic!("{}: field `{key}` is {other:?}, wanted rows", self.name),
        }
    }

    fn points(&self, key: &str) -> Vec<Vec3> {
        self.rows(key)
            .iter()
            .map(|r| {
                assert_eq!(r.len(), 3, "{}: `{key}` row is not a point", self.name);
                [r[0], r[1], r[2]]
            })
            .collect()
    }

    fn matrix(&self, key: &str) -> [[f64; 3]; 3] {
        let rows = self.rows(key);
        assert_eq!(rows.len(), 3, "{}: `{key}` is not 3x3", self.name);
        let mut m = [[0.0; 3]; 3];
        for (out, r) in m.iter_mut().zip(rows) {
            assert_eq!(r.len(), 3, "{}: `{key}` row is not 3 wide", self.name);
            out.copy_from_slice(&r[..3]);
        }
        m
    }

    fn text(&self, key: &str) -> &str {
        match self.fields.get(key) {
            Some(Field::Text(s)) => s,
            other => panic!("{}: field `{key}` is {other:?}, wanted text", self.name),
        }
    }

    fn boolean(&self, key: &str) -> bool {
        self.scalar(key) != 0.0
    }
}

fn load_cases() -> Vec<Case> {
    let path = format!("{}/fixtures/space_ops.txt", env!("CARGO_MANIFEST_DIR"));
    let content = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("reading {path}: {e}"));

    let mut cases = Vec::new();
    let mut current: Option<Case> = None;
    let mut pending: Option<(String, usize, Vec<Vec<f64>>)> = None;

    for line in content.lines() {
        if line.starts_with('#') || line.is_empty() {
            continue;
        }
        if let Some((key, want, rows)) = pending.as_mut() {
            if rows.len() < *want {
                rows.push(line.split('\t').map(|t| t.parse().unwrap()).collect());
                if rows.len() == *want {
                    let (key, _, rows) = pending.take().unwrap();
                    let case = current.as_mut().expect("rows outside case");
                    case.fields.insert(key, Field::Rows(rows));
                }
                continue;
            }
            let _ = key;
        }
        if let Some(name) = line.strip_prefix("case ") {
            current = Some(Case {
                name: name.to_string(),
                op: String::new(),
                fields: HashMap::new(),
            });
            continue;
        }
        if line == "end" {
            cases.push(current.take().expect("end outside case"));
            continue;
        }
        let case = current.as_mut().expect("field outside case");
        let (key, rest) = line.split_once(' ').expect("field line needs a value");
        if key == "op" {
            case.op = rest.to_string();
            continue;
        }
        if let Some(count) = rest.strip_prefix("rows ") {
            let want: usize = count.parse().unwrap();
            if want == 0 {
                case.fields.insert(key.to_string(), Field::Rows(Vec::new()));
            } else {
                pending = Some((key.to_string(), want, Vec::new()));
            }
            continue;
        }
        let parsed: Option<Vec<f64>> = rest
            .split('\t')
            .map(|t| t.trim().parse::<f64>().ok())
            .collect();
        let field = match parsed {
            Some(values) => Field::Values(values),
            None => Field::Text(rest.to_string()),
        };
        case.fields.insert(key.to_string(), field);
    }
    assert!(current.is_none(), "unterminated case");
    assert!(!cases.is_empty(), "no cases parsed");
    cases
}

// -------------------------------------------------------------- assertions

#[track_caller]
fn assert_close(actual: f64, expected: f64, what: &str) {
    assert!(
        (actual - expected).abs() < TOL,
        "{what}: {actual} vs expected {expected}"
    );
}

#[track_caller]
fn assert_vec(actual: Vec3, expected: Vec3, what: &str) {
    for k in 0..3 {
        assert!(
            (actual[k] - expected[k]).abs() < TOL,
            "{what}: component {k}: {:?} vs expected {:?}",
            actual,
            expected
        );
    }
}

#[track_caller]
fn assert_quat(actual: Quat, expected: Quat, what: &str) {
    for k in 0..4 {
        assert!(
            (actual[k] - expected[k]).abs() < TOL,
            "{what}: component {k}: {:?} vs expected {:?} \
             (sign is part of the convention — not a free choice)",
            actual,
            expected
        );
    }
}

#[track_caller]
fn assert_matrix(actual: [[f64; 3]; 3], expected: [[f64; 3]; 3], what: &str) {
    for r in 0..3 {
        assert_vec(actual[r], expected[r], &format!("{what} row {r}"));
    }
}

/// Compare two angles modulo 2π: the ±π branch cut is a representation
/// choice, and a value that lands a bit either side of it is the same angle.
#[track_caller]
fn assert_angle(actual: f64, expected: f64, what: &str) {
    let diff = (actual - expected + PI).rem_euclid(TAU) - PI;
    assert!(
        diff.abs() < TOL,
        "{what}: {actual} vs expected {expected} (wrapped difference {diff})"
    );
}

// -------------------------------------------------------------------- test

#[test]
fn space_ops_matches_the_reference() {
    let cases = load_cases();
    let mut seen: HashMap<&str, usize> = HashMap::new();

    for case in &cases {
        let name = case.name.as_str();
        *seen.entry(case.op.as_str()).or_default() += 1;

        match case.op.as_str() {
            // ---------------------------------------------------- rotations
            "rotation_matrix" => assert_matrix(
                so::rotation_matrix(case.scalar("angle"), case.vec3("axis")),
                case.matrix("matrix"),
                name,
            ),
            "rotation_matrix_transpose" => assert_matrix(
                so::rotation_matrix_transpose(case.scalar("angle"), case.vec3("axis")),
                case.matrix("matrix"),
                name,
            ),
            "rotation_about_z" => assert_matrix(
                so::rotation_about_z(case.scalar("angle")),
                case.matrix("matrix"),
                name,
            ),
            "rotation_between_vectors" => assert_matrix(
                so::rotation_between_vectors(case.vec3("v1"), case.vec3("v2")),
                case.matrix("matrix"),
                name,
            ),
            "z_to_vector" => {
                assert_matrix(so::z_to_vector(case.vec3("v")), case.matrix("matrix"), name)
            }

            // -------------------------------------------------- quaternions
            "quaternion_from_angle_axis" => assert_quat(
                so::quaternion_from_angle_axis(case.scalar("angle"), case.vec3("axis")),
                case.quat("quat"),
                name,
            ),
            "angle_axis_from_quaternion" => {
                let (angle, axis) =
                    so::angle_axis_from_quaternion(case.quat("quat")).expect("non-identity");
                assert_close(angle, case.scalar("angle"), &format!("{name}/angle"));
                assert_vec(axis, case.vec3("axis"), &format!("{name}/axis"));
            }
            "quaternion_mult" => {
                let quats: Vec<Quat> = case
                    .rows("quats")
                    .iter()
                    .map(|r| [r[0], r[1], r[2], r[3]])
                    .collect();
                assert_quat(so::quaternion_mult(&quats), case.quat("quat"), name);
            }
            "quaternion_conjugate" => assert_quat(
                so::quaternion_conjugate(case.quat("quat")),
                case.quat("out"),
                name,
            ),
            "rotation_matrix_from_quaternion" => assert_matrix(
                so::rotation_matrix_from_quaternion(case.quat("quat")).expect("unit quat"),
                case.matrix("matrix"),
                name,
            ),
            "rotation_matrix_transpose_from_quaternion" => assert_matrix(
                so::rotation_matrix_transpose_from_quaternion(case.quat("quat"))
                    .expect("unit quat"),
                case.matrix("matrix"),
                name,
            ),

            // -------------------------------------------------------- Euler
            "as_euler" => {
                let seq = EulerSeq::parse(case.text("seq")).expect("known sequence");
                let got = rotation::euler_from_quat(case.quat("quat"), seq).expect("unit quat");
                let expected = case.angles("angles");
                for (k, want) in expected.iter().enumerate() {
                    assert_angle(got.angles[k], *want, &format!("{name}/angle {k}"));
                }
            }
            "from_euler" => {
                let seq = EulerSeq::parse(case.text("seq")).expect("known sequence");
                let quat = rotation::quat_from_euler(seq, case.angles("angles"));
                assert_quat(quat, case.quat("quat"), &format!("{name}/quat"));
                assert_matrix(
                    rotation::matrix_from_unit_quat(quat),
                    case.matrix("matrix"),
                    &format!("{name}/matrix"),
                );
            }

            // ------------------------------------------------ vector basics
            "rotate_vector" => assert_vec(
                so::rotate_vector(case.vec3("v"), case.scalar("angle"), case.vec3("axis")),
                case.vec3("out"),
                name,
            ),
            "rotate_vector_2d" => {
                let v = case.values("v");
                let out = so::rotate_vector_2d([v[0], v[1]], case.scalar("angle"));
                let expected = case.values("out");
                assert_close(out[0], expected[0], &format!("{name}/re"));
                assert_close(out[1], expected[1], &format!("{name}/im"));
            }
            "angle_of_vector" => assert_angle(
                so::angle_of_vector(case.vec3("v")),
                case.scalar("angle"),
                name,
            ),
            "angle_between_vectors" => assert_close(
                so::angle_between_vectors(case.vec3("v1"), case.vec3("v2")),
                case.scalar("angle"),
                name,
            ),
            "get_norm" => assert_close(so::get_norm(case.vec3("v")), case.scalar("norm"), name),
            "norm_squared" => {
                assert_close(so::norm_squared(case.vec3("v")), case.scalar("value"), name)
            }
            "get_dist" => assert_close(
                so::get_dist(case.vec3("v1"), case.vec3("v2")),
                case.scalar("value"),
                name,
            ),
            "normalize" => assert_vec(so::normalize(case.vec3("v")), case.vec3("out"), name),
            "normalize_fallback" => assert_vec(
                so::normalize_or(case.vec3("v"), case.vec3("fallback")),
                case.vec3("out"),
                name,
            ),
            "cross" => assert_vec(
                so::cross(case.vec3("v1"), case.vec3("v2")),
                case.vec3("out"),
                name,
            ),
            "cross2d" => assert_close(
                so::cross2d(case.vec3("v1"), case.vec3("v2")),
                case.scalar("value"),
                name,
            ),
            "midpoint" => assert_vec(
                so::midpoint(case.vec3("v1"), case.vec3("v2")),
                case.vec3("out"),
                name,
            ),
            "get_unit_normal" => assert_vec(
                so::get_unit_normal(
                    case.vec3("v1"),
                    case.vec3("v2"),
                    so::DEFAULT_UNIT_NORMAL_TOL,
                ),
                case.vec3("out"),
                name,
            ),
            "project_along_vector" => assert_vec(
                so::project_along_vector(case.vec3("point"), case.vec3("v")),
                case.vec3("out"),
                name,
            ),

            // --------------------------------------------- planar geometry
            "find_intersection" => assert_vec(
                so::find_intersection(
                    case.vec3("p0"),
                    case.vec3("v0"),
                    case.vec3("p1"),
                    case.vec3("v1"),
                    case.scalar("threshold"),
                ),
                case.vec3("out"),
                name,
            ),
            "line_intersection" => assert_vec(
                so::line_intersection(
                    (case.vec3("l1a"), case.vec3("l1b")),
                    (case.vec3("l2a"), case.vec3("l2b")),
                )
                .expect("non-parallel"),
                case.vec3("out"),
                name,
            ),
            "get_closest_point_on_line" => assert_vec(
                so::get_closest_point_on_line(case.vec3("a"), case.vec3("b"), case.vec3("p")),
                case.vec3("out"),
                name,
            ),
            "get_winding_number" => {
                // The generator's closed paths repeat their first point;
                // our cyclic reading of the same list adds one zero-length
                // step, so the value is unchanged.
                assert_close(
                    so::get_winding_number(&case.points("points")),
                    case.scalar("value"),
                    name,
                )
            }
            "compass_directions" => {
                let n = case.scalar("n") as usize;
                let got = so::compass_directions(n, case.vec3("start"));
                let expected = case.points("points");
                assert_eq!(got.len(), expected.len(), "{name}: count");
                for (i, (a, e)) in got.iter().zip(&expected).enumerate() {
                    assert_vec(*a, *e, &format!("{name}/{i}"));
                }
            }
            "tri_area" => assert_close(
                so::tri_area(case.vec3("a"), case.vec3("b"), case.vec3("c")),
                case.scalar("value"),
                name,
            ),
            "is_inside_triangle" => assert_eq!(
                so::is_inside_triangle(
                    case.vec3("p"),
                    case.vec3("a"),
                    case.vec3("b"),
                    case.vec3("c")
                ),
                case.boolean("value"),
                "{name}"
            ),
            "line_intersects_path" => assert_eq!(
                so::line_intersects_path(
                    case.vec3("start"),
                    case.vec3("end"),
                    &case.points("path")
                ),
                case.boolean("value"),
                "{name}"
            ),
            "poly_line_length" => assert_close(
                so::poly_line_length(&case.points("points")),
                case.scalar("value"),
                name,
            ),
            "center_of_mass" => assert_vec(
                so::center_of_mass(&case.points("points")),
                case.vec3("out"),
                name,
            ),

            // ------------------------------------------------------- misc
            "complex_to_R3" => {
                let z = case.values("z");
                assert_vec(so::complex_to_r3([z[0], z[1]]), case.vec3("out"), name);
            }
            "R3_to_complex" => {
                let got = so::r3_to_complex(case.vec3("point"));
                let expected = case.values("z");
                assert_close(got[0], expected[0], &format!("{name}/re"));
                assert_close(got[1], expected[1], &format!("{name}/im"));
            }
            "thick_diagonal" => {
                let dim = case.scalar("dim") as usize;
                let thickness = case.scalar("thickness") as usize;
                let got = so::thick_diagonal(dim, thickness);
                let expected = case.rows("matrix");
                assert_eq!(got.len(), expected.len(), "{name}: rows");
                for (r, (row, exp)) in got.iter().zip(expected).enumerate() {
                    for (c, (v, e)) in row.iter().zip(exp).enumerate() {
                        assert_eq!(f64::from(*v), *e, "{name}: [{r}][{c}]");
                    }
                }
            }

            other => panic!(
                "{name}: unhandled op `{other}` — the fixture grew a case the test does not check"
            ),
        }
    }

    // The generator and this test are two halves of one contract: if a
    // family stops being generated, the silence should fail here.
    for op in [
        "rotation_matrix",
        "rotation_between_vectors",
        "quaternion_from_angle_axis",
        "angle_axis_from_quaternion",
        "as_euler",
        "from_euler",
        "rotate_vector",
        "find_intersection",
        "get_unit_normal",
        "compass_directions",
    ] {
        assert!(seen.contains_key(op), "fixture lost its `{op}` cases");
    }
    assert!(cases.len() > 400, "fixture shrank to {} cases", cases.len());
}
