//! The Animation contract (fm-67a acceptance): lifecycle order over the
//! §9.2 sample points, the `get_sub_alpha` fixture corpus from the pinned
//! Reference formula, `prepare_animation`'s typed boundary, and the
//! normalized-alpha pipeline's composition properties.
//!
//! Fixtures are generated by `scripts/gen_anim_fixtures.py` from the
//! Reference formulas at `3b1b/manim @ 6199a00d…`; regenerate there, never
//! hand-edit. Tolerance 1e-12 absolute (formulas agree to ~1e-15; the
//! slack absorbs libm ulp differences only).

use std::cell::RefCell;
use std::rc::Rc;

use fmn_anim::{
    AnimConfig, AnimError, AnimState, Animation, MethodAnimation, RateFunc, RationalFrameClock,
    prepare_animation, sub_alpha, time_spanned_alpha,
};
use fmn_core::rate;
use fmn_mobject::animate::AnimateArgs;
use fmn_mobject::{Mob, Mobject, Stage};

const TOL: f64 = 1e-12;

fn square(stage: &mut Stage) -> Mob {
    stage.add(Mobject::from_points(&[
        [-0.5, -0.5, 0.0],
        [0.5, -0.5, 0.0],
        [0.5, 0.5, 0.0],
        [-0.5, 0.5, 0.0],
    ]))
}

// ------------------------------------------------------- fixture corpora

#[test]
fn sub_alpha_matches_the_reference_corpus() {
    for (lineno, line) in include_str!("../fixtures/sub_alpha.txt")
        .lines()
        .enumerate()
    {
        let cols: Vec<&str> = line.split('\t').collect();
        let [rate_name, lag, num, index, alpha, expected] = cols[..] else {
            panic!("fixture line {lineno} malformed: {line:?}");
        };
        let rate_func = match rate_name {
            "linear" => RateFunc::linear(),
            "smooth" => RateFunc::smooth(),
            other => panic!("unknown rate {other}"),
        };
        let got = sub_alpha(
            alpha.parse().unwrap(),
            index.parse().unwrap(),
            num.parse().unwrap(),
            lag.parse().unwrap(),
            &rate_func,
        );
        let want: f64 = expected.parse().unwrap();
        assert!(
            (got - want).abs() <= TOL,
            "line {lineno} ({line}): got {got:?}, Reference formula says {want:?}"
        );
    }
}

#[test]
fn time_spanned_alpha_matches_the_reference_corpus() {
    for (lineno, line) in include_str!("../fixtures/time_spanned.txt")
        .lines()
        .enumerate()
    {
        let cols: Vec<&str> = line.split('\t').collect();
        let [run_time, start, end, alpha, expected] = cols[..] else {
            panic!("fixture line {lineno} malformed: {line:?}");
        };
        let got = time_spanned_alpha(
            alpha.parse().unwrap(),
            run_time.parse().unwrap(),
            Some((start.parse().unwrap(), end.parse().unwrap())),
        );
        let want: f64 = expected.parse().unwrap();
        assert!(
            (got - want).abs() <= TOL,
            "line {lineno} ({line}): got {got:?}, Reference formula says {want:?}"
        );
    }
}

// ------------------------------------------- pipeline composition properties

#[test]
fn rate_func_combinators_match_the_fmn_core_closures() {
    let squished = RateFunc::smooth().squish(0.3, 0.7);
    let reference = rate::squish_rate_func(rate::smooth, 0.3, 0.7);
    let scaled = RateFunc::smooth().not_quite_there(0.7);
    let reference_scaled = rate::not_quite_there(rate::smooth, 0.7);
    for i in 0..=1000 {
        let t = f64::from(i) / 1000.0;
        assert_eq!(squished.eval(t), reference(t), "squish at t={t}");
        assert_eq!(scaled.eval(t), reference_scaled(t), "scaled at t={t}");
    }
}

#[test]
fn degenerate_squish_returns_the_window_point() {
    // The Reference's a == b branch returns a itself, not func(a).
    let f = RateFunc::smooth().squish(0.4, 0.4);
    assert_eq!(f.eval(0.0), 0.4);
    assert_eq!(f.eval(0.9), 0.4);
}

#[test]
fn squish_of_squish_composes_affinely() {
    // squish(squish(f, a2, b2), a1, b1) ≡ squish(f, a1 + a2·w, a1 + b2·w)
    // with w = b1 − a1 — associativity of window composition, where both
    // windows are non-degenerate.
    let (a1, b1, a2, b2) = (0.2, 0.8, 0.25, 0.75);
    let nested = RateFunc::smooth().squish(a2, b2).squish(a1, b1);
    let w = b1 - a1;
    let flat = RateFunc::smooth().squish(a1 + a2 * w, a1 + b2 * w);
    for i in 0..=1000 {
        let t = f64::from(i) / 1000.0;
        assert!(
            (nested.eval(t) - flat.eval(t)).abs() <= TOL,
            "t={t}: nested {} vs flat {}",
            nested.eval(t),
            flat.eval(t)
        );
    }
}

#[test]
fn lag_zero_is_simultaneous_and_lag_one_is_successive() {
    let linear = RateFunc::linear();
    // lag 0: every submobject sees the raw alpha.
    for index in 0..5 {
        assert_eq!(sub_alpha(0.37, index, 5, 0.0, &linear), 0.37);
    }
    // lag 1, two submobjects: the first finishes exactly as the second
    // starts (alpha 0.5 is the handoff).
    assert_eq!(sub_alpha(0.5, 0, 2, 1.0, &linear), 1.0);
    assert_eq!(sub_alpha(0.5, 1, 2, 1.0, &linear), 0.0);
}

// ------------------------------------------------------ a probe animation

/// Shared log of `(row index, sub_alpha)` pairs a [`Probe`] writes.
type RowLog = Rc<RefCell<Vec<(usize, f64)>>>;

/// Records every `interpolate_submobject` row: (row index, sub_alpha) —
/// each interpolate pass appends one row per zipped family entry, so tests
/// can count passes and inspect the pipeline output.
struct Probe {
    state: AnimState,
    rows: RowLog,
    row_counter: usize,
}

impl Probe {
    fn new(mobject: Mob, config: AnimConfig) -> (Self, RowLog) {
        let rows = Rc::new(RefCell::new(Vec::new()));
        (
            Self {
                state: AnimState::new(mobject, config),
                rows: Rc::clone(&rows),
                row_counter: 0,
            },
            rows,
        )
    }
}

impl Animation for Probe {
    fn state(&self) -> &AnimState {
        &self.state
    }

    fn state_mut(&mut self) -> &mut AnimState {
        &mut self.state
    }

    fn interpolate_submobject(&mut self, _stage: &mut Stage, _mobs: &[Mob], sub_alpha: f64) {
        let index = self.row_counter % self.state.families().len().max(1);
        self.row_counter += 1;
        self.rows.borrow_mut().push((index, sub_alpha));
    }
}

// ------------------------------------------------------------- lifecycle

#[test]
fn begin_interpolates_at_zero_exactly_once() {
    let mut stage = Stage::new();
    let mob = square(&mut stage);
    let (mut probe, rows) = Probe::new(
        mob,
        AnimConfig {
            rate_func: RateFunc::linear(),
            ..AnimConfig::default()
        },
    );
    probe.begin(&mut stage).expect("begin succeeds");
    // One pass over the zipped rows (single-node family → one row), at
    // alpha zero.
    assert_eq!(rows.borrow().as_slice(), &[(0, 0.0)]);
    // The starting copy exists and is distinct.
    let starting = probe.state().starting_mobject().expect("copied at begin");
    assert_ne!(starting, mob);
    assert!(stage.contains(starting));
}

#[test]
fn play_over_clock_samples_is_monotone_and_ends_at_one() {
    let mut stage = Stage::new();
    let mob = square(&mut stage);
    let (mut probe, rows) = Probe::new(
        mob,
        AnimConfig {
            rate_func: RateFunc::smooth(),
            ..AnimConfig::default()
        },
    );
    let clock = RationalFrameClock::new(30).expect("fps");
    let segment = clock.segment(1.0).expect("segment");

    probe.begin(&mut stage).expect("begin");
    for sample in segment.samples() {
        probe.interpolate(&mut stage, sample.alpha);
    }
    probe.finish(&mut stage);

    let recorded: Vec<f64> = rows.borrow().iter().map(|&(_, a)| a).collect();
    // begin(0) + 30 emitted samples + finish(final_alpha_value).
    assert_eq!(recorded.len(), 32);
    assert_eq!(recorded[0], 0.0);
    assert!(
        recorded.windows(2).all(|w| w[1] >= w[0]),
        "sub_alpha sequence must be monotone under smooth: {recorded:?}"
    );
    assert_eq!(*recorded.last().unwrap(), 1.0);
}

#[test]
fn skipped_playback_still_begins_and_finishes_exactly_once() {
    let mut stage = Stage::new();
    let mob = square(&mut stage);
    let (mut probe, rows) = Probe::new(
        mob,
        AnimConfig {
            rate_func: RateFunc::linear(),
            ..AnimConfig::default()
        },
    );
    let clock = RationalFrameClock::new(30).expect("fps");
    let segment = clock.segment(1.0).expect("segment");

    probe.begin(&mut stage).expect("begin");
    let skip = segment.skip_sample().expect("nonempty segment");
    probe.interpolate(&mut stage, skip.alpha);
    probe.finish(&mut stage);

    // Exactly three passes: begin's zero, the one skip step, finish.
    let recorded: Vec<f64> = rows.borrow().iter().map(|&(_, a)| a).collect();
    assert_eq!(recorded, vec![0.0, 1.0, 1.0]);
}

#[test]
fn finish_lands_on_final_alpha_value() {
    let mut stage = Stage::new();
    let mob = square(&mut stage);
    let (mut probe, rows) = Probe::new(
        mob,
        AnimConfig {
            rate_func: RateFunc::linear(),
            final_alpha_value: 0.25,
            ..AnimConfig::default()
        },
    );
    probe.begin(&mut stage).expect("begin");
    probe.finish(&mut stage);
    assert_eq!(rows.borrow().last().copied(), Some((0, 0.25)));
}

#[test]
fn begin_widens_run_time_to_the_time_span_end() {
    let mut stage = Stage::new();
    let mob = square(&mut stage);
    let (mut probe, _rows) = Probe::new(
        mob,
        AnimConfig {
            run_time: 1.0,
            time_span: Some((0.5, 2.5)),
            rate_func: RateFunc::linear(),
            ..AnimConfig::default()
        },
    );
    // get_run_time reports the widened value even before begin.
    assert_eq!(probe.get_run_time(), 2.5);
    probe.begin(&mut stage).expect("begin");
    assert_eq!(probe.state().config.run_time, 2.5);
}

#[test]
fn hollow_time_span_is_a_named_error() {
    let mut stage = Stage::new();
    let mob = square(&mut stage);
    let (mut probe, _rows) = Probe::new(
        mob,
        AnimConfig {
            time_span: Some((1.0, 1.0)),
            ..AnimConfig::default()
        },
    );
    assert_eq!(
        probe.begin(&mut stage),
        Err(AnimError::InvalidTimeSpan {
            start: 1.0,
            end: 1.0
        })
    );
}

#[test]
fn time_span_windows_the_play() {
    // run_time 2, span (0.5, 1.5): before 0.25 of the segment nothing
    // moves; after 0.75 it is done; the middle is a linear ramp.
    let mut stage = Stage::new();
    let mob = square(&mut stage);
    let (mut probe, rows) = Probe::new(
        mob,
        AnimConfig {
            run_time: 2.0,
            time_span: Some((0.5, 1.5)),
            rate_func: RateFunc::linear(),
            ..AnimConfig::default()
        },
    );
    probe.begin(&mut stage).expect("begin");
    rows.borrow_mut().clear();
    for alpha in [0.0, 0.125, 0.25, 0.5, 0.75, 0.9, 1.0] {
        probe.interpolate(&mut stage, alpha);
    }
    let recorded: Vec<f64> = rows.borrow().iter().map(|&(_, a)| a).collect();
    let expected = [0.0, 0.0, 0.0, 0.5, 1.0, 1.0, 1.0];
    for (got, want) in recorded.iter().zip(expected) {
        assert!((got - want).abs() <= TOL, "{recorded:?} vs {expected:?}");
    }
}

#[test]
fn suspend_mobject_updating_pauses_and_finish_resumes_with_one_call() {
    let mut stage = Stage::new();
    let mob = square(&mut stage);
    let calls = Rc::new(RefCell::new(0usize));
    let counter = Rc::clone(&calls);
    stage
        .add_dt_updater(
            mob,
            move |_stage, _mob, _dt| {
                *counter.borrow_mut() += 1;
            },
            false,
        )
        .expect("registers");
    stage.add_to_scene(mob).expect("rooted");

    let (mut probe, _rows) = Probe::new(
        mob,
        AnimConfig {
            suspend_mobject_updating: true,
            ..AnimConfig::default()
        },
    );
    probe.begin(&mut stage).expect("begin");
    stage.update(1.0 / 30.0);
    assert_eq!(*calls.borrow(), 0, "suspended during the play");

    probe.finish(&mut stage);
    // resume_updating's call_updater pass runs update(0) exactly once (C-5).
    assert_eq!(*calls.borrow(), 1, "finish resumes with one update(0)");
    stage.update(1.0 / 30.0);
    assert_eq!(*calls.borrow(), 2, "updating resumed after finish");
}

#[test]
fn finish_does_not_resume_a_mobject_that_was_already_suspended() {
    let mut stage = Stage::new();
    let mob = square(&mut stage);
    let calls = Rc::new(RefCell::new(0usize));
    let counter = Rc::clone(&calls);
    stage
        .add_dt_updater(
            mob,
            move |_stage, _mob, _dt| {
                *counter.borrow_mut() += 1;
            },
            false,
        )
        .expect("registers");
    stage.add_to_scene(mob).expect("rooted");
    stage.suspend_updating(mob, true); // the user's own suspension

    let (mut probe, _rows) = Probe::new(
        mob,
        AnimConfig {
            suspend_mobject_updating: true,
            ..AnimConfig::default()
        },
    );
    probe.begin(&mut stage).expect("begin");
    probe.finish(&mut stage);
    stage.update(1.0 / 30.0);
    assert_eq!(
        *calls.borrow(),
        0,
        "the animation must not resume what it did not pause"
    );
}

#[test]
fn animating_status_marks_family_and_ancestors_and_clears_at_finish() {
    let mut stage = Stage::new();
    let child = square(&mut stage);
    let parent = stage.add(Mobject::new());
    stage.attach(parent, child).expect("attach");

    let (mut probe, _rows) = Probe::new(child, AnimConfig::default());
    probe.begin(&mut stage).expect("begin");
    assert!(stage.is_animating(child));
    assert!(
        stage.is_animating(parent),
        "ancestors are marked (the Reference's get_ancestors walk)"
    );
    assert!(stage.is_changing(child));

    probe.finish(&mut stage);
    assert!(!stage.is_animating(child));
    assert!(!stage.is_animating(parent));
}

#[test]
fn update_mobjects_ticks_the_copies_not_the_scene_mobject() {
    let mut stage = Stage::new();
    let mob = square(&mut stage);
    let ticked: Rc<RefCell<Vec<Mob>>> = Rc::new(RefCell::new(Vec::new()));
    let sink = Rc::clone(&ticked);
    stage
        .add_dt_updater(
            mob,
            move |_stage, m, _dt| {
                sink.borrow_mut().push(m);
            },
            false,
        )
        .expect("registers");

    let (mut probe, _rows) = Probe::new(mob, AnimConfig::default());
    probe.begin(&mut stage).expect("begin");
    let starting = probe.state().starting_mobject().expect("copied");

    probe.update_mobjects(&mut stage, 1.0 / 30.0);
    // The starting copy shares the updater callable (§8.3) and is the one
    // ticked; the scene's own mobject is the scene's responsibility.
    assert_eq!(ticked.borrow().as_slice(), &[starting]);
    assert_eq!(probe.mobjects_to_update(), vec![starting]);
}

#[test]
fn lag_distributes_across_the_zipped_family_rows() {
    let mut stage = Stage::new();
    let a = Mobject::from_points(&[[0.0, 0.0, 0.0]]);
    let b = Mobject::from_points(&[[1.0, 0.0, 0.0]]);
    let group = stage.add(Mobject::group(vec![a, b]));

    let lag_ratio = 1.0;
    let (mut probe, rows) = Probe::new(
        group,
        AnimConfig {
            lag_ratio,
            rate_func: RateFunc::linear(),
            ..AnimConfig::default()
        },
    );
    probe.begin(&mut stage).expect("begin");
    rows.borrow_mut().clear();

    let alpha = 0.5;
    probe.interpolate(&mut stage, alpha);
    let recorded = rows.borrow().clone();
    // Family is [group, a, b] — three rows, each at the pipeline value.
    assert_eq!(recorded.len(), 3);
    let linear = RateFunc::linear();
    for (index, got) in &recorded {
        let want = sub_alpha(alpha, *index, 3, lag_ratio, &linear);
        assert!((got - want).abs() <= TOL, "row {index}: {got} vs {want}");
    }
}

#[test]
fn update_rate_info_sets_explicit_zeros() {
    // Deliberate divergence (D5): the Reference's `or`-merge ignores an
    // explicit 0; Some(0.0) must set here.
    let mut stage = Stage::new();
    let mob = square(&mut stage);
    let (mut probe, _rows) = Probe::new(mob, AnimConfig::default());
    probe.update_rate_info(Some(0.0), None, Some(0.0));
    assert_eq!(probe.state().config.run_time, 0.0);
    assert_eq!(probe.state().config.lag_ratio, 0.0);
    probe.update_rate_info(None, Some(RateFunc::linear()), None);
    assert_eq!(probe.state().config.run_time, 0.0, "None keeps");
}

// ------------------------------------------- MethodAnimation + prepare

#[test]
fn animate_chain_plays_source_to_target() {
    let mut stage = Stage::new();
    let mob = square(&mut stage);
    let builder = mob
        .animate()
        .set_anim_args(AnimateArgs {
            rate_func: Some(rate::linear),
            ..AnimateArgs::default()
        })
        .and_then(|b| b.shift([2.0, 0.0, 0.0]))
        .expect("chain records");

    let mut anim = prepare_animation(builder, &mut stage).expect("prepares");
    anim.begin(&mut stage).expect("begin");
    assert!(
        stage.get_center(mob)[0].abs() < 1e-6,
        "begin's zero interpolate leaves the source at the start"
    );
    anim.interpolate(&mut stage, 0.5);
    assert!((stage.get_center(mob)[0] - 1.0).abs() < 1e-5);
    anim.interpolate(&mut stage, 1.0);
    assert!((stage.get_center(mob)[0] - 2.0).abs() < 1e-5);
    anim.finish(&mut stage);
    assert!((stage.get_center(mob)[0] - 2.0).abs() < 1e-5);
}

#[test]
fn prepare_animation_accepts_animation_builder_and_built() {
    let mut stage = Stage::new();
    let mob = square(&mut stage);

    let (probe, _rows) = Probe::new(mob, AnimConfig::default());
    assert!(prepare_animation(probe, &mut stage).is_ok());

    let builder = mob.animate().shift([1.0, 0.0, 0.0]).expect("records");
    assert!(prepare_animation(builder, &mut stage).is_ok());

    let built = mob
        .animate()
        .shift([1.0, 0.0, 0.0])
        .and_then(|b| b.build(&mut stage))
        .expect("builds");
    assert!(prepare_animation(built, &mut stage).is_ok());
}

#[test]
fn path_arc_on_a_built_chain_is_a_named_error() {
    let mut stage = Stage::new();
    let mob = square(&mut stage);
    let built = mob
        .animate()
        .set_anim_args(AnimateArgs {
            path_arc: Some(0.5),
            ..AnimateArgs::default()
        })
        .and_then(|b| b.shift([1.0, 0.0, 0.0]))
        .and_then(|b| b.build(&mut stage))
        .expect("builds");
    assert_eq!(
        MethodAnimation::new(built).err(),
        Some(AnimError::PathArcUnsupported)
    );
}

#[test]
fn structurally_diverged_pair_is_a_named_error() {
    let mut stage = Stage::new();
    let mob = square(&mut stage);
    let built = mob
        .animate()
        .shift([1.0, 0.0, 0.0])
        .and_then(|b| b.build(&mut stage))
        .expect("builds");
    // Mutate the source's family after build: alignment is fm-cye's.
    let extra = square(&mut stage);
    stage.attach(mob, extra).expect("attach");

    let mut anim = MethodAnimation::new(built).expect("wraps");
    assert_eq!(anim.begin(&mut stage), Err(AnimError::UnalignedFamilies));
}

#[test]
fn stale_target_at_begin_is_a_named_error() {
    let mut stage = Stage::new();
    let mob = square(&mut stage);
    let built = mob
        .animate()
        .shift([1.0, 0.0, 0.0])
        .and_then(|b| b.build(&mut stage))
        .expect("builds");
    let target = built.target;
    let mut anim = MethodAnimation::new(built).expect("wraps");
    stage.delete(target).expect("deletes");
    assert_eq!(anim.begin(&mut stage), Err(AnimError::StaleHandle(target)));
}
