//! Composition acceptance (fm-hfe, §9.4): the interval algebra against the
//! pinned Reference's own arithmetic, the lifecycle each operator promises,
//! and the two BN-11 divergences asserted deliberately rather than absorbed.
//!
//! Fixtures are generated by `scripts/gen_composition_fixtures.py` from
//! `manimlib/animation/composition.py` at `3b1b/manim @ 6199a00d…`;
//! regenerate there, never hand-edit. Tolerance 1e-12 absolute (the
//! formulas agree to ~1e-15; the slack absorbs libm ulp differences only).

use std::cell::RefCell;
use std::rc::Rc;

use fmn_anim::animation::{AnimConfig, AnimError, AnimState, Animation, AnimationSignature};
use fmn_anim::{
    AnimationGroup, DEFAULT_LAGGED_START_LAG_RATIO, Interval, RateFunc, RationalFrameClock,
    Succession, build_timings, lagged_start, lagged_start_map, play_segment,
};
use fmn_core::rate;
use fmn_core::rng::RngRoot;
use fmn_mobject::{Mob, Mobject, Stage};

const TOL: f64 = 1e-12;

fn square(stage: &mut Stage) -> Mob {
    stage.add(Mobject::from_points(&[
        [-0.5, -0.5, 0.0],
        [0.5, -0.5, 0.0],
        [0.5, 0.5, 0.0],
        [-0.5, 0.5, 0.0],
    ]))
}

// ------------------------------------------------------- a probe animation

/// What a [`Probe`] records, in the order it happened.
#[derive(Debug, Clone, PartialEq)]
enum Event {
    Begin(&'static str),
    Alpha(&'static str, f64),
    Finish(&'static str),
    Removed(&'static str),
}

type Log = Rc<RefCell<Vec<Event>>>;

/// A leaf animation that records its lifecycle and every raw alpha its
/// container hands it. `interpolate` is overridden (rather than
/// `interpolate_submobject`) precisely because composition is about the
/// alpha a member *receives* — the member's own pipeline is tested by the
/// contract suite.
struct Probe {
    state: AnimState,
    log: Log,
    id: &'static str,
    pure: bool,
}

impl Probe {
    fn new(mobject: Mob, id: &'static str, run_time: f64, log: &Log) -> Self {
        Self {
            state: AnimState::new(
                mobject,
                AnimConfig {
                    run_time,
                    name: id.to_owned(),
                    ..AnimConfig::default()
                },
            ),
            log: Rc::clone(log),
            id,
            pure: true,
        }
    }

    fn boxed(mobject: Mob, id: &'static str, run_time: f64, log: &Log) -> Box<dyn Animation> {
        Box::new(Self::new(mobject, id, run_time, log))
    }

    fn unclassified(mut self) -> Self {
        self.pure = false;
        self
    }

    fn remover(mut self) -> Self {
        self.state.config.remover = true;
        self
    }
}

impl Animation for Probe {
    fn state(&self) -> &AnimState {
        &self.state
    }

    fn state_mut(&mut self) -> &mut AnimState {
        &mut self.state
    }

    fn setup(&mut self, _stage: &mut Stage) -> Result<(), AnimError> {
        self.log.borrow_mut().push(Event::Begin(self.id));
        Ok(())
    }

    fn teardown(&mut self, _stage: &mut Stage) {
        self.log.borrow_mut().push(Event::Finish(self.id));
    }

    fn interpolate(&mut self, _stage: &mut Stage, alpha: f64) {
        self.log.borrow_mut().push(Event::Alpha(self.id, alpha));
    }

    fn interpolate_submobject(&mut self, _stage: &mut Stage, _mobs: &[Mob], _sub_alpha: f64) {}

    fn clean_up_from_scene(&mut self, stage: &mut Stage) {
        if self.is_remover() {
            self.log.borrow_mut().push(Event::Removed(self.id));
            stage.remove_from_scene(self.state.mobject());
        }
    }

    fn effect_signature(&self) -> AnimationSignature {
        if self.pure {
            AnimationSignature::Pure
        } else {
            AnimationSignature::Unclassified
        }
    }
}

/// A leaf whose `begin` refuses — the just-in-time failure `Succession` has
/// no error channel for.
struct FailingProbe {
    state: AnimState,
}

impl Animation for FailingProbe {
    fn state(&self) -> &AnimState {
        &self.state
    }

    fn state_mut(&mut self) -> &mut AnimState {
        &mut self.state
    }

    fn setup(&mut self, _stage: &mut Stage) -> Result<(), AnimError> {
        Err(AnimError::EmptyMobject)
    }

    fn interpolate_submobject(&mut self, _stage: &mut Stage, _mobs: &[Mob], _sub_alpha: f64) {}
}

/// Every alpha the member `id` received, in order.
fn alphas_of(log: &Log, id: &str) -> Vec<f64> {
    log.borrow()
        .iter()
        .filter_map(|event| match event {
            Event::Alpha(who, alpha) if *who == id => Some(*alpha),
            _ => None,
        })
        .collect()
}

fn ids_of<'a>(log: &Log, pick: impl Fn(&Event) -> Option<&'a str> + Copy) -> Vec<String> {
    log.borrow()
        .iter()
        .filter_map(|event| pick(event).map(str::to_owned))
        .collect()
}

fn parse_list(field: &str) -> Vec<f64> {
    field
        .split(',')
        .map(|x| x.parse().expect("float"))
        .collect()
}

// -------------------------------------------------------- fixture corpora

#[test]
fn timings_match_the_reference_corpus() {
    for (lineno, line) in include_str!("../fixtures/composition_timings.txt")
        .lines()
        .enumerate()
    {
        let cols: Vec<&str> = line.split('\t').collect();
        let [lag, run_times, starts, ends, max_end] = cols[..] else {
            panic!("fixture line {lineno} malformed: {line:?}");
        };
        let run_times = parse_list(run_times);
        let got = build_timings(&run_times, lag.parse().expect("lag"));
        let want_starts = parse_list(starts);
        let want_ends = parse_list(ends);
        assert_eq!(got.len(), want_starts.len(), "line {lineno}");
        for (index, interval) in got.iter().enumerate() {
            assert!(
                (interval.start - want_starts[index]).abs() <= TOL
                    && (interval.end - want_ends[index]).abs() <= TOL,
                "line {lineno} member {index}: got {interval:?}, Reference says \
                 ({}, {})",
                want_starts[index],
                want_ends[index]
            );
        }
        let derived = got.iter().map(|i| i.end).fold(0.0_f64, f64::max);
        assert!((derived - max_end.parse::<f64>().expect("max end")).abs() <= TOL);
    }
}

#[test]
fn group_member_alphas_match_the_reference_corpus() {
    for (lineno, line) in include_str!("../fixtures/composition_alpha.txt")
        .lines()
        .enumerate()
    {
        let cols: Vec<&str> = line.split('\t').collect();
        let [lag, run_times, alpha, subs] = cols[..] else {
            panic!("fixture line {lineno} malformed: {line:?}");
        };
        let run_times = parse_list(run_times);
        let want = parse_list(subs);
        let alpha: f64 = alpha.parse().expect("alpha");

        let mut stage = Stage::new();
        let log: Log = Rc::new(RefCell::new(Vec::new()));
        let members: Vec<Box<dyn Animation>> = run_times
            .iter()
            .map(|&run_time| {
                let mob = square(&mut stage);
                Probe::boxed(mob, "m", run_time, &log)
            })
            .collect();
        let mut group =
            AnimationGroup::with_lag_ratio(&mut stage, members, lag.parse().expect("lag"))
                .expect("group builds");
        log.borrow_mut().clear();
        group.interpolate(&mut stage, alpha);

        let got = alphas_of(&log, "m");
        assert_eq!(got.len(), want.len(), "line {lineno}: member count");
        for (index, (&got, &want)) in got.iter().zip(&want).enumerate() {
            assert!(
                (got - want).abs() <= TOL,
                "line {lineno} member {index}: got {got:?}, Reference says {want:?}"
            );
        }
    }
}

#[test]
fn succession_honours_member_run_times_where_the_reference_does_not() {
    let mut divergences = 0;
    for (lineno, line) in include_str!("../fixtures/succession_active.txt")
        .lines()
        .enumerate()
    {
        let cols: Vec<&str> = line.split('\t').collect();
        let [run_times, alpha, ref_index, _ref_sub, our_index, our_sub] = cols[..] else {
            panic!("fixture line {lineno} malformed: {line:?}");
        };
        let run_times = parse_list(run_times);
        let alpha: f64 = alpha.parse().expect("alpha");
        let want_index: usize = our_index.parse().expect("index");
        let want_sub: f64 = our_sub.parse().expect("sub alpha");
        if ref_index != our_index {
            divergences += 1;
        }

        let mut stage = Stage::new();
        let log: Log = Rc::new(RefCell::new(Vec::new()));
        let members: Vec<Box<dyn Animation>> = run_times
            .iter()
            .map(|&run_time| {
                let mob = square(&mut stage);
                Probe::boxed(mob, "m", run_time, &log)
            })
            .collect();
        let mut succession = Succession::new(&mut stage, members).expect("succession builds");
        succession.begin(&mut stage).expect("begin succeeds");
        log.borrow_mut().clear();
        succession.interpolate(&mut stage, alpha);

        assert_eq!(
            succession.active_index(),
            want_index,
            "line {lineno}: active member (Reference's equal-share pick was {ref_index})"
        );
        let got = *alphas_of(&log, "m").last().expect("the active member ran");
        assert!(
            (got - want_sub).abs() <= TOL,
            "line {lineno}: active sub-alpha {got:?} != {want_sub:?}"
        );
    }
    // The corpus is only worth committing if it actually exercises the
    // divergence: the Reference's equal-share pick differs on unequal
    // run times, which is exactly the defect BN-11 names.
    assert!(
        divergences >= 20,
        "the corpus lost its divergent cases ({divergences})"
    );
}

// ---------------------------------------------------------- derived timing

#[test]
fn a_groups_run_time_derives_from_its_members() {
    let mut stage = Stage::new();
    let log: Log = Rc::new(RefCell::new(Vec::new()));
    let a = square(&mut stage);
    let b = square(&mut stage);
    let group = AnimationGroup::new(
        &mut stage,
        vec![
            Probe::boxed(a, "a", 3.0, &log),
            Probe::boxed(b, "b", 1.0, &log),
        ],
    )
    .expect("group builds");
    // lag_ratio 0 ⇒ both start at zero ⇒ the timeline is the longest member.
    assert_eq!(group.max_end_time(), 3.0);
    assert_eq!(group.get_run_time(), 3.0);
    assert_eq!(
        group.timings(),
        [
            Interval {
                start: 0.0,
                end: 3.0
            },
            Interval {
                start: 0.0,
                end: 1.0
            }
        ]
    );
}

#[test]
fn a_successions_run_time_is_the_sum_of_its_members() {
    let mut stage = Stage::new();
    let log: Log = Rc::new(RefCell::new(Vec::new()));
    let a = square(&mut stage);
    let b = square(&mut stage);
    let succession = Succession::new(
        &mut stage,
        vec![
            Probe::boxed(a, "a", 3.0, &log),
            Probe::boxed(b, "b", 1.0, &log),
        ],
    )
    .expect("succession builds");
    assert_eq!(succession.max_end_time(), 4.0);
    assert_eq!(succession.get_run_time(), 4.0);
}

#[test]
fn a_run_time_override_rescales_without_touching_the_timeline() {
    let mut stage = Stage::new();
    let log: Log = Rc::new(RefCell::new(Vec::new()));
    let a = square(&mut stage);
    let b = square(&mut stage);
    let mut group = AnimationGroup::with_lag_ratio(
        &mut stage,
        vec![
            Probe::boxed(a, "a", 2.0, &log),
            Probe::boxed(b, "b", 2.0, &log),
        ],
        1.0,
    )
    .expect("group builds")
    .with_run_time(10.0);
    assert_eq!(group.get_run_time(), 10.0);
    assert_eq!(group.max_end_time(), 4.0, "the internal timeline is intact");
    // Half the composition's alpha is still half its internal timeline: the
    // first member done, the second starting.
    group.interpolate(&mut stage, 0.5);
    assert_eq!(alphas_of(&log, "a").last().copied(), Some(1.0));
    assert_eq!(alphas_of(&log, "b").last().copied(), Some(0.0));
}

#[test]
fn lag_ratio_spreads_member_starts() {
    let mut stage = Stage::new();
    let log: Log = Rc::new(RefCell::new(Vec::new()));
    let mobs: Vec<Mob> = (0..3).map(|_| square(&mut stage)).collect();
    let members: Vec<Box<dyn Animation>> = mobs
        .iter()
        .map(|&m| Probe::boxed(m, "m", 1.0, &log))
        .collect();
    let group = lagged_start(&mut stage, members).expect("lagged start builds");
    let starts: Vec<f64> = group.timings().iter().map(|i| i.start).collect();
    assert!((starts[1] - DEFAULT_LAGGED_START_LAG_RATIO).abs() <= TOL);
    assert!((starts[2] - 2.0 * DEFAULT_LAGGED_START_LAG_RATIO).abs() <= TOL);
    assert_eq!(
        group.max_end_time(),
        1.0 + 2.0 * DEFAULT_LAGGED_START_LAG_RATIO
    );
}

#[test]
fn lagged_start_map_builds_one_animation_per_submobject() {
    let mut stage = Stage::new();
    let log: Log = Rc::new(RefCell::new(Vec::new()));
    let parent = stage.add(Mobject::new());
    for _ in 0..4 {
        let child = square(&mut stage);
        stage.attach(parent, child).expect("attach");
    }
    let group = lagged_start_map(&mut stage, parent, |_stage, submob| {
        Ok(Probe::boxed(submob, "m", 1.0, &log))
    })
    .expect("map builds");
    assert_eq!(group.animations().len(), 4);
    assert_eq!(group.group(), parent, "the caller's group is animated");
    assert_eq!(
        group.get_run_time(),
        2.0,
        "the Reference's run_time default"
    );
}

// ------------------------------------------------- the divergences (BN-11)

#[test]
fn a_group_rate_func_shapes_the_composition() {
    let mut stage = Stage::new();
    let log: Log = Rc::new(RefCell::new(Vec::new()));
    let a = square(&mut stage);
    let mut group = AnimationGroup::new(&mut stage, vec![Probe::boxed(a, "a", 1.0, &log)])
        .expect("group builds")
        .with_rate_func(RateFunc::Base(rate::there_and_back));
    for alpha in [0.0, 0.25, 0.5, 0.75, 1.0] {
        group.interpolate(&mut stage, alpha);
    }
    let got = alphas_of(&log, "a");
    // there_and_back peaks at the middle and returns: a curve the
    // Reference's group would have ignored entirely.
    assert!(got[0].abs() <= TOL);
    assert!((got[2] - 1.0).abs() <= TOL, "peak at the midpoint: {got:?}");
    assert!(got[4].abs() <= TOL, "back where it started: {got:?}");
    assert!(got[1] > got[0] && got[3] < got[2]);
}

#[test]
fn the_default_group_rate_func_is_the_identity() {
    // The corollary that keeps the common case bit-for-bit the Reference's:
    // members own their easing, so a group's default curve must be linear.
    let mut stage = Stage::new();
    let log: Log = Rc::new(RefCell::new(Vec::new()));
    let a = square(&mut stage);
    let mut group = AnimationGroup::new(&mut stage, vec![Probe::boxed(a, "a", 1.0, &log)])
        .expect("group builds");
    log.borrow_mut().clear();
    for alpha in [0.1, 0.4, 0.9] {
        group.interpolate(&mut stage, alpha);
    }
    assert_eq!(alphas_of(&log, "a"), vec![0.1, 0.4, 0.9]);
}

#[test]
fn a_group_time_span_re_windows_the_composition() {
    let mut stage = Stage::new();
    let log: Log = Rc::new(RefCell::new(Vec::new()));
    let a = square(&mut stage);
    let mut group = AnimationGroup::new(&mut stage, vec![Probe::boxed(a, "a", 1.0, &log)])
        .expect("group builds");
    group.state_mut().config.time_span = Some((0.5, 1.0));
    group.begin(&mut stage).expect("begin succeeds");
    log.borrow_mut().clear();
    // The composition idles through the first half of its run time, then
    // runs its whole arc in the window — the Reference ignores the span.
    for alpha in [0.25, 0.5, 0.75, 1.0] {
        group.interpolate(&mut stage, alpha);
    }
    let got = alphas_of(&log, "a");
    assert!(got[0].abs() <= TOL, "still idle at 0.25: {got:?}");
    assert!(got[1].abs() <= TOL, "the window opens at 0.5: {got:?}");
    assert!((got[2] - 0.5).abs() <= TOL, "halfway through it: {got:?}");
    assert!((got[3] - 1.0).abs() <= TOL);
}

#[test]
fn nested_groups_compose_with_independent_rate_funcs() {
    let mut stage = Stage::new();
    let log: Log = Rc::new(RefCell::new(Vec::new()));
    let a = square(&mut stage);
    let b = square(&mut stage);
    let inner = AnimationGroup::with_lag_ratio(
        &mut stage,
        vec![
            Probe::boxed(a, "a", 1.0, &log),
            Probe::boxed(b, "b", 1.0, &log),
        ],
        1.0,
    )
    .expect("inner builds")
    .with_rate_func(RateFunc::linear());
    let c = square(&mut stage);
    let mut outer = AnimationGroup::new(
        &mut stage,
        vec![Box::new(inner), Probe::boxed(c, "c", 2.0, &log)],
    )
    .expect("outer builds")
    .with_rate_func(RateFunc::Base(rate::smooth));

    assert_eq!(outer.max_end_time(), 2.0, "the inner group's run time is 2");
    log.borrow_mut().clear();
    outer.interpolate(&mut stage, 0.5);
    // smooth(0.5) == 0.5, so the outer curve is transparent at the midpoint:
    // the inner group is halfway through its own successive timeline (member
    // a finished, member b about to start) and c is halfway through its own.
    assert_eq!(alphas_of(&log, "a").last().copied(), Some(1.0));
    assert_eq!(alphas_of(&log, "b").last().copied(), Some(0.0));
    assert_eq!(alphas_of(&log, "c").last().copied(), Some(0.5));

    log.borrow_mut().clear();
    outer.interpolate(&mut stage, 0.25);
    // smooth(0.25) ≈ 0.1035: the outer easing reaches *through* the inner
    // group, which is the property nesting has to have.
    let inner_a = alphas_of(&log, "a").last().copied().expect("a ran");
    let outer_c = alphas_of(&log, "c").last().copied().expect("c ran");
    assert!((outer_c - rate::smooth(0.25)).abs() <= TOL);
    assert!(
        (inner_a - 2.0 * outer_c).abs() <= TOL,
        "a spans the first half"
    );
}

#[test]
fn succession_walks_the_members_a_coarse_step_would_skip() {
    // Three members, one frame: the Reference jumps straight to the last and
    // the middle one never begins or finishes. Ours runs every member in
    // order — their effects are not optional.
    let mut stage = Stage::new();
    let log: Log = Rc::new(RefCell::new(Vec::new()));
    let mobs: Vec<Mob> = (0..3).map(|_| square(&mut stage)).collect();
    let members: Vec<Box<dyn Animation>> = vec![
        Probe::boxed(mobs[0], "a", 1.0, &log),
        Probe::boxed(mobs[1], "b", 1.0, &log),
        Probe::boxed(mobs[2], "c", 1.0, &log),
    ];
    let mut succession = Succession::new(&mut stage, members).expect("succession builds");
    succession.begin(&mut stage).expect("begin succeeds");
    succession.interpolate(&mut stage, 1.0);

    let begins = ids_of(&log, |event| match event {
        Event::Begin(id) => Some(*id),
        _ => None,
    });
    let finishes = ids_of(&log, |event| match event {
        Event::Finish(id) => Some(*id),
        _ => None,
    });
    assert_eq!(begins, ["a", "b", "c"], "every member begins, in order");
    assert_eq!(finishes, ["a", "b"], "the passed members finish, in order");
    assert_eq!(succession.active_index(), 2);
}

// ------------------------------------------------------------- lifecycle

#[test]
fn a_group_begins_every_member_and_a_succession_begins_one() {
    let mut stage = Stage::new();
    let log: Log = Rc::new(RefCell::new(Vec::new()));
    let a = square(&mut stage);
    let b = square(&mut stage);
    let mut group = AnimationGroup::new(
        &mut stage,
        vec![
            Probe::boxed(a, "a", 1.0, &log),
            Probe::boxed(b, "b", 1.0, &log),
        ],
    )
    .expect("group builds");
    group.begin(&mut stage).expect("begin succeeds");
    assert_eq!(
        ids_of(&log, |event| match event {
            Event::Begin(id) => Some(*id),
            _ => None,
        }),
        ["a", "b"]
    );

    let log2: Log = Rc::new(RefCell::new(Vec::new()));
    let c = square(&mut stage);
    let d = square(&mut stage);
    let mut succession = Succession::new(
        &mut stage,
        vec![
            Probe::boxed(c, "c", 1.0, &log2),
            Probe::boxed(d, "d", 1.0, &log2),
        ],
    )
    .expect("succession builds");
    succession.begin(&mut stage).expect("begin succeeds");
    assert_eq!(
        ids_of(&log2, |event| match event {
            Event::Begin(id) => Some(*id),
            _ => None,
        }),
        ["c"],
        "the second member begins only when the timeline reaches it"
    );
}

#[test]
fn the_container_marks_its_family_animating() {
    let mut stage = Stage::new();
    let log: Log = Rc::new(RefCell::new(Vec::new()));
    let a = square(&mut stage);
    let mut group = AnimationGroup::new(&mut stage, vec![Probe::boxed(a, "a", 1.0, &log)])
        .expect("group builds");
    let container = group.group();
    assert!(!stage.is_animating(container));
    group.begin(&mut stage).expect("begin succeeds");
    assert!(stage.is_animating(container));
    assert!(stage.is_animating(a), "and the member it contains");
    group.finish(&mut stage);
    assert!(!stage.is_animating(container));
    assert!(!stage.is_animating(a));
}

#[test]
fn the_container_family_holds_every_distinct_member_mobject() {
    let mut stage = Stage::new();
    let log: Log = Rc::new(RefCell::new(Vec::new()));
    let a = square(&mut stage);
    let b = square(&mut stage);
    // Two animations on ONE mobject plus a second mobject: the container
    // holds each distinct mobject once (`remove_list_redundancies`).
    let group = AnimationGroup::new(
        &mut stage,
        vec![
            Probe::boxed(a, "a1", 1.0, &log),
            Probe::boxed(a, "a2", 1.0, &log),
            Probe::boxed(b, "b", 1.0, &log),
        ],
    )
    .expect("group builds");
    let children = stage
        .get(group.group())
        .expect("container is live")
        .submobjects()
        .to_vec();
    assert_eq!(children, [a, b]);
}

#[test]
fn a_remover_inside_a_group_still_leaves_the_scene() {
    let mut stage = Stage::new();
    let log: Log = Rc::new(RefCell::new(Vec::new()));
    let staying = square(&mut stage);
    let going = square(&mut stage);
    stage.add_to_scene(staying).expect("root");
    stage.add_to_scene(going).expect("root");
    let group = AnimationGroup::new(
        &mut stage,
        vec![
            Probe::boxed(staying, "staying", 1.0, &log),
            Box::new(Probe::new(going, "going", 1.0, &log).remover()),
        ],
    )
    .expect("group builds");

    let mut clock = RationalFrameClock::new(30).expect("clock");
    let rng = RngRoot::from_seed(7);
    let mut animations: Vec<Box<dyn Animation>> = vec![Box::new(group)];
    play_segment(
        &mut stage,
        &mut clock,
        &rng,
        &mut animations,
        false,
        &mut |_packet| {},
    )
    .expect("segment plays");

    assert!(stage.roots().contains(&staying));
    assert!(
        !stage.roots().contains(&going),
        "the group delegated removal to its member"
    );
    assert!(log.borrow().contains(&Event::Removed("going")));
}

#[test]
fn purity_is_the_conjunction_of_the_members() {
    let mut stage = Stage::new();
    let log: Log = Rc::new(RefCell::new(Vec::new()));
    let a = square(&mut stage);
    let b = square(&mut stage);
    let pure = AnimationGroup::new(
        &mut stage,
        vec![
            Probe::boxed(a, "a", 1.0, &log),
            Probe::boxed(b, "b", 1.0, &log),
        ],
    )
    .expect("group builds");
    assert_eq!(pure.effect_signature(), AnimationSignature::Pure);

    let c = square(&mut stage);
    let d = square(&mut stage);
    let mixed = AnimationGroup::new(
        &mut stage,
        vec![
            Probe::boxed(c, "c", 1.0, &log),
            Box::new(Probe::new(d, "d", 1.0, &log).unclassified()),
        ],
    )
    .expect("group builds");
    assert_eq!(
        mixed.effect_signature(),
        AnimationSignature::Unclassified,
        "one unclassified member demotes the composition (R20)"
    );
}

#[test]
fn a_pure_composition_lets_its_segment_classify_pure() {
    let mut stage = Stage::new();
    let log: Log = Rc::new(RefCell::new(Vec::new()));
    let a = square(&mut stage);
    let b = square(&mut stage);
    let group = AnimationGroup::with_lag_ratio(
        &mut stage,
        vec![
            Probe::boxed(a, "a", 1.0, &log),
            Probe::boxed(b, "b", 1.0, &log),
        ],
        0.5,
    )
    .expect("group builds");
    let mut clock = RationalFrameClock::new(30).expect("clock");
    let rng = RngRoot::from_seed(11);
    let mut animations: Vec<Box<dyn Animation>> = vec![Box::new(group)];
    let report = play_segment(
        &mut stage,
        &mut clock,
        &rng,
        &mut animations,
        false,
        &mut |_packet| {},
    )
    .expect("segment plays");
    assert!(report.purity.is_pure());
    assert!(report.begin_state.is_some());
}

// ---------------------------------------------------------- named refusals

#[test]
fn an_empty_composition_is_refused_by_name() {
    let mut stage = Stage::new();
    assert_eq!(
        AnimationGroup::new(&mut stage, Vec::new()).err(),
        Some(AnimError::EmptyComposition)
    );
    assert_eq!(
        Succession::new(&mut stage, Vec::new()).err(),
        Some(AnimError::EmptyComposition)
    );
}

#[test]
fn a_just_in_time_begin_failure_surfaces_from_the_segment() {
    let mut stage = Stage::new();
    let log: Log = Rc::new(RefCell::new(Vec::new()));
    let a = square(&mut stage);
    let b = square(&mut stage);
    let succession = Succession::new(
        &mut stage,
        vec![
            Probe::boxed(a, "a", 1.0, &log),
            Box::new(FailingProbe {
                state: AnimState::new(b, AnimConfig::default()),
            }),
        ],
    )
    .expect("succession builds");

    let mut clock = RationalFrameClock::new(30).expect("clock");
    let rng = RngRoot::from_seed(3);
    let mut animations: Vec<Box<dyn Animation>> = vec![Box::new(succession)];
    let err = play_segment(
        &mut stage,
        &mut clock,
        &rng,
        &mut animations,
        false,
        &mut |_packet| {},
    )
    .expect_err("the second member's begin refuses");
    assert_eq!(err, AnimError::EmptyMobject);
}

#[test]
fn a_hollow_group_time_span_is_refused_at_begin() {
    let mut stage = Stage::new();
    let log: Log = Rc::new(RefCell::new(Vec::new()));
    let a = square(&mut stage);
    let mut group = AnimationGroup::new(&mut stage, vec![Probe::boxed(a, "a", 1.0, &log)])
        .expect("group builds");
    group.state_mut().config.time_span = Some((1.0, 1.0));
    assert_eq!(
        group.begin(&mut stage).err(),
        Some(AnimError::InvalidTimeSpan {
            start: 1.0,
            end: 1.0
        })
    );
}
