//! Owned deterministic elementary functions: bit-reproducible transcendentals for the certified path (§6.6, D-17).
//!
//! `std`'s transcendentals defer to platform libm and differ across
//! glibc/macOS/WASM; this engine is transcendental-dense (arc construction,
//! per-vertex atan2 joints, rate functions, glow falloffs, tanh
//! normalization, Euler conversions). fmn-dmath is the owned,
//! fixed-implementation layer: classical FDLIBM-style range reduction and
//! fixed-coefficient, fixed-order minimax polynomials, bit-identical on
//! every certified target, locked by the committed vector files under
//! `vectors/` (generated by `scripts/gen_dmath_vectors.py` from mpmath
//! ground truth; regenerate, never hand-edit).
//!
//! **Accuracy bounds** are documented per function and measured against
//! correctly-rounded ground truth by `tests/vectors.rs`. `sqrt` is the one
//! deliberate delegation: IEEE 754 requires correct rounding, so
//! `f64::sqrt`/`f32::sqrt` are already bit-identical everywhere.
//!
//! **The mode seam** (§6.6): `standard` mode may use fast paths;
//! `certified` uses fmn-dmath exclusively. The seam is the
//! [`Transcendentals`] function table, chosen once at engine construction
//! — never a scattered `cfg`.
//!
//! **SIMD posture** (§17.3): every kernel is a fixed-coefficient,
//! fixed-order polynomial over range reduction, so later `std::simd`
//! vectorization can reproduce the scalar path bit-for-bit lane by lane.
//! Nothing here is vectorized yet; nothing here precludes it.
//!
//! **f32 entry points** compute through the f64 implementations and round
//! once at the end ([`f32api`]). That is deterministic (the f64 layer is),
//! at least as accurate as a native-f32 polynomial, and half the surface
//! to audit. The double-rounding caveat is documented on the module.
#![forbid(unsafe_code)]

mod bits;
mod cbrt;
mod exp_log;
pub mod f32api;
mod hyper;
mod inverse_trig;
mod pow;
mod rem_pio2;
mod trig;

pub use cbrt::cbrt;
pub use exp_log::{exp, expm1, ln, log2};
pub use hyper::{cosh, sinh, tanh};
pub use inverse_trig::{acos, asin, atan, atan2};
pub use pow::pow;
pub use trig::{cos, sin, tan};

/// `sqrt` — delegated to the hardware instruction on purpose: IEEE 754
/// requires correct rounding, so it is bit-identical on every certified
/// target already. Max error: 0.5 ulp (correctly rounded).
#[must_use]
pub fn sqrt(x: f64) -> f64 {
    x.sqrt()
}

/// The standard/certified seam (§6.6): one function table, chosen at
/// engine construction. `certified` construction takes [`CERTIFIED`];
/// `standard` may take [`FAST`]. Call sites hold the table, never a cfg.
#[derive(Clone, Copy)]
pub struct Transcendentals {
    pub sin: fn(f64) -> f64,
    pub cos: fn(f64) -> f64,
    pub tan: fn(f64) -> f64,
    pub asin: fn(f64) -> f64,
    pub acos: fn(f64) -> f64,
    pub atan: fn(f64) -> f64,
    pub atan2: fn(f64, f64) -> f64,
    pub exp: fn(f64) -> f64,
    pub ln: fn(f64) -> f64,
    pub log2: fn(f64) -> f64,
    pub pow: fn(f64, f64) -> f64,
    pub sqrt: fn(f64) -> f64,
    pub cbrt: fn(f64) -> f64,
    pub sinh: fn(f64) -> f64,
    pub cosh: fn(f64) -> f64,
    pub tanh: fn(f64) -> f64,
}

/// The certified table: fmn-dmath exclusively. This is the definition the
/// certified engine's bits are a function of.
pub const CERTIFIED: Transcendentals = Transcendentals {
    sin,
    cos,
    tan,
    asin,
    acos,
    atan,
    atan2,
    exp,
    ln,
    log2,
    pow,
    sqrt,
    cbrt,
    sinh,
    cosh,
    tanh,
};

/// The fast table: platform libm via `std`. Deterministic per
/// build/platform only — `standard` mode, always labeled, never certified.
pub const FAST: Transcendentals = Transcendentals {
    sin: f64::sin,
    cos: f64::cos,
    tan: f64::tan,
    asin: f64::asin,
    acos: f64::acos,
    atan: f64::atan,
    atan2: f64::atan2,
    exp: f64::exp,
    ln: f64::ln,
    log2: f64::log2,
    pow: f64::powf,
    sqrt,
    cbrt: f64::cbrt,
    sinh: f64::sinh,
    cosh: f64::cosh,
    tanh: f64::tanh,
};

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn seam_tables_are_swappable_at_construction() {
        // An "engine" holding its table — the seam pattern call sites use.
        struct Engine {
            math: Transcendentals,
        }
        let certified = Engine { math: CERTIFIED };
        let fast = Engine { math: FAST };
        // Both compute; the certified one is the pinned definition.
        let x = 1.234_567_89_f64;
        let c = (certified.math.sin)(x);
        let f = (fast.math.sin)(x);
        assert!((c - f).abs() < 1e-15);
        assert_eq!(c.to_bits(), sin(x).to_bits());
    }

    #[test]
    fn sqrt_is_correctly_rounded_delegation() {
        assert_eq!(sqrt(2.0).to_bits(), 2.0_f64.sqrt().to_bits());
        assert!(sqrt(-1.0).is_nan());
        assert_eq!(sqrt(0.0).to_bits(), 0.0_f64.to_bits());
    }
}
