//! Owned deterministic elementary functions: bit-reproducible transcendentals for the certified path (§6.6, D-17).
//!
//! `std`'s transcendentals defer to platform libm and differ across
//! glibc/macOS/WASM; this engine is transcendental-dense (arc construction,
//! per-vertex atan2 joints, rate functions, glow falloffs, tanh
//! normalization, Euler conversions). fmn-dmath is the owned,
//! fixed-implementation layer: classical FDLIBM-style range reduction and
//! fixed-coefficient, fixed-order minimax polynomials, bit-identical on
//! every certified target, locked by the committed vector files under
//! `vectors/` (generated by `scripts/gen_dmath_vectors.py` from mpmath
//! ground truth; regenerate, never hand-edit).
//!
//! **Accuracy bounds** are documented per function and measured against
//! correctly-rounded ground truth by `tests/vectors.rs`. `sqrt` is the one
//! deliberate delegation: IEEE 754 requires correct rounding, so
//! `f64::sqrt`/`f32::sqrt` are already bit-identical everywhere.
//!
//! **The mode seam** (§6.6): `standard` mode may use fast paths;
//! `certified` uses fmn-dmath exclusively. The seam is the
//! [`Transcendentals`] function table, chosen once at engine construction
//! — never a scattered `cfg`.
//!
//! **SIMD posture** (§17.3): every retained bulk kernel groups independent
//! inputs in `std::simd` lanes while reproducing the scalar operation order
//! bit-for-bit within each lane. No horizontal reduction may make the result
//! depend on the build tier's lane count.
//!
//! **f32 entry points** compute through the f64 implementations and round
//! once at the end ([`f32api`]). That is deterministic (the f64 layer is),
//! at least as accurate as a native-f32 polynomial, and half the surface
//! to audit. The double-rounding caveat is documented on the module.
#![feature(portable_simd)]
#![cfg_attr(test, feature(test))]
#![forbid(unsafe_code)]

#[cfg(test)]
extern crate test;

mod bits;
mod cbrt;
mod exp_log;
pub mod f32api;
mod hyper;
mod inverse_trig;
mod pow;
mod rem_pio2;
mod trig;

pub use cbrt::{cbrt, cbrt_slice};
pub use exp_log::{exp, exp_slice, expm1, expm1_slice, ln, ln_slice, log2, log2_slice};
pub use hyper::{cosh, cosh_slice, sinh, sinh_slice, tanh, tanh_slice};
pub use inverse_trig::{acos, asin, atan, atan2};
pub use pow::pow;
pub use trig::{cos, sin, tan};

/// `sqrt` — delegated to the hardware instruction on purpose: IEEE 754
/// requires correct rounding, so it is bit-identical on every certified
/// target already. Max error: 0.5 ulp (correctly rounded).
#[must_use]
pub fn sqrt(x: f64) -> f64 {
    x.sqrt()
}

/// Apply the certified [`sqrt`] definition to a slice in place.
///
/// Independent values are grouped into build-tier SIMD lanes; every output
/// is bit-identical to calling [`sqrt`] on that element. The scalar tail
/// preserves the same definition for lengths not divisible by the lane
/// count.
pub fn sqrt_slice(values: &mut [f64]) {
    use std::simd::StdFloat as _;

    let mut index = 0;
    while index + bits::SIMD_LANES <= values.len() {
        let roots = bits::F64x::from_slice(&values[index..]).sqrt();
        roots.copy_to_slice(&mut values[index..index + bits::SIMD_LANES]);
        index += bits::SIMD_LANES;
    }
    for value in &mut values[index..] {
        *value = sqrt(*value);
    }
}

/// The standard/certified seam (§6.6): one function table, chosen at
/// engine construction. `certified` construction takes [`CERTIFIED`];
/// `standard` may take [`FAST`]. Call sites hold the table, never a cfg.
#[derive(Clone, Copy)]
pub struct Transcendentals {
    pub sin: fn(f64) -> f64,
    pub cos: fn(f64) -> f64,
    pub tan: fn(f64) -> f64,
    pub asin: fn(f64) -> f64,
    pub acos: fn(f64) -> f64,
    pub atan: fn(f64) -> f64,
    pub atan2: fn(f64, f64) -> f64,
    pub exp: fn(f64) -> f64,
    pub ln: fn(f64) -> f64,
    pub log2: fn(f64) -> f64,
    pub pow: fn(f64, f64) -> f64,
    pub sqrt: fn(f64) -> f64,
    pub cbrt: fn(f64) -> f64,
    pub sinh: fn(f64) -> f64,
    pub cosh: fn(f64) -> f64,
    pub tanh: fn(f64) -> f64,
}

/// The certified table: fmn-dmath exclusively. This is the definition the
/// certified engine's bits are a function of.
pub const CERTIFIED: Transcendentals = Transcendentals {
    sin,
    cos,
    tan,
    asin,
    acos,
    atan,
    atan2,
    exp,
    ln,
    log2,
    pow,
    sqrt,
    cbrt,
    sinh,
    cosh,
    tanh,
};

/// The fast table: platform libm via `std`. Deterministic per
/// build/platform only — `standard` mode, always labeled, never certified.
pub const FAST: Transcendentals = Transcendentals {
    sin: f64::sin,
    cos: f64::cos,
    tan: f64::tan,
    asin: f64::asin,
    acos: f64::acos,
    atan: f64::atan,
    atan2: f64::atan2,
    exp: f64::exp,
    ln: f64::ln,
    log2: f64::log2,
    pow: f64::powf,
    sqrt,
    cbrt: f64::cbrt,
    sinh: f64::sinh,
    cosh: f64::cosh,
    tanh: f64::tanh,
};

#[cfg(test)]
mod tests {
    use super::*;
    use test::{Bencher, black_box};

    #[test]
    fn seam_tables_are_swappable_at_construction() {
        // An "engine" holding its table — the seam pattern call sites use.
        struct Engine {
            math: Transcendentals,
        }
        let certified = Engine { math: CERTIFIED };
        let fast = Engine { math: FAST };
        // Both compute; the certified one is the pinned definition.
        let x = 1.234_567_89_f64;
        let c = (certified.math.sin)(x);
        let f = (fast.math.sin)(x);
        assert!((c - f).abs() < 1e-15);
        assert_eq!(c.to_bits(), sin(x).to_bits());
    }

    #[test]
    fn sqrt_is_correctly_rounded_delegation() {
        assert_eq!(sqrt(2.0).to_bits(), 2.0_f64.sqrt().to_bits());
        assert!(sqrt(-1.0).is_nan());
        assert_eq!(sqrt(0.0).to_bits(), 0.0_f64.to_bits());
    }

    fn bit_corpus() -> Vec<f64> {
        let mut values = vec![
            0.0,
            -0.0,
            f64::MIN_POSITIVE,
            -f64::MIN_POSITIVE,
            f64::from_bits(1),
            f64::from_bits((1_u64 << 63) | 1),
            f64::MAX,
            -f64::MAX,
            f64::INFINITY,
            f64::NEG_INFINITY,
            f64::NAN,
            f64::from_bits(0x7ff8_1234_5678_9abc),
            f64::from_bits(0xfff8_1234_5678_9abc),
        ];
        let mut state = 0x243f_6a88_85a3_08d3_u64;
        for _ in 0..65_537 {
            state = state
                .wrapping_mul(6_364_136_223_846_793_005)
                .wrapping_add(1_442_695_040_888_963_407);
            values.push(f64::from_bits(state));
        }
        values
    }

    fn normal_corpus(low: f64, high: f64) -> Vec<f64> {
        let mut values = bench_inputs(low, high);
        values.extend([
            f64::MIN_POSITIVE,
            1.0,
            2.0,
            f64::MAX,
            f64::from_bits(0x3fe6_a09e_667f_3bcc),
        ]);
        values
    }

    fn boundary_corpus(points: &[f64]) -> Vec<f64> {
        let mut values = Vec::with_capacity(points.len() * 3 * bits::SIMD_LANES);
        for point in points {
            for point_bits in [
                point.to_bits().wrapping_sub(1),
                point.to_bits(),
                point.to_bits().wrapping_add(1),
            ] {
                for _ in 0..bits::SIMD_LANES {
                    values.push(f64::from_bits(point_bits));
                }
            }
        }
        values
    }

    fn assert_slice_bits(name: &str, scalar: fn(f64) -> f64, slice: fn(&mut [f64]), input: &[f64]) {
        let expected: Vec<_> = input.iter().copied().map(scalar).collect();
        let mut actual = input.to_vec();
        slice(&mut actual);
        for (index, (&expected, &actual)) in expected.iter().zip(&actual).enumerate() {
            assert_eq!(
                actual.to_bits(),
                expected.to_bits(),
                "{name} lane {index}: input={:#018x}, expected={:#018x}, actual={:#018x}",
                input[index].to_bits(),
                expected.to_bits(),
                actual.to_bits()
            );
        }
    }

    #[test]
    fn simd_slices_are_the_scalar_definition_lane_for_lane() {
        let arbitrary = bit_corpus();
        assert_slice_bits("sqrt arbitrary", sqrt, sqrt_slice, &arbitrary);
        assert_slice_bits("cbrt arbitrary", cbrt, cbrt_slice, &arbitrary);
        assert_slice_bits("exp arbitrary", exp, exp_slice, &arbitrary);
        assert_slice_bits("expm1 arbitrary", expm1, expm1_slice, &arbitrary);
        assert_slice_bits("ln arbitrary", ln, ln_slice, &arbitrary);
        assert_slice_bits("log2 arbitrary", log2, log2_slice, &arbitrary);
        assert_slice_bits("sinh arbitrary", sinh, sinh_slice, &arbitrary);
        assert_slice_bits("cosh arbitrary", cosh, cosh_slice, &arbitrary);
        assert_slice_bits("tanh arbitrary", tanh, tanh_slice, &arbitrary);

        assert_slice_bits(
            "sqrt boundaries",
            sqrt,
            sqrt_slice,
            &boundary_corpus(&[
                0.0,
                -0.0,
                f64::MIN_POSITIVE,
                -f64::MIN_POSITIVE,
                f64::INFINITY,
                f64::NEG_INFINITY,
                f64::NAN,
            ]),
        );
        assert_slice_bits(
            "cbrt boundaries",
            cbrt,
            cbrt_slice,
            &boundary_corpus(&[f64::MIN_POSITIVE, -f64::MIN_POSITIVE, f64::MAX, -f64::MAX]),
        );
        assert_slice_bits(
            "exp boundaries",
            exp,
            exp_slice,
            &boundary_corpus(&[
                f64::from_bits(0x3e30_0000_0000_0000),
                -f64::from_bits(0x3e30_0000_0000_0000),
                -708.0,
                709.0,
            ]),
        );
        assert_slice_bits(
            "expm1 boundaries",
            expm1,
            expm1_slice,
            &boundary_corpus(&[
                f64::from_bits(0x3c90_0000_0000_0000),
                -f64::from_bits(0x3c90_0000_0000_0000),
                f64::from_bits(0x4043_687a_0000_0000),
                -f64::from_bits(0x4043_687a_0000_0000),
            ]),
        );
        let logarithm_boundaries = boundary_corpus(&[
            f64::MIN_POSITIVE,
            1.0,
            f64::from_bits(0x3fe6_a09e_667f_3bcc),
            f64::INFINITY,
        ]);
        assert_slice_bits("ln boundaries", ln, ln_slice, &logarithm_boundaries);
        assert_slice_bits("log2 boundaries", log2, log2_slice, &logarithm_boundaries);
        assert_slice_bits(
            "sinh boundaries",
            sinh,
            sinh_slice,
            &boundary_corpus(&[
                f64::from_bits(0x3e30_0000_0000_0000),
                -f64::from_bits(0x3e30_0000_0000_0000),
                1.0,
                -1.0,
                22.0,
                -22.0,
            ]),
        );
        assert_slice_bits(
            "cosh boundaries",
            cosh,
            cosh_slice,
            &boundary_corpus(&[
                f64::from_bits(0x3c90_0000_0000_0000),
                -f64::from_bits(0x3c90_0000_0000_0000),
                f64::from_bits(0x3fd6_2e43_0000_0000),
                -f64::from_bits(0x3fd6_2e43_0000_0000),
                22.0,
                -22.0,
            ]),
        );
        assert_slice_bits(
            "tanh boundaries",
            tanh,
            tanh_slice,
            &boundary_corpus(&[
                f64::from_bits(0x3c80_0000_0000_0000),
                -f64::from_bits(0x3c80_0000_0000_0000),
                1.0,
                -1.0,
                22.0,
                -22.0,
            ]),
        );

        assert_slice_bits(
            "cbrt normal",
            cbrt,
            cbrt_slice,
            &normal_corpus(-1_000_000.0, 1_000_000.0),
        );
        assert_slice_bits("exp direct", exp, exp_slice, &normal_corpus(-700.0, 700.0));
        assert_slice_bits(
            "expm1 ordinary",
            expm1,
            expm1_slice,
            &normal_corpus(-38.0, 38.0),
        );
        assert_slice_bits(
            "ln normal",
            ln,
            ln_slice,
            &normal_corpus(f64::MIN_POSITIVE, 1.0e300),
        );
        assert_slice_bits(
            "log2 normal",
            log2,
            log2_slice,
            &normal_corpus(f64::MIN_POSITIVE, 1.0e300),
        );
        assert_slice_bits(
            "sinh ordinary",
            sinh,
            sinh_slice,
            &normal_corpus(-10.0, 10.0),
        );
        assert_slice_bits(
            "cosh ordinary",
            cosh,
            cosh_slice,
            &normal_corpus(-10.0, 10.0),
        );
        assert_slice_bits(
            "tanh ordinary",
            tanh,
            tanh_slice,
            &normal_corpus(-10.0, 10.0),
        );
        assert_slice_bits(
            "tanh positive near saturation",
            tanh,
            tanh_slice,
            &bench_inputs(19.5, 21.9),
        );
        assert_slice_bits(
            "tanh negative near saturation",
            tanh,
            tanh_slice,
            &bench_inputs(-21.9, -19.5),
        );
        assert_slice_bits(
            "cosh small expm1 branch",
            cosh,
            cosh_slice,
            &bench_inputs(1.0e-15, 0.34),
        );

        let signed_tail = bench_inputs(-10.0, 10.0);
        let positive_tail = bench_inputs(0.000_001, 10.0);
        for length in 0..=(2 * bits::SIMD_LANES + 3) {
            let input = &arbitrary[..length];
            assert_slice_bits("sqrt tail", sqrt, sqrt_slice, input);
            assert_slice_bits("cbrt tail", cbrt, cbrt_slice, input);
            assert_slice_bits("exp tail", exp, exp_slice, input);
            assert_slice_bits("expm1 tail", expm1, expm1_slice, input);
            assert_slice_bits("ln tail", ln, ln_slice, input);
            assert_slice_bits("log2 tail", log2, log2_slice, input);
            assert_slice_bits("sinh tail", sinh, sinh_slice, input);
            assert_slice_bits("cosh tail", cosh, cosh_slice, input);
            assert_slice_bits("tanh tail", tanh, tanh_slice, input);

            let signed = &signed_tail[..length];
            assert_slice_bits("cbrt SIMD tail", cbrt, cbrt_slice, signed);
            assert_slice_bits("exp SIMD tail", exp, exp_slice, signed);
            assert_slice_bits("expm1 SIMD tail", expm1, expm1_slice, signed);
            assert_slice_bits("sinh SIMD tail", sinh, sinh_slice, signed);
            assert_slice_bits("cosh SIMD tail", cosh, cosh_slice, signed);
            assert_slice_bits("tanh SIMD tail", tanh, tanh_slice, signed);

            let positive = &positive_tail[..length];
            assert_slice_bits("sqrt SIMD tail", sqrt, sqrt_slice, positive);
            assert_slice_bits("ln SIMD tail", ln, ln_slice, positive);
            assert_slice_bits("log2 SIMD tail", log2, log2_slice, positive);
        }
    }

    const BENCH_LEN: usize = 65_536;

    fn bench_inputs(low: f64, high: f64) -> Vec<f64> {
        let step = (high - low) / BENCH_LEN as f64;
        (0..BENCH_LEN)
            .map(|index| low + (index as f64 + 0.5) * step)
            .collect()
    }

    macro_rules! bench_unary {
        ($name:ident, $function:path, $low:expr, $high:expr) => {
            #[bench]
            fn $name(bencher: &mut Bencher) {
                let input = bench_inputs($low, $high);
                let mut output = vec![0.0; BENCH_LEN];
                bencher.iter(|| {
                    for (destination, &value) in output.iter_mut().zip(&input) {
                        *destination = $function(black_box(value));
                    }
                    black_box(&output);
                });
            }
        };
    }

    macro_rules! bench_slice {
        ($name:ident, $function:path, $low:expr, $high:expr) => {
            #[bench]
            fn $name(bencher: &mut Bencher) {
                let input = bench_inputs($low, $high);
                let mut output = vec![0.0; BENCH_LEN];
                bencher.iter(|| {
                    output.copy_from_slice(&input);
                    $function(black_box(&mut output));
                    black_box(&output);
                });
            }
        };
    }

    bench_unary!(scalar_sin_65536, sin, -100.0, 100.0);
    bench_unary!(scalar_cos_65536, cos, -100.0, 100.0);
    bench_unary!(scalar_tan_65536, tan, -100.0, 100.0);
    bench_unary!(scalar_asin_65536, asin, -1.0, 1.0);
    bench_unary!(scalar_acos_65536, acos, -1.0, 1.0);
    bench_unary!(scalar_atan_65536, atan, -100.0, 100.0);
    bench_unary!(scalar_exp_65536, exp, -10.0, 10.0);
    bench_unary!(scalar_expm1_65536, expm1, -10.0, 10.0);
    bench_unary!(scalar_ln_65536, ln, 0.000_001, 100.0);
    bench_unary!(scalar_log2_65536, log2, 0.000_001, 100.0);
    bench_unary!(scalar_sqrt_65536, sqrt, 0.0, 1_000_000.0);
    bench_unary!(scalar_cbrt_65536, cbrt, -1_000_000.0, 1_000_000.0);
    bench_unary!(scalar_sinh_65536, sinh, -10.0, 10.0);
    bench_unary!(scalar_cosh_65536, cosh, -10.0, 10.0);
    bench_unary!(scalar_tanh_65536, tanh, -10.0, 10.0);
    bench_slice!(simd_sqrt_65536, sqrt_slice, 0.0, 1_000_000.0);
    bench_slice!(simd_cbrt_65536, cbrt_slice, -1_000_000.0, 1_000_000.0);
    bench_slice!(simd_exp_65536, exp_slice, -10.0, 10.0);
    bench_slice!(simd_expm1_65536, expm1_slice, -10.0, 10.0);
    bench_slice!(simd_ln_65536, ln_slice, 0.000_001, 100.0);
    bench_slice!(simd_log2_65536, log2_slice, 0.000_001, 100.0);
    bench_slice!(simd_sinh_65536, sinh_slice, -10.0, 10.0);
    bench_slice!(simd_cosh_65536, cosh_slice, -10.0, 10.0);
    bench_slice!(simd_tanh_65536, tanh_slice, -10.0, 10.0);

    #[bench]
    fn scalar_atan2_65536(bencher: &mut Bencher) {
        let y = bench_inputs(-100.0, 100.0);
        let x = bench_inputs(0.000_001, 200.0);
        let mut output = vec![0.0; BENCH_LEN];
        bencher.iter(|| {
            for ((destination, &y), &x) in output.iter_mut().zip(&y).zip(&x) {
                *destination = atan2(black_box(y), black_box(x));
            }
            black_box(&output);
        });
    }

    #[bench]
    fn scalar_pow_65536(bencher: &mut Bencher) {
        let x = bench_inputs(0.000_001, 10.0);
        let y = bench_inputs(-3.0, 3.0);
        let mut output = vec![0.0; BENCH_LEN];
        bencher.iter(|| {
            for ((destination, &x), &y) in output.iter_mut().zip(&x).zip(&y) {
                *destination = pow(black_box(x), black_box(y));
            }
            black_box(&output);
        });
    }
}
