#!/usr/bin/env python3
"""Generate fmn-dmath cross-platform vector files from mpmath ground truth.

Each line pairs input f64 bit pattern(s) with the CORRECTLY ROUNDED f64
result computed at 150-bit precision:
    single-arg:  <in_bits_hex>\t<expected_bits_hex>
    two-arg:     <x_bits_hex>\t<y_bits_hex>\t<expected_bits_hex>

The Rust harness (crates/fmn-dmath/tests/vectors.rs) asserts each
implementation lands within its documented ULP bound of these values —
the same committed files on every platform, which is what makes the
bit-identity claim testable in CI across the certified matrix.

NaN inputs are deliberately excluded (payload propagation is
platform-defined); NaN behavior is covered by unit tests instead.

Environment: python3 with mpmath (`uv pip install mpmath`).
Outputs: crates/fmn-dmath/vectors/<fn>.txt — regenerate, never hand-edit.
"""

import math
import os
import struct

from mpmath import mp, mpf

mp.prec = 150

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "crates", "fmn-dmath", "vectors")

HEADER = [
    "# fmn-dmath ground-truth vectors (input bits -> correctly rounded f64 bits)",
    "# generated by scripts/gen_dmath_vectors.py at mpmath prec=150 — regenerate, never hand-edit",
]


def bits(x: float) -> str:
    return f"{struct.unpack('<Q', struct.pack('<d', x))[0]:016x}"


def linspace(a, b, n):
    step = (b - a) / (n - 1)
    return [a + i * step for i in range(n)]


def logspace(lo_exp, hi_exp, n, base=10.0):
    return [base ** e for e in linspace(lo_exp, hi_exp, n)]


DENORMALS = [5e-324, 1e-320, 2.2250738585072011e-308]
TINY = [2.0 ** -k for k in (60, 40, 30, 27, 26, 20, 10)]

# Near-integer multiples of pi/2 (the reduction stress set) as exact doubles.
NEAR_PIO2 = []
for k in range(1, 41):
    NEAR_PIO2.append(float(mpf(k) * mp.pi / 2))
# The classic worst case for double-precision trig reduction.
HARD_TRIG = [
    6381956970095103.0 * 2.0 ** 797,
    5.31937264832654141671e255,
    1e10, 1e16, 1e22, 2.0 ** 500, 2.0 ** 1000, 2.0 ** 1023,
]


def sym(values):
    out = []
    for v in values:
        out.append(v)
        out.append(-v)
    return out


def gen_single(name, fn, inputs):
    os.makedirs(OUT, exist_ok=True)
    path = os.path.join(OUT, f"{name}.txt")
    seen = set()
    lines = list(HEADER)
    for x in inputs:
        b = bits(x)
        if b in seen or math.isnan(x):
            continue
        seen.add(b)
        try:
            expected = float(fn(mpf(x)))
        except (ValueError, OverflowError, ZeroDivisionError):
            continue
        lines.append(f"{b}\t{bits(expected)}")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {path} ({len(lines) - len(HEADER)} vectors)")


def gen_pair(name, fn, pairs):
    os.makedirs(OUT, exist_ok=True)
    path = os.path.join(OUT, f"{name}.txt")
    seen = set()
    lines = list(HEADER)
    for x, y in pairs:
        key = (bits(x), bits(y))
        if key in seen or math.isnan(x) or math.isnan(y):
            continue
        seen.add(key)
        try:
            # Pass raw floats: mpf() collapses -0.0, and the truth
            # functions need the sign for the IEEE special cases.
            expected = float(fn(x, y))
        except (ValueError, OverflowError, ZeroDivisionError, TypeError):
            continue
        if math.isnan(expected):
            continue
        lines.append(f"{key[0]}\t{key[1]}\t{bits(expected)}")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {path} ({len(lines) - len(HEADER)} vectors)")


def trig_inputs():
    xs = linspace(-8.0, 8.0, 400)
    xs += sym([x + 1e-9 for x in NEAR_PIO2]) + sym(NEAR_PIO2)
    xs += sym(HARD_TRIG) + sym(logspace(0.5, 8, 60)) + sym(TINY) + sym(DENORMALS)
    xs += [0.0, -0.0]
    return xs


def main():
    gen_single("sin", mp.sin, trig_inputs())
    gen_single("cos", mp.cos, trig_inputs())
    gen_single("tan", mp.tan, trig_inputs())

    atan_inputs = (
        sym(logspace(-300, 300, 300))
        + linspace(-4.0, 4.0, 200)
        + sym([7 / 16, 11 / 16, 19 / 16, 39 / 16, 2.0 ** 66])
        + sym(DENORMALS)
        + [0.0, -0.0, float("inf"), float("-inf")]
    )
    gen_single("atan", mp.atan, atan_inputs)

    unit = linspace(-1.0, 1.0, 400) + sym([1 - 2.0 ** -k for k in range(1, 40)]) + [1.0, -1.0]
    gen_single("asin", mp.asin, unit + list(sym(TINY)) + list(sym(DENORMALS)))
    gen_single("acos", mp.acos, unit)

    axes = [0.0, -0.0, 0.5, -0.5, 1.0, -1.0, 1e300, -1e300, 1e-300, -1e-300,
            float("inf"), float("-inf")]
    pairs = [(y, x) for y in axes for x in axes]
    grid = linspace(-3.0, 3.0, 24)
    pairs += [(y, x) for y in grid for x in grid]

    def atan2_truth(y, x):
        # mpmath collapses -0.0 to +0.0, which breaks the IEEE-specified
        # signed-zero/inf results; those cases are exactly-representable
        # constants the platform libm returns per IEEE 754, so use it there
        # and keep mpmath truth for the finite nonzero field.
        fy, fx = float(y), float(x)
        if fy == 0.0 or fx == 0.0 or math.isinf(fy) or math.isinf(fx):
            return mpf(math.atan2(fy, fx))
        return mp.atan2(y, x)

    gen_pair("atan2", atan2_truth, pairs)

    exp_inputs = (
        linspace(-745.0, 709.7, 500)
        + [709.782712893384, 709.7827128933841, -745.1332191019412, -745.2]
        + sym(TINY) + sym(DENORMALS) + [0.0, -0.0, float("-inf")]
    )
    gen_single("exp", mp.exp, exp_inputs)
    gen_single("expm1", mp.expm1, linspace(-40.0, 40.0, 400) + list(sym(TINY)) + list(sym(DENORMALS)) + [0.0, -0.0, 709.0, float("-inf")])

    log_inputs = (
        logspace(-308, 308, 500)
        + [1 + 2.0 ** -k for k in range(1, 45)]
        + [1 - 2.0 ** -k for k in range(1, 45)]
        + DENORMALS + [1.0, 2.0, float("inf")]
        + [2.0 ** k for k in range(-60, 61)]
    )
    gen_single("ln", mp.log, log_inputs)
    gen_single("log2", lambda x: mp.log(x) / mp.log(2), log_inputs)

    pow_pairs = []
    for x in [0.5, 1.5, 2.0, 3.0, 10.0, 0.1, 1e10, 1e-10, 0.9999999, 1.0000001]:
        for y in linspace(-30.0, 30.0, 40):
            pow_pairs.append((x, y))
    for x in [-2.0, -3.0, -1.5]:
        for y in [-3.0, -2.0, -1.0, 0.0, 1.0, 2.0, 3.0, 4.0, 5.0]:
            pow_pairs.append((x, y))
    pow_pairs += [(2.0, 1023.0), (2.0, -1074.0), (10.0, 308.0), (10.0, -308.0),
                  (1.0000000000000002, 1e15), (0.9999999999999999, 1e15)]

    def mp_pow(x, y):
        return mp.power(x, y)

    gen_pair("pow", mp_pow, pow_pairs)

    def mp_cbrt(x):
        return mp.sign(x) * mp.cbrt(abs(x)) if x < 0 else mp.cbrt(x)

    gen_single("cbrt", mp_cbrt,
               sym(logspace(-300, 300, 300)) + [8.0, -27.0, 0.001, 1e300]
               + list(sym(DENORMALS)) + [0.0, -0.0, float("inf"), float("-inf")])

    hyper_inputs = linspace(-40.0, 40.0, 400) + list(sym(TINY)) + list(sym(DENORMALS)) \
        + [0.0, -0.0, 709.0, -709.0, 710.5, -710.5, float("inf"), float("-inf")]
    gen_single("sinh", mp.sinh, hyper_inputs)
    gen_single("cosh", mp.cosh, hyper_inputs)
    gen_single("tanh", mp.tanh, hyper_inputs)


if __name__ == "__main__":
    main()
