#!/usr/bin/env python3
"""Generate fmn-core RNG parity vectors from NumPy's PCG64DXSM.

The one-RNG rule (§6.5, D-06): FrankenManim's stream is PCG64DXSM,
bit-exact against NumPy for explicit seeds. These vectors pin:
  - SeedSequence.generate_state words for seeds and spawn keys,
  - the first u64 draws and f64 doubles of seeded generators,
  - named-substream and keyed per-frame-fork generators, using the
    canonical name encoding mirrored in crates/fmn-core/src/rng.rs:
    spawn_key = [len(name_bytes)] + name_bytes packed LE into u32 words
    (zero-padded), then [frame_lo, frame_hi] for forks.

Output: crates/fmn-core/fixtures/rng_vectors.txt — regenerate, never
hand-edit. Requires numpy.
"""

import os
import struct

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "crates", "fmn-core", "fixtures", "rng_vectors.txt")

SEEDS = [0, 1, 42, 123456789, 2**32 - 1, 2**63 + 11, 2**64 - 1]
NAMES = ["layout_jitter", "stream_lines", "sampling", "shuffle", "x"]
FRAMES = [0, 1, 2, 1000, 2**32 + 5]


def name_words(name: str) -> list[int]:
    data = name.encode("utf-8")
    words = [len(data)]
    padded = data + b"\x00" * (-len(data) % 4)
    for i in range(0, len(padded), 4):
        words.append(struct.unpack("<I", padded[i : i + 4])[0])
    return words


def frame_words(frame: int) -> list[int]:
    return [frame & 0xFFFFFFFF, (frame >> 32) & 0xFFFFFFFF]


def gen_u64(seed_seq, n):
    g = np.random.Generator(np.random.PCG64DXSM(seed_seq))
    return [int(x) for x in g.integers(0, 2**64, n, dtype=np.uint64)]


def main():
    lines = [
        "# fmn-core RNG parity vectors (NumPy PCG64DXSM / SeedSequence ground truth)",
        "# generated by scripts/gen_rng_vectors.py — regenerate, never hand-edit",
    ]
    for seed in SEEDS:
        ss = np.random.SeedSequence(seed)
        words = ss.generate_state(8)
        lines.append(
            f"seedseq\t{seed}\t" + "\t".join(f"{int(w):08x}" for w in words)
        )
        draws = gen_u64(np.random.SeedSequence(seed), 16)
        lines.append(f"draws\t{seed}\t" + "\t".join(f"{d:016x}" for d in draws))
        g = np.random.Generator(np.random.PCG64DXSM(np.random.SeedSequence(seed)))
        doubles = g.random(8)
        lines.append(
            f"doubles\t{seed}\t"
            + "\t".join(f"{struct.unpack('<Q', struct.pack('<d', float(d)))[0]:016x}" for d in doubles)
        )
    for seed in [0, 42]:
        for name in NAMES:
            key = tuple(name_words(name))
            ss = np.random.SeedSequence(entropy=seed, spawn_key=key)
            draws = gen_u64(ss, 8)
            lines.append(
                f"substream\t{seed}\t{name}\t" + "\t".join(f"{d:016x}" for d in draws)
            )
            for frame in FRAMES:
                fork_key = key + tuple(frame_words(frame))
                fss = np.random.SeedSequence(entropy=seed, spawn_key=fork_key)
                fdraws = gen_u64(fss, 4)
                lines.append(
                    f"fork\t{seed}\t{name}\t{frame}\t"
                    + "\t".join(f"{d:016x}" for d in fdraws)
                )
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({len(lines) - 2} vectors)")


if __name__ == "__main__":
    main()
