//! Parity tables against the pinned Reference
//! (`3b1b/manim @ 6199a00d4c1b1127ebe45cb629c3f22538b10e13`).
//!
//! Fixtures are generated by `scripts/gen_reference_fixtures.py`; regenerate
//! there, never hand-edit. Tolerance is 1e-12 absolute: the formulas agree
//! to ~1e-15, and the slack only absorbs libm ulp differences between
//! platforms (the very differences fmn-dmath will erase for render math).

use fmn_core::color::{Srgb, average_color, color_gradient, interpolate_color};
use fmn_core::constants::*;
use fmn_core::rate;

const TOL: f64 = 1e-12;

fn fixture(name: &str) -> &'static str {
    match name {
        "constants" => include_str!("../fixtures/constants.txt"),
        "rate_manifest" => include_str!("../fixtures/rate_functions.txt"),
        "color_ops" => include_str!("../fixtures/color_ops.txt"),
        _ => unreachable!(),
    }
}

fn assert_close(name: &str, got: f64, want: f64) {
    assert!(
        (got - want).abs() <= TOL,
        "{name}: got {got:?}, Reference says {want:?} (|Δ| = {:e})",
        (got - want).abs()
    );
}

// --- constants ------------------------------------------------------------

enum Expect {
    F(f64),
    V(fmn_core::types::Vec3),
    Res((u32, u32)),
    Color(Srgb),
}

fn constant_by_name(name: &str) -> Option<Expect> {
    use Expect::{Color, F, Res, V};
    Some(match name {
        "DEFAULT_PIXEL_WIDTH" => F(f64::from(DEFAULT_PIXEL_WIDTH)),
        "DEFAULT_PIXEL_HEIGHT" => F(f64::from(DEFAULT_PIXEL_HEIGHT)),
        "ASPECT_RATIO" => F(ASPECT_RATIO),
        "FRAME_HEIGHT" => F(FRAME_HEIGHT),
        "FRAME_WIDTH" => F(FRAME_WIDTH),
        "FRAME_Y_RADIUS" => F(FRAME_Y_RADIUS),
        "FRAME_X_RADIUS" => F(FRAME_X_RADIUS),
        "SMALL_BUFF" => F(SMALL_BUFF),
        "MED_SMALL_BUFF" => F(MED_SMALL_BUFF),
        "MED_LARGE_BUFF" => F(MED_LARGE_BUFF),
        "LARGE_BUFF" => F(LARGE_BUFF),
        "DEFAULT_MOBJECT_TO_EDGE_BUFF" => F(DEFAULT_MOBJECT_TO_EDGE_BUFF),
        "DEFAULT_MOBJECT_TO_MOBJECT_BUFF" => F(DEFAULT_MOBJECT_TO_MOBJECT_BUFF),
        "ORIGIN" => V(ORIGIN),
        "UP" => V(UP),
        "DOWN" => V(DOWN),
        "RIGHT" => V(RIGHT),
        "LEFT" => V(LEFT),
        "IN" => V(IN),
        "OUT" => V(OUT),
        "X_AXIS" => V(X_AXIS),
        "Y_AXIS" => V(Y_AXIS),
        "Z_AXIS" => V(Z_AXIS),
        "UL" => V(UL),
        "UR" => V(UR),
        "DL" => V(DL),
        "DR" => V(DR),
        "TOP" => V(TOP),
        "BOTTOM" => V(BOTTOM),
        "LEFT_SIDE" => V(LEFT_SIDE),
        "RIGHT_SIDE" => V(RIGHT_SIDE),
        "PI" => F(PI),
        "TAU" => F(TAU),
        "DEG" => F(DEG),
        "RADIANS" => F(RADIANS),
        "DEFAULT_STROKE_WIDTH" => F(DEFAULT_STROKE_WIDTH),
        "STROKE_WIDTH_CONVERSION" => F(STROKE_WIDTH_CONVERSION),
        "DEFAULT_FPS" => F(f64::from(DEFAULT_FPS)),
        "DEFAULT_BACKGROUND_COLOR" => Color(DEFAULT_BACKGROUND_COLOR),
        "RESOLUTION_LOW" => Res(RESOLUTION_LOW),
        "RESOLUTION_MED" => Res(RESOLUTION_MED),
        "RESOLUTION_HIGH" => Res(RESOLUTION_HIGH),
        "RESOLUTION_4K" => Res(RESOLUTION_4K),
        "BLUE_E" => Color(BLUE_E),
        "BLUE_D" => Color(BLUE_D),
        "BLUE_C" => Color(BLUE_C),
        "BLUE_B" => Color(BLUE_B),
        "BLUE_A" => Color(BLUE_A),
        "TEAL_E" => Color(TEAL_E),
        "TEAL_D" => Color(TEAL_D),
        "TEAL_C" => Color(TEAL_C),
        "TEAL_B" => Color(TEAL_B),
        "TEAL_A" => Color(TEAL_A),
        "GREEN_E" => Color(GREEN_E),
        "GREEN_D" => Color(GREEN_D),
        "GREEN_C" => Color(GREEN_C),
        "GREEN_B" => Color(GREEN_B),
        "GREEN_A" => Color(GREEN_A),
        "YELLOW_E" => Color(YELLOW_E),
        "YELLOW_D" => Color(YELLOW_D),
        "YELLOW_C" => Color(YELLOW_C),
        "YELLOW_B" => Color(YELLOW_B),
        "YELLOW_A" => Color(YELLOW_A),
        "GOLD_E" => Color(GOLD_E),
        "GOLD_D" => Color(GOLD_D),
        "GOLD_C" => Color(GOLD_C),
        "GOLD_B" => Color(GOLD_B),
        "GOLD_A" => Color(GOLD_A),
        "RED_E" => Color(RED_E),
        "RED_D" => Color(RED_D),
        "RED_C" => Color(RED_C),
        "RED_B" => Color(RED_B),
        "RED_A" => Color(RED_A),
        "MAROON_E" => Color(MAROON_E),
        "MAROON_D" => Color(MAROON_D),
        "MAROON_C" => Color(MAROON_C),
        "MAROON_B" => Color(MAROON_B),
        "MAROON_A" => Color(MAROON_A),
        "PURPLE_E" => Color(PURPLE_E),
        "PURPLE_D" => Color(PURPLE_D),
        "PURPLE_C" => Color(PURPLE_C),
        "PURPLE_B" => Color(PURPLE_B),
        "PURPLE_A" => Color(PURPLE_A),
        "GREY_E" => Color(GREY_E),
        "GREY_D" => Color(GREY_D),
        "GREY_C" => Color(GREY_C),
        "GREY_B" => Color(GREY_B),
        "GREY_A" => Color(GREY_A),
        "WHITE" => Color(WHITE),
        "BLACK" => Color(BLACK),
        "GREY_BROWN" => Color(GREY_BROWN),
        "DARK_BROWN" => Color(DARK_BROWN),
        "LIGHT_BROWN" => Color(LIGHT_BROWN),
        "PINK" => Color(PINK),
        "LIGHT_PINK" => Color(LIGHT_PINK),
        "GREEN_SCREEN" => Color(GREEN_SCREEN),
        "ORANGE" => Color(ORANGE),
        "PURE_RED" => Color(PURE_RED),
        "PURE_GREEN" => Color(PURE_GREEN),
        "PURE_BLUE" => Color(PURE_BLUE),
        "BLUE" => Color(BLUE),
        "TEAL" => Color(TEAL),
        "GREEN" => Color(GREEN),
        "YELLOW" => Color(YELLOW),
        "GOLD" => Color(GOLD),
        "RED" => Color(RED),
        "MAROON" => Color(MAROON),
        "PURPLE" => Color(PURPLE),
        "GREY" => Color(GREY),
        "DEFAULT_MOBJECT_COLOR" => Color(DEFAULT_MOBJECT_COLOR),
        "DEFAULT_LIGHT_COLOR" => Color(DEFAULT_LIGHT_COLOR),
        "DEFAULT_VMOBJECT_STROKE_COLOR" => Color(DEFAULT_VMOBJECT_STROKE_COLOR),
        "DEFAULT_VMOBJECT_FILL_COLOR" => Color(DEFAULT_VMOBJECT_FILL_COLOR),
        _ => return None,
    })
}

#[test]
fn constants_match_the_reference() {
    let mut checked = 0usize;
    for line in fixture("constants").lines() {
        if line.starts_with('#') || line.is_empty() {
            continue;
        }
        let mut parts = line.split('\t');
        let name = parts.next().unwrap();
        let fields: Vec<&str> = parts.collect();
        let expect = constant_by_name(name)
            .unwrap_or_else(|| panic!("fixture constant {name} not implemented in fmn-core"));
        match expect {
            Expect::F(got) => {
                assert_eq!(fields.len(), 1, "{name}: field count");
                // Constants are exact: bit-for-bit equal, not merely close.
                assert_eq!(
                    got,
                    fields[0].parse::<f64>().unwrap(),
                    "{name} diverges from the Reference"
                );
            }
            Expect::V(got) => {
                assert_eq!(fields.len(), 3, "{name}: field count");
                for (axis, (g, w)) in got.iter().zip(&fields).enumerate() {
                    assert_eq!(
                        *g,
                        w.parse::<f64>().unwrap(),
                        "{name}[{axis}] diverges from the Reference"
                    );
                }
            }
            Expect::Res((w, h)) => {
                assert_eq!(fields.len(), 2, "{name}: field count");
                assert_eq!(w, fields[0].parse::<u32>().unwrap(), "{name} width");
                assert_eq!(h, fields[1].parse::<u32>().unwrap(), "{name} height");
            }
            Expect::Color(got) => {
                assert_eq!(fields.len(), 1, "{name}: field count");
                let want = Srgb::from_hex(fields[0]).unwrap();
                assert_eq!(got, want, "{name} diverges from the Reference palette");
            }
        }
        checked += 1;
    }
    assert!(
        checked >= 113,
        "expected the full constants table, saw {checked}"
    );
}

// --- rate functions -------------------------------------------------------

#[test]
fn rate_functions_match_the_reference_at_1e4_samples() {
    let bin: &[u8] = include_bytes!("../fixtures/rate_functions.bin");
    let mut offset = 0usize;
    let mut functions_checked = 0usize;
    for line in fixture("rate_manifest").lines() {
        if line.starts_with('#') || line.is_empty() {
            continue;
        }
        let (name, count) = line.split_once('\t').unwrap();
        let count: usize = count.parse().unwrap();
        let n = count - 1;
        let f: Box<dyn Fn(f64) -> f64> = match name {
            "linear" => Box::new(rate::linear),
            "smooth" => Box::new(rate::smooth),
            "rush_into" => Box::new(rate::rush_into),
            "rush_from" => Box::new(rate::rush_from),
            "slow_into" => Box::new(rate::slow_into),
            "double_smooth" => Box::new(rate::double_smooth),
            "there_and_back" => Box::new(rate::there_and_back),
            "there_and_back_with_pause" => {
                Box::new(|t| rate::there_and_back_with_pause(t, 1.0 / 3.0))
            }
            "running_start" => Box::new(|t| rate::running_start(t, -0.5)),
            "overshoot" => Box::new(|t| rate::overshoot(t, 1.5)),
            "wiggle" => Box::new(|t| rate::wiggle(t, 2.0)),
            "lingering" => Box::new(rate::lingering),
            "exponential_decay" => Box::new(|t| rate::exponential_decay(t, 0.1)),
            "not_quite_there_smooth_0.7" => Box::new(rate::not_quite_there(rate::smooth, 0.7)),
            "squish_smooth_0.4_0.6" => Box::new(rate::squish_rate_func(rate::smooth, 0.4, 0.6)),
            other => panic!("fixture rate function {other} not implemented"),
        };
        for i in 0..count {
            let bytes: [u8; 8] = bin[offset + i * 8..offset + i * 8 + 8].try_into().unwrap();
            let want = f64::from_le_bytes(bytes);
            let t = i as f64 / n as f64;
            assert_close(&format!("{name}(t={t})"), f(t), want);
        }
        offset += count * 8;
        functions_checked += 1;
    }
    assert_eq!(functions_checked, 15, "expected the full rate catalog");
    assert_eq!(offset, bin.len(), "fixture and manifest disagree on length");
}

// --- color operations -----------------------------------------------------

#[test]
fn color_operations_match_the_reference() {
    let mut interp = 0usize;
    let mut avg = 0usize;
    let mut grad = 0usize;
    let gradient = color_gradient(&COLORMAP_3B1B, 9);
    for line in fixture("color_ops").lines() {
        if line.starts_with('#') || line.is_empty() {
            continue;
        }
        let fields: Vec<&str> = line.split('\t').collect();
        match fields[0] {
            "interp" => {
                let c1 = palette_by_lower_name(fields[1]);
                let c2 = palette_by_lower_name(fields[2]);
                let alpha: f64 = fields[3].parse().unwrap();
                let got = interpolate_color(c1, c2, alpha);
                for (axis, (g, w)) in [got.r, got.g, got.b].iter().zip(&fields[4..]).enumerate() {
                    assert_close(
                        &format!("interp({}, {}, {alpha})[{axis}]", fields[1], fields[2]),
                        *g,
                        w.parse().unwrap(),
                    );
                }
                interp += 1;
            }
            "average" => {
                let colors: Vec<Srgb> = match fields[1] {
                    "ALL" => ALL_PALETTE.to_vec(),
                    fam => ALL_PALETTE_NAMES
                        .iter()
                        .zip(ALL_PALETTE.iter())
                        .filter(|(n, _)| n.starts_with(&format!("{fam}_")))
                        .map(|(_, c)| *c)
                        .collect(),
                };
                let got = average_color(&colors);
                for (axis, (g, w)) in [got.r, got.g, got.b].iter().zip(&fields[2..]).enumerate() {
                    assert_close(
                        &format!("average({})[{axis}]", fields[1]),
                        *g,
                        w.parse().unwrap(),
                    );
                }
                avg += 1;
            }
            "gradient3b1b" => {
                let j: usize = fields[1].parse().unwrap();
                let got = gradient[j];
                for (axis, (g, w)) in [got.r, got.g, got.b].iter().zip(&fields[2..]).enumerate() {
                    assert_close(
                        &format!("gradient3b1b[{j}][{axis}]"),
                        *g,
                        w.parse().unwrap(),
                    );
                }
                grad += 1;
            }
            other => panic!("unknown color fixture kind {other}"),
        }
    }
    assert!(
        interp >= 300 && avg == 10 && grad == 9,
        "fixture coverage shrank"
    );
}

const ALL_PALETTE_NAMES: [&str; 57] = [
    "blue_e",
    "blue_d",
    "blue_c",
    "blue_b",
    "blue_a",
    "teal_e",
    "teal_d",
    "teal_c",
    "teal_b",
    "teal_a",
    "green_e",
    "green_d",
    "green_c",
    "green_b",
    "green_a",
    "yellow_e",
    "yellow_d",
    "yellow_c",
    "yellow_b",
    "yellow_a",
    "gold_e",
    "gold_d",
    "gold_c",
    "gold_b",
    "gold_a",
    "red_e",
    "red_d",
    "red_c",
    "red_b",
    "red_a",
    "maroon_e",
    "maroon_d",
    "maroon_c",
    "maroon_b",
    "maroon_a",
    "purple_e",
    "purple_d",
    "purple_c",
    "purple_b",
    "purple_a",
    "grey_e",
    "grey_d",
    "grey_c",
    "grey_b",
    "grey_a",
    "white",
    "black",
    "grey_brown",
    "dark_brown",
    "light_brown",
    "pink",
    "light_pink",
    "green_screen",
    "orange",
    "pure_red",
    "pure_green",
    "pure_blue",
];

const ALL_PALETTE: [Srgb; 57] = [
    BLUE_E,
    BLUE_D,
    BLUE_C,
    BLUE_B,
    BLUE_A,
    TEAL_E,
    TEAL_D,
    TEAL_C,
    TEAL_B,
    TEAL_A,
    GREEN_E,
    GREEN_D,
    GREEN_C,
    GREEN_B,
    GREEN_A,
    YELLOW_E,
    YELLOW_D,
    YELLOW_C,
    YELLOW_B,
    YELLOW_A,
    GOLD_E,
    GOLD_D,
    GOLD_C,
    GOLD_B,
    GOLD_A,
    RED_E,
    RED_D,
    RED_C,
    RED_B,
    RED_A,
    MAROON_E,
    MAROON_D,
    MAROON_C,
    MAROON_B,
    MAROON_A,
    PURPLE_E,
    PURPLE_D,
    PURPLE_C,
    PURPLE_B,
    PURPLE_A,
    GREY_E,
    GREY_D,
    GREY_C,
    GREY_B,
    GREY_A,
    WHITE,
    BLACK,
    GREY_BROWN,
    DARK_BROWN,
    LIGHT_BROWN,
    PINK,
    LIGHT_PINK,
    GREEN_SCREEN,
    ORANGE,
    PURE_RED,
    PURE_GREEN,
    PURE_BLUE,
];

fn palette_by_lower_name(name: &str) -> Srgb {
    ALL_PALETTE_NAMES
        .iter()
        .position(|n| *n == name)
        .map(|i| ALL_PALETTE[i])
        .unwrap_or_else(|| panic!("unknown palette name {name}"))
}
