//! fm-65l acceptance: WAV round-trips across sample formats, y4m
//! header/frame conformance, GIF determinism + golden digest + an
//! in-test LZW oracle, and the deterministic parallel PNG sequence at
//! {1, 4, 16} threads (bit-identical bytes — the PG-5 property).

use fmn_codec::{
    CompressionLevel, PngLimits, SampleFormat, WavError, WavLimits, Y4mColorspace, Y4mWriter,
    decode_png, decode_wav, decode_y4m, encode_gif, encode_png_sequence, encode_rgba8_segmented,
    encode_wav,
};
use fmn_frame::{FrameBuffer, FrameLayout, PixelFormat};

// ---- WAV ------------------------------------------------------------

#[test]
fn wav_s16_round_trip_is_exact() {
    let samples: Vec<f32> = (-8..8).map(|v| f32::from(v as i16) / 8.0 * 0.9).collect();
    let bytes = encode_wav(2, 48_000, SampleFormat::S16, &samples);
    let decoded = decode_wav(&bytes, &WavLimits::default()).unwrap();
    assert_eq!(decoded.channels, 2);
    assert_eq!(decoded.sample_rate, 48_000);
    assert_eq!(decoded.format, SampleFormat::S16);
    // s16 quantization then /32768 recovers a value within one step;
    // and re-encoding is a fixed point (the certified artifact form).
    let bytes2 = encode_wav(2, 48_000, SampleFormat::S16, &decoded.samples);
    assert_eq!(bytes, bytes2, "s16 encode is not idempotent");
}

#[test]
fn wav_f32_round_trip_is_identity() {
    let samples: Vec<f32> = (0..100)
        .map(|i| ((i * 37) % 200) as f32 / 100.0 - 1.0)
        .collect();
    let bytes = encode_wav(1, 44_100, SampleFormat::F32, &samples);
    let decoded = decode_wav(&bytes, &WavLimits::default()).unwrap();
    assert_eq!(decoded.format, SampleFormat::F32);
    assert_eq!(decoded.samples, samples);
}

#[test]
fn wav_decodes_the_cpython_fixture_matrix() {
    // Fixtures generated by CPython's wave module + struct (see
    // gen_wav_fixtures.py): the same ramp in u8/s16/s24/s32/f32.
    for (name, format) in [
        ("ramp_u8", SampleFormat::U8),
        ("ramp_s16", SampleFormat::S16),
        ("ramp_s24", SampleFormat::S24),
        ("ramp_s32", SampleFormat::S32),
        ("ramp_f32", SampleFormat::F32),
    ] {
        let bytes = match name {
            "ramp_u8" => &include_bytes!("fixtures/wav/ramp_u8.wav")[..],
            "ramp_s16" => &include_bytes!("fixtures/wav/ramp_s16.wav")[..],
            "ramp_s24" => &include_bytes!("fixtures/wav/ramp_s24.wav")[..],
            "ramp_s32" => &include_bytes!("fixtures/wav/ramp_s32.wav")[..],
            _ => &include_bytes!("fixtures/wav/ramp_f32.wav")[..],
        };
        let decoded =
            decode_wav(bytes, &WavLimits::default()).unwrap_or_else(|e| panic!("{name}: {e}"));
        assert_eq!(decoded.format, format, "{name}");
        assert_eq!(decoded.channels, 1, "{name}");
        assert_eq!(decoded.sample_rate, 8000, "{name}");
        assert_eq!(decoded.samples.len(), 64, "{name}");
        // The ramp: sample k ≈ (k − 32)/32, within each format's step.
        let tolerance = match format {
            SampleFormat::U8 => 1.0 / 127.0,
            _ => 1.0 / 8000.0,
        };
        for (k, &v) in decoded.samples.iter().enumerate() {
            #[allow(clippy::cast_precision_loss)]
            let expected = (k as f32 - 32.0) / 32.0;
            assert!(
                (v - expected).abs() <= tolerance,
                "{name}[{k}]: {v} vs {expected}"
            );
        }
    }
}

#[test]
fn wav_refusals_are_typed() {
    assert_eq!(
        decode_wav(b"RIFFxxxxWAVE", &WavLimits::default()),
        Err(WavError::MissingFmt)
    );
    assert_eq!(
        decode_wav(b"not audio", &WavLimits::default()),
        Err(WavError::NotWav)
    );
    // A µ-law tag is a named refusal.
    let mut bytes = encode_wav(1, 8000, SampleFormat::S16, &[0.0; 4]);
    bytes[20] = 7; // format tag
    assert_eq!(
        decode_wav(&bytes, &WavLimits::default()),
        Err(WavError::UnsupportedFormat { format_tag: 7 })
    );
    // The sample budget.
    let big = encode_wav(1, 8000, SampleFormat::S16, &[0.0; 100]);
    assert_eq!(
        decode_wav(&big, &WavLimits { max_samples: 50 }),
        Err(WavError::TooLarge { max_samples: 50 })
    );
}

// ---- y4m ------------------------------------------------------------

fn nv12_frame(w: u32, h: u32, seed: u8) -> FrameBuffer {
    let mut frame = FrameBuffer::new(FrameLayout::tight(PixelFormat::Nv12, w, h).unwrap());
    for (i, byte) in frame.plane_mut(0).iter_mut().enumerate() {
        *byte = (i as u8).wrapping_mul(3).wrapping_add(seed);
    }
    for (i, byte) in frame.plane_mut(1).iter_mut().enumerate() {
        *byte = (i as u8).wrapping_mul(5).wrapping_add(seed);
    }
    frame
}

#[test]
fn y4m_round_trip_and_header_conformance() {
    let mut writer = Y4mWriter::new(16, 8, (30000, 1001), Y4mColorspace::C420Mpeg2);
    writer.write_frame_nv12(&nv12_frame(16, 8, 1)).unwrap();
    writer.write_frame_nv12(&nv12_frame(16, 8, 2)).unwrap();
    let bytes = writer.finish();

    // Header conforms to spec, rational rate verbatim.
    let header_end = bytes.iter().position(|&b| b == b'\n').unwrap();
    assert_eq!(
        &bytes[..header_end],
        b"YUV4MPEG2 W16 H8 F30000:1001 Ip A1:1 C420mpeg2"
    );

    let decoded = decode_y4m(&bytes).unwrap();
    assert_eq!((decoded.width, decoded.height), (16, 8));
    assert_eq!(decoded.fps, (30000, 1001));
    assert_eq!(decoded.frames.len(), 2);
    assert_eq!(decoded.frames[0].len(), 16 * 8 * 3 / 2);

    // Planar layout: luma verbatim, then deinterleaved Cb, then Cr.
    let source = nv12_frame(16, 8, 1);
    let luma = &decoded.frames[0][..16 * 8];
    assert_eq!(luma, source.plane(0));
    let cb = &decoded.frames[0][16 * 8..16 * 8 + 8 * 4];
    let cr = &decoded.frames[0][16 * 8 + 8 * 4..];
    for (i, pair) in source.plane(1).as_chunks::<2>().0.iter().enumerate() {
        assert_eq!(cb[i], pair[0], "cb[{i}]");
        assert_eq!(cr[i], pair[1], "cr[{i}]");
    }

    // Wrong geometry and wrong format are refusals.
    let mut writer = Y4mWriter::new(16, 8, (30, 1), Y4mColorspace::C420Jpeg);
    assert!(writer.write_frame_nv12(&nv12_frame(8, 8, 0)).is_err());
    let rgba = FrameBuffer::new(FrameLayout::tight(PixelFormat::Rgba8, 16, 8).unwrap());
    assert!(writer.write_frame_nv12(&rgba).is_err());
}

// ---- GIF ------------------------------------------------------------

/// A minimal GIF block-walker + LZW decoder: the in-test oracle.
struct ParsedGif {
    palette: Vec<[u8; 3]>,
    /// (delay_cs, transparent_index, indices) per frame.
    frames: Vec<(u16, Option<u8>, Vec<u8>)>,
}

fn parse_gif(bytes: &[u8]) -> ParsedGif {
    assert_eq!(&bytes[..6], b"GIF89a");
    let flags = bytes[10];
    assert!(flags & 0x80 != 0, "no global color table");
    let gct_len = 1usize << ((flags & 0x07) + 1);
    let mut at = 13;
    let palette: Vec<[u8; 3]> = bytes[at..at + gct_len * 3]
        .as_chunks::<3>()
        .0
        .iter()
        .map(|c| [c[0], c[1], c[2]])
        .collect();
    at += gct_len * 3;

    let mut frames = Vec::new();
    let mut pending: (u16, Option<u8>) = (0, None);
    loop {
        match bytes[at] {
            0x3b => break,
            0x21 => {
                let label = bytes[at + 1];
                at += 2;
                if label == 0xf9 {
                    let size = bytes[at] as usize;
                    let body = &bytes[at + 1..at + 1 + size];
                    let delay = u16::from_le_bytes([body[1], body[2]]);
                    let transparent = (body[0] & 1 == 1).then_some(body[3]);
                    pending = (delay, transparent);
                }
                // Skip sub-blocks.
                loop {
                    let size = bytes[at] as usize;
                    at += 1 + size;
                    if size == 0 {
                        break;
                    }
                }
            }
            0x2c => {
                let w = u16::from_le_bytes([bytes[at + 5], bytes[at + 6]]) as usize;
                let h = u16::from_le_bytes([bytes[at + 7], bytes[at + 8]]) as usize;
                assert_eq!(bytes[at + 9] & 0x80, 0, "unexpected local palette");
                at += 10;
                let min_code_size = bytes[at];
                at += 1;
                let mut data = Vec::new();
                loop {
                    let size = bytes[at] as usize;
                    if size == 0 {
                        at += 1;
                        break;
                    }
                    data.extend_from_slice(&bytes[at + 1..at + 1 + size]);
                    at += 1 + size;
                }
                let indices = lzw_decode(&data, min_code_size);
                assert_eq!(indices.len(), w * h, "index count");
                frames.push((pending.0, pending.1, indices));
                pending = (0, None);
            }
            other => panic!("unexpected gif block {other:#x} at {at}"),
        }
    }
    ParsedGif { palette, frames }
}

/// GIF-variant LZW decode (the oracle for the encoder).
fn lzw_decode(data: &[u8], min_code_size: u8) -> Vec<u8> {
    let clear = 1u16 << min_code_size;
    let eoi = clear + 1;
    let mut table: Vec<Vec<u8>> = Vec::new();
    let reset = |table: &mut Vec<Vec<u8>>| {
        table.clear();
        for i in 0..clear {
            table.push(vec![i as u8]);
        }
        table.push(Vec::new()); // clear
        table.push(Vec::new()); // eoi
    };
    reset(&mut table);
    let mut width = u32::from(min_code_size) + 1;
    let mut out = Vec::new();
    let mut prev: Option<u16> = None;

    let mut bits = 0u32;
    let mut count = 0u32;
    let mut pos = 0usize;
    loop {
        while count < width {
            assert!(pos < data.len(), "lzw ran dry");
            bits |= u32::from(data[pos]) << count;
            count += 8;
            pos += 1;
        }
        let code = (bits & ((1 << width) - 1)) as u16;
        bits >>= width;
        count -= width;

        if code == clear {
            reset(&mut table);
            width = u32::from(min_code_size) + 1;
            prev = None;
            continue;
        }
        if code == eoi {
            return out;
        }
        let entry = if (code as usize) < table.len() {
            table[code as usize].clone()
        } else {
            // The k-w-k case.
            let p = &table[prev.expect("kwk without prev") as usize];
            let mut e = p.clone();
            e.push(p[0]);
            e
        };
        out.extend_from_slice(&entry);
        if let Some(p) = prev {
            let mut new = table[p as usize].clone();
            new.push(entry[0]);
            table.push(new);
            if table.len() == (1usize << width) && width < 12 {
                width += 1;
            }
        }
        prev = Some(code);
    }
}

#[test]
fn gif_flat_colors_round_trip_exactly() {
    // Four flat-color frames: few colors, no dither error — the oracle
    // must recover the exact input colors.
    let colors: [[u8; 4]; 4] = [
        [255, 0, 0, 255],
        [0, 255, 0, 255],
        [0, 0, 255, 255],
        [255, 255, 0, 255],
    ];
    let (w, h) = (11u32, 7u32);
    let frames: Vec<Vec<u8>> = colors
        .iter()
        .map(|c| c.repeat(w as usize * h as usize))
        .collect();
    let refs: Vec<&[u8]> = frames.iter().map(Vec::as_slice).collect();
    let gif = encode_gif(w, h, &refs, (3, 1), true).unwrap();

    let parsed = parse_gif(&gif);
    assert_eq!(parsed.frames.len(), 4);
    for (frame, color) in parsed.frames.iter().zip(&colors) {
        let indices = &frame.2;
        let index = indices[0] as usize;
        assert!(
            indices.iter().all(|&i| i as usize == index),
            "flat frame dithered"
        );
        assert_eq!(parsed.palette[index], [color[0], color[1], color[2]]);
    }
    // Drift-free delays at 3 fps: 33+34+33 per 100 cs.
    let delays: Vec<u16> = parsed.frames.iter().map(|f| f.0).collect();
    assert_eq!(delays, vec![33, 34, 33, 33]);
    // The loop extension is present.
    assert!(gif.windows(11).any(|w| w == b"NETSCAPE2.0"));
}

#[test]
fn gif_transparency_and_determinism() {
    let (w, h) = (8u32, 8u32);
    // A gradient frame with a transparent hole.
    let mut frame = Vec::with_capacity(w as usize * h as usize * 4);
    for y in 0..h {
        for x in 0..w {
            let alpha = if (2..5).contains(&x) && (2..5).contains(&y) {
                0
            } else {
                255
            };
            frame.extend_from_slice(&[(x * 30) as u8, (y * 30) as u8, 128, alpha]);
        }
    }
    let gif1 = encode_gif(w, h, &[&frame], (30, 1), false).unwrap();
    let gif2 = encode_gif(w, h, &[&frame], (30, 1), false).unwrap();
    assert_eq!(gif1, gif2, "gif encode is not deterministic");

    let parsed = parse_gif(&gif1);
    let (_, transparent, indices) = &parsed.frames[0];
    let t = transparent.expect("transparency flag missing");
    // The hole took the transparent index; opaque pixels did not.
    assert_eq!(indices[(3 * 8 + 3) as usize], t);
    assert_ne!(indices[0], t);
    assert!(!gif1.windows(11).any(|w| w == b"NETSCAPE2.0"));
}

#[test]
fn gif_golden_digest_is_locked() {
    // The self-golden: a deterministic two-frame fixture's bytes are
    // bit-locked. An intentional algorithm change must update this
    // digest deliberately (that is the point).
    let (w, h) = (16u32, 9u32);
    let make = |seed: u32| -> Vec<u8> {
        let mut state = seed;
        (0..w * h)
            .flat_map(|_| {
                state = state.wrapping_mul(1_664_525).wrapping_add(1_013_904_223);
                let b = state.to_le_bytes();
                [b[0], b[1], b[2], 255]
            })
            .collect()
    };
    let (f0, f1) = (make(1), make(2));
    let gif = encode_gif(w, h, &[&f0, &f1], (30000, 1001), true).unwrap();
    assert_eq!(
        fmn_hash::sha256::sha256(&gif).to_hex(),
        // Locked 2026-07-23 (fm-65l).
        GOLDEN_GIF_SHA256,
        "gif golden drifted — if the change is intentional, relock"
    );
}

/// The locked digest for `gif_golden_digest_is_locked`.
const GOLDEN_GIF_SHA256: &str = "b699a4f9fe7e127b10757fc7af90d4133191b269a9bb2bcc0023165c9d6d4d36";

// ---- deterministic parallel PNG sequences ---------------------------

#[test]
fn png_sequence_is_bit_identical_at_any_thread_count() {
    // Frames big enough that the filtered stream spans multiple fixed
    // segments (400×180 RGBA ⇒ ~288 KiB filtered > one 256 KiB segment).
    let (w, h) = (400u32, 180u32);
    let mut state = 99u32;
    let frames: Vec<Vec<u8>> = (0..6)
        .map(|_| {
            (0..w as usize * h as usize * 4)
                .map(|_| {
                    state = state.wrapping_mul(1_664_525).wrapping_add(1_013_904_223);
                    (state >> 24) as u8
                })
                .collect()
        })
        .collect();
    let refs: Vec<&[u8]> = frames.iter().map(Vec::as_slice).collect();

    let serial: Vec<Vec<u8>> = refs
        .iter()
        .map(|f| encode_rgba8_segmented(w, h, f, CompressionLevel::Default))
        .collect();
    for threads in [1usize, 4, 16] {
        let parallel = encode_png_sequence(w, h, &refs, CompressionLevel::Default, threads);
        assert_eq!(
            parallel, serial,
            "sequence bytes diverged at {threads} threads"
        );
    }

    // And the canonical segmented form decodes to the exact pixels.
    let limits = PngLimits::default();
    for (bytes, original) in serial.iter().zip(&frames) {
        let decoded = decode_png(bytes, &limits).unwrap();
        assert_eq!(&decoded.rgba, original);
    }
}
