//! fm-17m acceptance, slice B: PNG decode conformance over the full
//! color-type matrix (the committed fixture corpus), encode-decode
//! round-trips, deterministic encode, gamma/sRGB precedence, and the
//! §16.5 bomb/malformed refusals.
//!
//! Fixture provenance: generated by an independent CPython
//! implementation (`fixtures/gen_png_fixtures.py`); the 8-bit matrix
//! was verified byte-exact against ImageMagick/libpng, and the 16-bit
//! expectations encode the documented rounding (not chopping) policy.

use fmn_codec::checksum::crc32;
use fmn_codec::png::ColorIntent;
use fmn_codec::{CompressionLevel, PngError, PngLimits, decode_png, encode_rgba8};

macro_rules! fixture {
    ($name:literal) => {
        (
            $name,
            include_bytes!(concat!("fixtures/png/", $name, ".png")) as &[u8],
            include_bytes!(concat!("fixtures/png/", $name, ".rgba")) as &[u8],
        )
    };
}

/// The full matrix: (name, png bytes, expected canonical RGBA8).
const MATRIX: [(&str, &[u8], &[u8]); 22] = [
    fixture!("gray1"),
    fixture!("gray2"),
    fixture!("gray4"),
    fixture!("gray8"),
    fixture!("gray16"),
    fixture!("gray8_trns"),
    fixture!("gray16_trns"),
    fixture!("graya8"),
    fixture!("graya16"),
    fixture!("rgb8"),
    fixture!("rgb16"),
    fixture!("rgb8_trns"),
    fixture!("rgba8"),
    fixture!("rgba16"),
    fixture!("pal1"),
    fixture!("pal2"),
    fixture!("pal4"),
    fixture!("pal8"),
    fixture!("pal8_trns"),
    fixture!("rgba8_adam7"),
    fixture!("gray16_adam7"),
    fixture!("pal4_adam7"),
];

#[test]
fn decode_conformance_over_the_full_matrix() {
    let limits = PngLimits::default();
    for (name, png, expected) in MATRIX {
        let decoded = decode_png(png, &limits).unwrap_or_else(|e| panic!("{name}: {e}"));
        assert_eq!(decoded.width, 13, "{name}");
        assert_eq!(decoded.height, 7, "{name}");
        assert_eq!(decoded.rgba, expected, "{name}: pixel mismatch");
    }
}

#[test]
fn source_provenance_is_reported() {
    let limits = PngLimits::default();
    let d = decode_png(MATRIX[4].1, &limits).unwrap(); // gray16
    assert_eq!((d.source_color_type, d.source_bit_depth), (0, 16));
    let d = decode_png(MATRIX[19].1, &limits).unwrap(); // rgba8_adam7
    assert_eq!((d.source_color_type, d.source_bit_depth), (6, 8));
    let d = decode_png(MATRIX[16].1, &limits).unwrap(); // pal4
    assert_eq!((d.source_color_type, d.source_bit_depth), (3, 4));
}

#[test]
fn gamma_srgb_precedence() {
    let limits = PngLimits::default();
    let srgb = include_bytes!("fixtures/png/intent_srgb_wins.png");
    let gamma = include_bytes!("fixtures/png/intent_gamma.png");
    // Both chunks present: sRGB wins.
    assert_eq!(
        decode_png(srgb, &limits).unwrap().intent,
        ColorIntent::Srgb { intent: 1 }
    );
    // Only gAMA: reported verbatim.
    assert_eq!(
        decode_png(gamma, &limits).unwrap().intent,
        ColorIntent::Gamma {
            gamma_100000: 100000
        }
    );
    // Neither: assumed sRGB.
    assert_eq!(
        decode_png(MATRIX[0].1, &limits).unwrap().intent,
        ColorIntent::AssumedSrgb
    );
}

fn lcg_rgba(w: u32, h: u32, mut state: u32) -> Vec<u8> {
    (0..w as usize * h as usize * 4)
        .map(|_| {
            state = state.wrapping_mul(1_664_525).wrapping_add(1_013_904_223);
            (state >> 24) as u8
        })
        .collect()
}

#[test]
fn encode_decode_round_trip() {
    let limits = PngLimits::default();
    for (w, h) in [(1u32, 1u32), (13, 7), (64, 33), (256, 3)] {
        let rgba = lcg_rgba(w, h, w * 31 + h);
        for level in [
            CompressionLevel::Fast,
            CompressionLevel::Default,
            CompressionLevel::Best,
        ] {
            let png = encode_rgba8(w, h, &rgba, level);
            let decoded = decode_png(&png, &limits).unwrap();
            assert_eq!((decoded.width, decoded.height), (w, h));
            assert_eq!(decoded.rgba, rgba, "{w}x{h} {level:?}");
        }
    }
}

#[test]
fn encode_is_deterministic() {
    let rgba = lcg_rgba(40, 25, 7);
    assert_eq!(
        encode_rgba8(40, 25, &rgba, CompressionLevel::Default),
        encode_rgba8(40, 25, &rgba, CompressionLevel::Default)
    );
}

/// Build a chunk with a valid CRC (for crafting hostile inputs).
fn chunk(name: &[u8; 4], body: &[u8]) -> Vec<u8> {
    let mut out = Vec::new();
    out.extend_from_slice(&(body.len() as u32).to_be_bytes());
    out.extend_from_slice(name);
    out.extend_from_slice(body);
    let mut tagged = name.to_vec();
    tagged.extend_from_slice(body);
    out.extend_from_slice(&crc32(&tagged).to_be_bytes());
    out
}

fn ihdr(w: u32, h: u32, depth: u8, color: u8) -> Vec<u8> {
    let mut body = Vec::new();
    body.extend_from_slice(&w.to_be_bytes());
    body.extend_from_slice(&h.to_be_bytes());
    body.extend_from_slice(&[depth, color, 0, 0, 0]);
    chunk(b"IHDR", &body)
}

const SIG: [u8; 8] = [137, 80, 78, 71, 13, 10, 26, 10];

#[test]
fn dimension_bomb_is_refused_before_inflate() {
    // 65535×65535 would be 4.3 gigapixels; the refusal happens at IHDR,
    // with the (tiny, never-inflated) IDAT still unread.
    let mut png = SIG.to_vec();
    png.extend(ihdr(65535, 65535, 8, 0));
    png.extend(chunk(
        b"IDAT",
        &fmn_codec::zlib_compress(&[0], CompressionLevel::Fast),
    ));
    png.extend(chunk(b"IEND", &[]));
    let limits = PngLimits::default();
    assert_eq!(
        decode_png(&png, &limits),
        Err(PngError::TooLarge {
            max_pixels: limits.max_pixels
        })
    );
}

#[test]
fn oversized_idat_is_bounded_by_geometry() {
    // A 1×1 gray image whose IDAT inflates far past the 2 bytes its
    // geometry declares: the inflater's budget refuses mid-stream.
    let mut png = SIG.to_vec();
    png.extend(ihdr(1, 1, 8, 0));
    png.extend(chunk(
        b"IDAT",
        &fmn_codec::zlib_compress(&vec![0u8; 100_000], CompressionLevel::Best),
    ));
    png.extend(chunk(b"IEND", &[]));
    assert!(matches!(
        decode_png(&png, &PngLimits::default()),
        Err(PngError::Inflate(_))
    ));
}

#[test]
fn chunk_count_bomb_is_refused() {
    let mut png = SIG.to_vec();
    png.extend(ihdr(1, 1, 8, 0));
    for _ in 0..5000 {
        png.extend(chunk(b"jnkx", &[]));
    }
    let limits = PngLimits::default();
    assert_eq!(
        decode_png(&png, &limits),
        Err(PngError::TooManyChunks {
            limit: limits.max_chunks
        })
    );
}

#[test]
fn malformed_pngs_are_typed_refusals() {
    let limits = PngLimits::default();
    let good_stream = fmn_codec::zlib_compress(&[0u8, 0x55], CompressionLevel::Fast);

    // Bad signature.
    assert_eq!(decode_png(b"JFIF....", &limits), Err(PngError::NotPng));

    // CRC corruption.
    let mut png = SIG.to_vec();
    png.extend(ihdr(1, 1, 8, 0));
    png.extend(chunk(b"IDAT", &good_stream));
    png.extend(chunk(b"IEND", &[]));
    let mut corrupt = png.clone();
    let idat_crc_at = corrupt.len() - 12 - 5;
    corrupt[idat_crc_at] ^= 0xff;
    assert_eq!(decode_png(&corrupt, &limits), Err(PngError::ChunkCrc));

    // Truncation.
    assert!(decode_png(&png[..png.len() - 4], &limits).is_err());

    // Filter byte outside 0..=4.
    let mut png = SIG.to_vec();
    png.extend(ihdr(1, 1, 8, 0));
    png.extend(chunk(
        b"IDAT",
        &fmn_codec::zlib_compress(&[9u8, 0x55], CompressionLevel::Fast),
    ));
    png.extend(chunk(b"IEND", &[]));
    assert_eq!(decode_png(&png, &limits), Err(PngError::BadFilter(9)));

    // Unknown critical chunk.
    let mut png = SIG.to_vec();
    png.extend(ihdr(1, 1, 8, 0));
    png.extend(chunk(b"ABCD", &[1, 2, 3]));
    png.extend(chunk(b"IDAT", &good_stream));
    png.extend(chunk(b"IEND", &[]));
    assert_eq!(
        decode_png(&png, &limits),
        Err(PngError::UnknownCritical(*b"ABCD"))
    );

    // Non-consecutive IDAT run.
    let mut png = SIG.to_vec();
    png.extend(ihdr(1, 1, 8, 0));
    png.extend(chunk(b"IDAT", &good_stream[..4]));
    png.extend(chunk(b"gAMA", &45455u32.to_be_bytes()));
    png.extend(chunk(b"IDAT", &good_stream[4..]));
    png.extend(chunk(b"IEND", &[]));
    assert_eq!(
        decode_png(&png, &limits),
        Err(PngError::BadIdat("IDAT run is not consecutive"))
    );

    // Indexed image without a palette.
    let mut png = SIG.to_vec();
    png.extend(ihdr(1, 1, 8, 3));
    png.extend(chunk(b"IDAT", &good_stream));
    png.extend(chunk(b"IEND", &[]));
    assert!(matches!(
        decode_png(&png, &limits),
        Err(PngError::BadPalette(_))
    ));

    // Palette index out of range.
    let mut png = SIG.to_vec();
    png.extend(ihdr(1, 1, 8, 3));
    png.extend(chunk(b"PLTE", &[10, 20, 30])); // one entry
    png.extend(chunk(
        b"IDAT",
        &fmn_codec::zlib_compress(&[0u8, 5], CompressionLevel::Fast),
    ));
    png.extend(chunk(b"IEND", &[]));
    assert!(matches!(
        decode_png(&png, &limits),
        Err(PngError::BadPalette(_))
    ));

    // Decompressed stream shorter than the geometry requires.
    let mut png = SIG.to_vec();
    png.extend(ihdr(2, 2, 8, 0));
    png.extend(chunk(
        b"IDAT",
        &fmn_codec::zlib_compress(&[0u8, 1, 2], CompressionLevel::Fast),
    ));
    png.extend(chunk(b"IEND", &[]));
    assert!(matches!(
        decode_png(&png, &limits),
        Err(PngError::WrongDataSize { .. })
    ));

    // Garbage soup never hangs.
    let soup: Vec<u8> = (0..4096u32).map(|i| ((i * 37) >> 3) as u8).collect();
    let _ = decode_png(&soup, &limits);
    let mut sig_soup = SIG.to_vec();
    sig_soup.extend(&soup);
    let _ = decode_png(&sig_soup, &limits);
}
